### ISSUE TITLE
default menu option - 'Http' is not highlighted when launched from installed pwa app (UI bug)

### ISSUE THREAD

**Issue by NileshSP** [liyasthomas/postwoman#100]
**Describe the bug**
After launching pwa app from desktop, default 'Http' menu is not highlighted

![image](https://user-images.githubusercontent.com/13110493/63991977-ca196a80-cab7-11e9-9a2e-0d1e50533e39.png)

**To Reproduce**
1. Go to 'postwoman.io'
2. Click on 'Install PWA'
3. Open Postwoman app from desktop
4. 'Http' is not highlighted

**Expected behavior**

![image](https://user-images.githubusercontent.com/13110493/63992157-9a1e9700-cab8-11e9-8c1e-7c30cbc217b1.png)

**Desktop :**
 - OS: Win 10
 - Browser chrome
 - Version latest

**Comment by liyasthomas** [comment]
Issue has been identified. Most probably its an issue with start URL of PWA. Will look into it ASAP.

**Comment by NileshSP** [comment]
Have found the issue after a bit of troubleshooting and have a solution, let me know if I can contribute by submitting a PR

**Comment by NBTX** [comment]
@NileshSP go for it!

**Comment by NileshSP** [comment]
@liyasthomas , @NBTX  - submitted PR #125

**Comment by liyasthomas** [comment]
Fixed on #125
