### ISSUE TITLE
Postman Web is now out. It might be great to find a USP for Postwoman

### ISSUE THREAD

**Issue by tvvignesh** [liyasthomas/postwoman#1000]
Hi. Just read an announcement about Postman for Web: https://web.postman.co/

Like postwoman for its design, being open source and light, but may be its time to find the USP now that postman has released the web version.

**Comment by liyasthomas** [comment]
Okay. Cool.

**Comment by AndrewBastin** [comment]
Lol this exactly took ticket 1000 😅😂
