### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by Mikolaj98p** [liyasthomas/postwoman#1006]
**Describe the bug**
On command `npm run dev` I have compile error and in browser display error

**To Reproduce**
1. Run `npm install`
2. Run `npm audit fix` (I try with this command and without)
3. Run `npm run dev`
In browser
```
 in ./components/layout/footer.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./components/layout/footer.vue?vue&type=script&lang=js&)
Module not found: Error: Can't resolve '../../.postwoman/version.json' in 'D:\programs\node\postwoman-1.9.7\components\layout'
```
In cmd
```
 ERROR  Failed to compile with 1 errors                                                       friendly-errors 09:49:18

This relative module was not found:                                                           friendly-errors 09:49:18
                                                                                              friendly-errors 09:49:18
* ../../.postwoman/version.json in ./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./components/layout/footer.vue?vue&type=script&lang=js&
```

**Screenshots**
![Zrzut ekranu (3)](https://user-images.githubusercontent.com/20612773/87913590-a06e8680-ca6f-11ea-8718-e3c9e8eccc45.png)

**Desktop (please complete the following information):**
 - OS: Win10 TH2
 - Browser: Chrome 83.0.4103.116

PS: Sory for my bad english.

**Comment by liyasthomas** [comment]
**Step 1**
Create a folder named `.postwoman` in root directory.

**Step 2**
Create a file named `version.json` file inside `.postwoman` folder.

**Step 3**
Paste the following line in `version.json` file.
```
{"name":"v1.9.7"}
```

Detailed explained: `version.json` is dynamically created when we run the `build.js` script.

Let me know if the issue isn't solved.
