### ISSUE TITLE
postwoman google login doesn't work behind ingress or reverse proxy

### ISSUE THREAD

**Issue by JavadHajiani** [liyasthomas/postwoman#1009]
**Describe the bug**
Google login doesn't work when you deploy postwoman behind reverse proxy or ingress

**To Reproduce**
Easiest way to reproduce is run below docker-compose and login to google by http://localhost:80 (reverse_proxy) instead of http://localhost:3000 (postwoman direct)

https://gist.github.com/javad-hajiani/c604f42e3fc0068ae65b482a3adf8278

**Expected behavior**
google login work properly like what you have already without reverse_proxy

**Desktop (please complete the following information):**
 - OS: ubuntu 18.04
 - Browser chromium
 - Version 83

**Comment by liyasthomas** [comment]
Login is disabled for all request URLs except `postwoman.io` due to security concerns. Kindly use [postwoman.io](https://postwoman.io) to make use of sync feature.

**Comment by schndr** [comment]
@liyasthomas iyasthomasCan you please elaborate the security concerns in details?
