### ISSUE TITLE
User login is disabled after i run it on our local server.

### ISSUE THREAD

**Issue by zhangzhaohong** [liyasthomas/postwoman#1012]
We hope to run it on our local server so that we can manage our team, at first we hope to login and share the collections and documents to anyone in  our team, so can you help us to make the ability to login by local user in the database, and manage our team in the system?

**Comment by liyasthomas** [comment]
- For local development checkout [How to set up local development](https://github.com/liyasthomas/postwoman#developing-)

- Checkout out [Wiki on Hosting](https://github.com/liyasthomas/postwoman/wiki/Hosting)

**Comment by zhangzhaohong** [comment]
> * For local development checkout [How to set up local development](https://github.com/liyasthomas/postwoman#developing-)
> * Checkout out [Wiki on Hosting](https://github.com/liyasthomas/postwoman/wiki/Hosting)

yeah, we have build it local on our local server, but we cannot login and manage the team, so can you help us to approve the login ability by update the project?

**Comment by liyasthomas** [comment]
Step 1:
Set up local development environment. You've completed this step.

Step 2:
Create a Firebase project and obtain app's access keys.

Step 3:
Rename `.env.example` to `.env` and fill it with your own Firebase API keys.

**Comment by zhangzhaohong** [comment]
> Step 1:
> Set up local development environment. You've completed this step.
> 
> Step 2:
> Create a Firebase project and obtain app's access keys.
> 
> Step 3:
> Rename `.env.example` to `.env` and fill it with your own Firebase API keys.
> 
> Make sure you added Sign in with Google / GitHub from Firebase Dashboard.

OK thanks. I will have a try.
