### ISSUE TITLE
Why some Chrome do not have the ability to install PWA?

### ISSUE THREAD

**Issue by zhangzhaohong** [liyasthomas/postwoman#1015]
I have tried so many times, but i found that PWA do not show to the users and let us install it. I only see it when i use the domain name is "localhost", can you give us some solution to  solve this problem.

**Comment by liyasthomas** [comment]
Update the browser to it's latest version. Most browsers have option to install PWA. If the option isn't available, try adding the site to Home screen by going to "More options" > "Add to Home Screen" in Chrome.

This issue isn't related to PW hence closing.

**Comment by zhangzhaohong** [comment]
> Update the browser to it's latest version. Most browsers have option to install PWA. If the option isn't available, try adding the site to Home screen by going to "More options" > "Add to Home Screen" in Chrome.
> 
> This issue isn't related to PW hence closing.

I have tried it, but PWA is not exist, i found it is available in your demo site.

**Comment by liyasthomas** [comment]
PWA will only be available for sites hosted in `HTTPS` thus, `localhost` won't have PWA.

**Comment by zhangzhaohong** [comment]
> PWA will only be available for sites hosted in `HTTPS` thus, `localhost` won't have PWA.

But why it can show to us when i use localhost and dismiss in HTTPS site.

**Comment by liyasthomas** [comment]
PWA won't work with localhost. You should deploy the app in a HTTPS site.
