### ISSUE TITLE
Autoresize the textarea

### ISSUE THREAD

**Issue by reefqi037** [liyasthomas/postwoman#102]
**Is your feature request related to a problem? Please describe.**
No (I think)

**Describe the solution you'd like**
Autoresize the textarea parts such as "Parameter List" and "Header List" so that the rows increase/decrease accordingly when Parameters or Headers are being added/remove instead of showing the scrollbar inside.

**Describe alternatives you've considered**
- Do not show the list at all?
- Use vuetify textarea with auto-grow properties enabled

**Additional context**

![header](https://user-images.githubusercontent.com/44827833/63996953-13a99a00-cb38-11e9-880c-e6c90f339146.PNG)

**Comment by liyasthomas** [comment]
> Use vuetify textarea with auto-grow properties enabled

Will consider this approach.

**Comment by izerozlu** [comment]
Resolved by #111. Closing.
