### ISSUE TITLE
integrate parameters with history

### ISSUE THREAD

**Issue by sdavey** [liyasthomas/postwoman#1020]
sadly the API I'm testing using the query string for all calls, even PUT and POST

I'd like to use Collections to switch back and forth between different tests. Currently parameters are not stored in Collections. I'd like the option for parameters to be restored via Collections, including being cleared when there aren't any parameters.

**Comment by sdavey** [comment]
I see that Collections are what I should be using instead of the history list. The problem is the same though, parameters are not saved as part of a collection. Please consider saving parameters with collections (and history too, just to be consistent).

**Comment by liyasthomas** [comment]
I guess parameters are already restored when you "restore a hitoy" item. I just tried and it ok at my end.

**Comment by sdavey** [comment]
I'm glad to hear that. Unfortunately it's not working for me in Safari. I thought I had the latest version of Postwoman but maybe not. I'll see if I can figure it out.

**Comment by liyasthomas** [comment]
https://postwoman.io is the live version.

**Comment by sdavey** [comment]
thanks, but I'm testing with both postwoman and my service on my local network so I think postwoman.io won't work for me. The one I'm using is version 1.9.7 but looks a little different than the one on postwoman.io.

**Comment by sdavey** [comment]
btw, thanks for creating such an awesome tool!! I'll close this issue.

**Comment by liyasthomas** [comment]
It would be better if you could use the latest version (postwoman.io). And I appreciate if you could provide some logs / steps to reproduce issue so that I can track it down.

**Comment by sdavey** [comment]
ok, I'll give that a try tomorrow.

**Comment by sdavey** [comment]
good morning. I've updated to the latest version. I may have figured out what's going on. If I type parameters as part of the url, everything seems to work. But if I change the parameters by using "Add new" and the trashcan buttons, those seem to affect other requests in my collection. I haven't figured out the exact pattern. It may be that deleting a parameter deletes parameters of the same name in other requests in the collection. Sometimes adding a parameter (using "Add new") also adds the parameter to other requests in the collection. Anyway, typing in the url seems to work now. Thanks!

**Comment by liyasthomas** [comment]
Can you produce a screech record of the mentioned behaviour?
