### ISSUE TITLE
Details on fail requests

### ISSUE THREAD

**Issue by amireshoon** [liyasthomas/postwoman#1034]
**Is your feature request related to a problem? Please describe.**
Sometimes we need to see content and status code for request when it even failed.
For example, I have an API that returns `401` when `authentication` failed, It also returns a son content but in postWomen, I only can see my request has been failed!

**Describe the solution you'd like**
I personally like to see status code and the content of requests even it fails!

**Comment by AndrewBastin** [comment]
@amireshoon Browser extension version 0.15 has implemented this feature ^_^

I just pushed the changes so it is still in review for Chrome Web Store, but it is up in Firefox Add-ons!

Will let you know when it becomes live on Chrome!

**Comment by amireshoon** [comment]
Nice work @AndrewBastin .

**Comment by AndrewBastin** [comment]
@amireshoon The new version is live on Chrome Web Store!

Closing the issue.
