### ISSUE TITLE
Method dropdown is not keyboard navigable

### ISSUE THREAD

**Issue by z33212** [liyasthomas/postwoman#1106]
**Describe the bug**
Currently, there doesn't appear to be any way to change the request method using the keyboard. This seems to be caused by the fact that this dropdown component uses an `<input>` instead of a `<select>`, with a popover used to recreate native functionality. This behavior seems to be unique to this dropdown, since the rest appear to use a native `<select>`.

**To Reproduce**
- On the homepage of the app, press tab to navigate to to the "method" dropdown. 
- Once this dropdown has focus, attempt to change its value with the arrow keys

**Expected behavior**
I would expect this dropdown to behave like the other dropdowns in the app which use a native select so that they are fully keyboard navigable.

**Screenshots**
![image](https://user-images.githubusercontent.com/60930762/90968813-e8ddf180-e4be-11ea-9e78-903f904d5beb.png)

**Additional context**
I'm working with a team that has considered moving away from Postman for our API testing due to accessibility issues (the Postman app has almost no keyboard navigability). We were super excited to find Postwoman because it has MUCH better keyboard navigability overall! 😃 This is especially important because some of our developers are blind and need to use the keyboard to get around. One dev let me know though, that he couldn't seem to be able to change the HTTP method. Like I said, Postwoman is otherwise really awesome in this department, so it would be great if this could be fixed so everybody could use the app to its fullest.

**Comment by z33212** [comment]
> Hey @z33212 , let me know if #1107 solves your issues. We're open to any feedbacks regarding making Hoppscotch work for everyone.

Just tried this out -- the keyboard shortcuts work and I was able to change the method with the keyboard alone, awesome! In my opinion it still might be worth revisiting this dropdown to make it behave more like a native select later, since using the arrow keys doesn't appear to work, and a person who is using the keyboard would expect that they can change the options with the arrow keys. The only issue with special keyboard shortcuts is that a user wouldn't immediately know that they have those available, so a developer with vision impairments might still be confused (at least at first). But that's relatively minor -- I confirmed that the shortcuts work and that's great! Thanks so much! Our whole team can use the app now for testing. 😁

**Comment by liyasthomas** [comment]
@z33212 I really wanted to implement that native select with last iteration itself. But the component we used isn't supporting key binding. I'll need lil more time to figure out either go with a native select or add key binding feature to that select component. Stay with us - will update as soon as it's implemented. Do drop you valuable comments on anything that need to be implemented.
