### ISSUE TITLE
Change .editorconfig

### ISSUE THREAD

**Issue by NBTX** [liyasthomas/postwoman#115]
Can we please change the editor config to

```
indent_size = 2
indent_style = tab
```

At the very least, I think `indent_style` should be tab, as the tabs can be visually changed in the editor to the developer's preference.
I think `indent_size` should be changed because when set to 1, it's actually hard to see where the lines are indented.

**Comment by liyasthomas** [comment]
Proceed

**Comment by izerozlu** [comment]
That would be great! And some formatting committed also.

When I try to format on my local, still changes a lot of lines.
