### ISSUE TITLE
Handling request failures when build number is obtained from GitHub

### ISSUE THREAD

**Issue by NBTX** [liyasthomas/postwoman#122]
Per discussion in #121, this issue is to determine what we should do if we can't get the latest build number from GitHub at build time. The options I can think of are as follows:

1. Hide the name section in the version information.
2. Use 'deep clone' on Travis and get the tag from the git history. (Could make builds slower over time but probably wouldn't have that big an impact)
3. Get it from `package.json` but make sure the value in `package.json` stays up-to-date. (Perhaps use GitHub Actions or something to automatically change it to the version number in GitHub releases?) - Overall this is my preferred option.

/CC: @larouxn @liyasthomas

**Comment by liyasthomas** [comment]
I vote for updating version number from package.json
This seems the correct way to handle this, it also helps in tags as well.

**Comment by NBTX** [comment]
Actually funny thing, I decided 2 was my favorite option but then I came up with 3 because I wanted to put 3 things instead of 2 lol.
So thinking about it, I also prefer 3.

**Comment by larouxn** [comment]
We _should_ keep package.json version up to date anyway. So, if a solution for build numbers _also_ ensures that, then that's a double win. 🙌

**Comment by NBTX** [comment]
Exactly! ^

**Comment by liyasthomas** [comment]
@NBTX this issue seems to be absolute.  Would you mind closing it?

**Comment by NBTX** [comment]
@liyasthomas absolute?

**Comment by liyasthomas** [comment]
Sorry. Oftentimes, version number is still fetched from `package.json` causing version tag without "v" before the tag. This issue is persisting.

**Comment by NBTX** [comment]
Webhook test.

**Comment by liyasthomas** [comment]
Now the version number is correctly fetching from package.json and release tag, so I think I should this issue.
