### ISSUE TITLE
Use 'icon buttons' instead of 'text buttons'

### ISSUE THREAD

**Issue by liyasthomas** [liyasthomas/postwoman#130]
**Is your feature request related to a problem? Please describe.**
Icons buttons with svg would be better than plain text buttons. Use line icons.

**Describe the solution you'd like**
Icons are self explanatory. Buttons like copy, delete etc can be replaced with icon buttons

**Describe alternatives you've considered**
Use text buttons :(

**Additional context**
Icons buttons should not stretch as flex buttons would. Icons buttons should have mataching height and fixed width.

**Comment by NBTX** [comment]
:+1: I recommend [iconmonstr](https://iconmonstr.com/) for the icons. I used it for the Settings icon and their license is extremely permissive (no attribution required and completely free to use)

**Comment by liyasthomas** [comment]
I'll do it.

**Comment by liyasthomas** [comment]
aa1d3c6943b37d6699699f4119c8941c0eaf7bd8 fixed this hencing closing.
