### ISSUE TITLE
Please add a label for each request. It will be helpful.

### ISSUE THREAD

**Issue by MoonSmile1707** [liyasthomas/postwoman#133]
When i post or get a request and then i want to use it again. But i don't know where it is... same issue on postman... 
Please add a label for each request. :D

**Comment by liyasthomas** [comment]
History section has entries with Status code, URL, Path, timestamp. Isn't that enough?

**Comment by liyasthomas** [comment]
This could be related to #29 
A collection of requests with a common label/name would be :100: helpful. Make a collection of such requests and ability to share them.

**Comment by MoonSmile1707** [comment]
when i work with GraphQL. It was enough to find a request quickly. thanks <3

**Comment by sharath2106** [comment]
@liyasthomas I would like to work on this issue. Let me know if no one has claimed to work on this yet.

**Comment by liyasthomas** [comment]
@sharath2106 You're welcome. Assigning to you.

**Comment by sharath2106** [comment]
@liyasthomas You should be getting a PR by today or tomorrow. First timer here.

**Comment by liyasthomas** [comment]
_There is always a first._

**Comment by liyasthomas** [comment]
@sharath2106 just thought I should ping you for PR.

**Comment by sharath2106** [comment]
Done with setting up data and the text box for the request name. Rendering the same in the history section is not happening even after introducing the fields in history.vue component and index.vue.
<img width="1226" alt="Screenshot 2019-10-04 at 7 51 03 AM" src="https://user-images.githubusercontent.com/25933070/66176609-08d4ae80-e67c-11e9-8d75-3f7c2d88bd6b.png">
<img width="1220" alt="Screenshot 2019-10-04 at 7 50 53 AM" src="https://user-images.githubusercontent.com/25933070/66176610-08d4ae80-e67c-11e9-9c41-6bed147615b9.png">

**Comment by liyasthomas** [comment]
History data is fetched from localStorage. And also binded to it. After sanding the request, check `Dev tools > Application tab > Local storage > http://localhost:300 > history` to see entries.

**Comment by sharath2106** [comment]
Have tried to print the history entry in the console

<img width="1680" alt="Screenshot 2019-10-04 at 10 43 29 AM" src="https://user-images.githubusercontent.com/25933070/66182765-fbc3b980-e693-11e9-8b2e-bb6f6d124883.png">

This is the local storage - 
<img width="1680" alt="Screenshot 2019-10-04 at 10 42 44 AM" src="https://user-images.githubusercontent.com/25933070/66182766-fbc3b980-e693-11e9-8d06-9b00940dde19.png">

**Comment by liyasthomas** [comment]
@sharath2106 everything seems okay to me.

`<input aria-label="Label" type="text" readonly :value="entry.label">`

Add 👆 this to history.vue

```
<ul v-for="(entry, index) in filteredHistory" :key="index" class="entry">

(👈 here)

....
......
....

</ul>
```

And repost.

**Comment by sharath2106** [comment]
@liyasthomas Have already added those lines and then docker-compose up. 

<img width="1171" alt="Screenshot 2019-10-04 at 11 11 24 AM" src="https://user-images.githubusercontent.com/25933070/66183799-b99c7700-e697-11e9-81d4-a9f1843e54d9.png">

**Comment by liyasthomas** [comment]
@sharath2106 could make a PR for all changes till now, I'll look into it.
