### ISSUE TITLE
 introduce some script language to parse the response and pass environment variable as request parameter 

### ISSUE THREAD

**Issue by yrong** [liyasthomas/postwoman#139]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yrong** [comment]
with postman we can parse result with javascript and save data to somewhere
`
var jsonData = JSON.parse(responseBody);
tests["uuid found"] = jsonData.uuid;
postman.setEnvironmentVariable("production_id", jsonData.uuid);
`

then in the next request we can reference the saved data
`
http://{{api_host}}:{{api_port}}/api/knowledge_point/{{production_id}}
`

This feature is vital for the CI flow

**Comment by Nachiappa** [comment]
Hi @liyasthomas ,
Do we have environment setup in current postwoman to implement this ?

**Comment by liyasthomas** [comment]
@Nachiappa at present, there's no environment support.

**Comment by Nachiappa** [comment]
Ok . Should we manage it in a separate ticket as an enhancement task?

**Comment by liyasthomas** [comment]
That sounds okay.
I think it would be great to have this feature implemented. Environment setup along with import/export functionalities soothes things up.

**Comment by Nachiappa** [comment]
@liyasthomas Please review [https://github.com/liyasthomas/postwoman/issues/147](url)

**Comment by jgroom33** [comment]
If possible, all responses should automatically be parsed. No code should be required to parse a response. All responses should be available for reference via {{ foo.response.bar }} in a subsequent call.

**Comment by NBTX** [comment]
Please refer to #218
