### ISSUE TITLE
Inconsistent version name

### ISSUE THREAD

**Issue by larouxn** [liyasthomas/postwoman#141]
**Describe the bug**
Sometimes our version name is prepending with  `v`, something it's not. This breaks the links added in https://github.com/liyasthomas/postwoman/pull/135.

In prod we _don't_ have a `v`:
<img width="1211" alt="Screen Shot 2019-09-08 at 23 33 50" src="https://user-images.githubusercontent.com/1557529/64489720-5898a380-d291-11e9-9a18-2fe5b3a3f4c0.png">

In dev we _do_ have a `v`:
<img width="1230" alt="Screen Shot 2019-09-08 at 23 33 54" src="https://user-images.githubusercontent.com/1557529/64489721-5afafd80-d291-11e9-8b6d-33a303a37e8b.png">

**To Reproduce**
1. Go to the app in prod | [https://postwoman.io](https://postwoman.io)
2. Got to the app in dev | [http://localhost:3000/](http://localhost:3000/)
3. Compare the release version tags in the footer
4. Notice they're different and the link is broken in prod

**Expected behavior**
They're the same, `v0.1.0` on both, in this case.

**Comment by liyasthomas** [comment]
* In `package.json`, version is specified without `v`
* In GitHub releases, tag is specified with `v`

In dev mode, version is picked from `package.json`
Whereas at prod build, version is taken from env tag, ie: Release Tag

This might be the reason why at dev mode, version link is broken and at production link is working. We need to unify source from which tag is selected.

**Comment by larouxn** [comment]
Everything seems to working as desired now.
<img width="1227" alt="Screen Shot 2019-09-15 at 19 52 55" src="https://user-images.githubusercontent.com/1557529/64920412-78c8e500-d7f2-11e9-8eec-4b30581317e1.png">
<img width="1243" alt="Screen Shot 2019-09-15 at 19 53 05" src="https://user-images.githubusercontent.com/1557529/64920413-78c8e500-d7f2-11e9-80da-ae4fbc20047e.png">
