### ISSUE TITLE
A place to discuss

### ISSUE THREAD

**Issue by AndrewBastin** [liyasthomas/postwoman#149]
Just wanted to put out a request for a place to discuss postwoman related stuff in a convenient way. GitHub doesn't exactly offer a way to discuss stuff in a freeform way (without opening issues and stuff, just a general flow of ideas).

Could we have a chat room in [gitter](https://gitter.im/) or something similar ? (Discord, Slack, Telegram ?)

Bonus : Would give users a space to get live help.

**Comment by AndrewBastin** [comment]
Also a separate dev and help channels will be awesome

**Comment by liyasthomas** [comment]
A telegram group would be enough

**Comment by AndrewBastin** [comment]
@liyasthomas a mention of this in the README will be nice

**Comment by liyasthomas** [comment]
Will do in next commit

**Comment by liyasthomas** [comment]
Added Telegram group link to README on 8dadec62209715ae7b6c0510d59045880fc22591 hence closing

**Comment by hosseinnedaee** [comment]
I tried to join the channel, but Telegram isn't easily accessable in my region.

**Comment by liyasthomas** [comment]
I could start a gitter or discord group if you prefer

**Comment by hosseinnedaee** [comment]
I prefer discord.

**Comment by liyasthomas** [comment]
@hosseinnedaee https://discord.gg/GAMWxmR
