### ISSUE TITLE
Send Again Button Constantly Flickering

### ISSUE THREAD

**Issue by QasimArif** [liyasthomas/postwoman#157]
**Describe the bug**
When visiting the mobile site, the Send Again and Send button constanly flicker. This only occurs when you're at the top of the page. 

**To Reproduce**
1. Go to 'https://postwoman.io/'
2. Scroll to the very top. See buttons flicker. 

**Expected behavior**
No flickering

**Screenshots**

[Screen recording](https://drive.google.com/file/d/15cJJ07h-fS9W6ThRV3Oulgy0xXh2k2El/view?usp=drivesdk) 

**Smartphone (please complete the following information):**
 - Device: Huawei Mate 20 Pro
 - OS: Android
 - Browser: Chrome

**Comment by liyasthomas** [comment]
Issue has been identified. Will get back to you ASAP.

**Comment by liyasthomas** [comment]
It has been found that, this issue is caused by different viewport on mobile devices. And it is a device specific bug. Since it's not a universal bug, it somehow went unnoticed.
Working on a fix right now.

**Comment by NBTX** [comment]
@liyasthomas perhaps we should just hide the send again button until the first request has been sent? That kind of kills two birds with one stone for me, so to speak.

**Comment by yemkhaung** [comment]
Device: **Galaxy S5 (Chrome Dev Tools)**

Found that it flickers at a certain point of scrolling. Also saw a IntersectionObserver toggling "show" CSS class). Not sure that's the case.
