### ISSUE TITLE
Response with content-type "application/hal+json" shows as [Object object]

### ISSUE THREAD

**Issue by davidyscott** [liyasthomas/postwoman#158]
**Describe the bug**
A picture says a thousand words here.  Also note that this is a recent regression; earlier versions worked as desired (I know this isn't super helpful since I don't know which exact commit broke it)
![Screenshot from 2019-09-23 10-49-48](https://user-images.githubusercontent.com/5116327/65449682-53d70200-ddf0-11e9-82ab-5377768be96e.png)

**To Reproduce**
1. Find a service endpoint that returns a content-type of "application/hal+json"
2. Make a request to said endpoint
3. Observe the response shows "[Object object]"

**Expected behavior**
The actual response is shown, ideally rendered prettily as JSON.

**Comment by AndrewBastin** [comment]
Thanks for opening up the issue.

I will look into this.

**Comment by AndrewBastin** [comment]
@davidyscott I have submitted a PR.

Feel free to test my (fork)[https://github.com/AndrewBastin/postwoman] and please do report if the issue still persists.

**Comment by davidyscott** [comment]
@AndrewBastin Yayy thank you!  :)
