### ISSUE TITLE
Add Docker

### ISSUE THREAD

**Issue by jgroom33** [liyasthomas/postwoman#164]
it would be nice to have no install dependencies except docker.

expected behavior: `docker run -it -p 3000:3000 liyasthomas/postwoman:latest`

**Comment by jgroom33** [comment]
@liyasthomas 
“Set up Automated Builds using GitHub and Docker Hub” by oleksii_y https://link.medium.com/AmD5s8x6f0

**Comment by liyasthomas** [comment]
We're already making use of Travis CI for deployments. And I'm not experienced with docker. Would you care to explain docker CD advantages over other CIs?

**Comment by jgroom33** [comment]
the requirement is:
Publish an image to docker hub liyasthomas/postwoman

This account needs to exist so the image can be published there.

Then the image needs to be pushed there.

It's probably possible to do this with Travis, but it would require that to be setup in Travis. (Ie add a token for docker hub in Travis)

If docker hub is used, the process is easier. Just link your GitHub account from docker hub and it will watch for new releases. When a new release is published, it builds the image using the docker file and publishes it.

**Comment by liyasthomas** [comment]
Cool! Let me do a background check on it and will let you know.

**Comment by liyasthomas** [comment]
Closed by accident

**Comment by liyasthomas** [comment]
@jgroom33 https://hub.docker.com/r/liyasthomas/postwoman

**Comment by jgroom33** [comment]
Works great. Now just need to update the readme with:
`docker run -p 3000:3000 liyasthomas/postwoman:latest`

**Comment by liyasthomas** [comment]
Will do

**Comment by liyasthomas** [comment]
@jgroom33 can you tell me why docker taking ~12 mins to build? Any optimizations you wanna suggest to `dockerfile`?

**Comment by jgroom33** [comment]
Where are you seeing the 12 minutes?
One of the things that would be good is to use an alpine image. They are much smaller (50M compared to 300M)
But that would only impact time if the root image is being downloaded each build.
I tried to use an alpine image originally, but the build failed.

**Comment by liyasthomas** [comment]
Build duration was 12 mins.
Let me see if I could build with alpine rather than buster.

**Comment by jgroom33** [comment]
https://hub.docker.com/_/node/?tab=tags&page=1&name=alpine

**Comment by jls-tschanzc** [comment]
Another improvement might be to use [tini](https://github.com/krallin/tini) and switching from "npm run start" to directly executing the nuxt command. Just add "tini" to the `apk add` command and then switch the CMD line with:
```
ENTRYPOINT ["/sbin/tini", "--"]
CMD ["nuxt", "start"]
```

Another nice to have feature might be a [healthcheck](https://docs.docker.com/engine/reference/builder/#healthcheck), something like this:
```
HEALTHCHECK --interval=5m --timeout=3s CMD curl --fail http://localhost:3000/health || exit 1
```

I am not entirely sure how nuxt works and what dependencies it needs for runtime but maybe it could further slim down the resulting image by using a [multi stage build](https://docs.docker.com/develop/develop-images/multistage-build/) so you would prepare everything for the `npm run build` in the first stage and run the build and then in the second stage you would only copy over the resulting build artefacts and set `ENV NODE_ENV production` as well as run only `npm install --only=prod` (IF all the `dependencies` are even required for nuxt to run).

**Comment by pidario** [comment]
Sorry to comment under a closed issue, but in response to the previous comment I tried this Dockerfile:

```
FROM node:12.10.0-alpine as builder

WORKDIR /app

# Add git as the prebuild target requires it to parse version information
RUN apk add --update --no-cache \
  git \
  tini \
  ca-certificates

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build
######################################################################################
FROM node:12.10.0-alpine as runner

LABEL maintainer="Liyas Thomas (liyascthomas@gmail.com)"

COPY --from=builder /sbin/tini /sbin/tini
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt

WORKDIR /app

COPY --from=builder /app .

EXPOSE 3000

ENTRYPOINT ["/sbin/tini", "--"]
CMD ["node_modules/.bin/nuxt", "start"]
```

I added tini as suggested and I also took the liberty to add ca-certificates.

I usually build this Dockerfile by using two different commands in sequence:
`docker build --target builder -t builder-postwoman:latest .`
This image is used for caching purposes only and is not pushed to docker hub: note the tag is just builder-postwoman;
and then
`docker build --target runner -t liyasthomas/postwoman:latest .`
This one instead has the usual tag you currently use and will be pushed to DH.

The image got shrunk down to 303MB, which is not bad for a nodejs application this large but probably you could still improve it by installing production dependencies only (for example you don't need test suite in production) as suggested by @jls-tschanzc
