### ISSUE TITLE
Headers turn into 0 : [Object object]

### ISSUE THREAD

**Issue by davidyscott** [liyasthomas/postwoman#166]
**Describe the bug**
Headers specified in the "Headers" section do not get sent correctly on the request.  Instead, they are sent with the key as a zero-indexed integer and the value as "[Object object]".  That is, if I specify one header, let's say `abcd : efgh` the actual request will have `0 : [Object object]`.  If I specify two headers, the request will have `1 : [Object object]` as well.

**To Reproduce**
1. Open Postwoman, set up a request
1. Configure one or more headers
1. Open your browser's Network Tools
1. Send the request
1. In the Network Tools, observe that the header you wanted was not sent, but `0 : [Object object]` was

**Comment by liyasthomas** [comment]
Issue has been identified.

**Comment by davidyscott** [comment]
@liyasthomas WOW SO FAST!!!

**Comment by liyasthomas** [comment]
Please verify that issue has been solved

**Comment by davidyscott** [comment]
@liyasthomas Verified!  Thanks so much!  :D
