### ISSUE TITLE
Content-Type is always set to application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by davidyscott** [liyasthomas/postwoman#167]
**Describe the bug**
Regardless of what I select from the Content Type dropdown, requests are actually sent with the header "Content-Type: application/x-www-form-urlencoded".

**To Reproduce**
1. Open Postwoman and your browser's Network Tools
1. Make a POST or PUT request with Content Type of "application/json" selected
1. Observe that the request was actually sent with the header "Content-Type: application/x-www-form-urlencoded"

**Expected behavior**
The correct Content-Type header is sent.

**Comment by liyasthomas** [comment]
I failed to reproduce this issue

**Comment by AndrewBastin** [comment]
I tested the behavior both from the server and client side, the content-type header seems to be sent fine.

**Comment by davidyscott** [comment]
:(  I can't repro it anymore either.  Probably some sort of user error!!

**Comment by flleeppyy** [comment]
Hiya, I'm having this issue. I'm only sending query parameters. My body is set to none, yet in the request sent by Hoppscotch, the content type is set to `application/x-www-form-urlencoded`
![image](https://github.com/hoppscotch/hoppscotch/assets/18307183/3880c6ac-0037-4e50-bc0d-4c4b578322bf)
![image](https://github.com/hoppscotch/hoppscotch/assets/18307183/d7107db6-6e53-4fff-8b47-6afffe81a627)
