### ISSUE TITLE
Docker-compose in development

### ISSUE THREAD

**Issue by nickpalenchar** [liyasthomas/postwoman#168]
Since we recently Dockerized  in #164, I'm happy to add docker-compose.yml configuration for development with docker. 

The main advantage would be that a developer could have a fully working dev environment by running `docker-compose up`, no need to install anything else. An added bonus is that the local environment would be much closer to production.

`docker-compose` is also a nice "layer", in that devs who don't wish to use it can still run development as it runs now.

Containerization is a primary responsibility in my day job so I'd love to add that here--let me know what you think!

**Comment by liyasthomas** [comment]
@nickpalenchar you are good to go. Com'n.. this is our project, we make this better for everyone! 🚀

**Comment by liyasthomas** [comment]
#169 resolves this hence closing
