### ISSUE TITLE
Send request on Enter Key press

### ISSUE THREAD

**Issue by aashutoshrathi** [liyasthomas/postwoman#17]
**Is your feature request related to a problem? Please describe.**
It will be easy if on pressing enter I can send the request.

**Describe the solution you'd like**
A simple onClick event listener to top 3 inputs, which will validate and submit the form if `event.keyCode === 13`.

**Comment by AndrewBastin** [comment]
@liyasthomas please close the issue as the associated PR is merged.

**Comment by liyasthomas** [comment]
#23 fixes this issue.

**Comment by aashutoshrathi** [comment]
Cool.
Thanks for considering.
