### ISSUE TITLE
Allow HTTP (not HTTPS) on postwoman.io

### ISSUE THREAD

**Issue by NBTX** [liyasthomas/postwoman#175]
Currently postwoman.io redirects insecure requests to HTTPS.
Whilst this is often desirable, it prevents us from testing HTTP-only sites.

So essentially, we just need to disable this redirect.

**Comment by liyasthomas** [comment]
Browser will block any resources (scripts , link , iframe , XMLHttpRequest, fetch) to download if original html page is in https and request resources are in http.

Browser throws an Mixed Content error.

> https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content

Only work around I found is to tweak browser security policies and allow http requests.

**Comment by hosseinnedaee** [comment]
Maybe we should use a proxy server. send the request to proxy server fetch HTTP request on the server and then return back the response to Postwoman client.

**Comment by liyasthomas** [comment]
Proxy implementation with Nuxt middleware is planned. @hosseinnedaee would you like to work on this feature?

**Comment by hosseinnedaee** [comment]
yeah sure @liyasthomas 
do you have any idea about implementation or I just start to work on it?

**Comment by liyasthomas** [comment]
@hosseinnedaee #2 had an active discussion around implementing middleware for proxy. This not only allow us to request for http but also solves CORS issues. NBTX is busy and couldn't follow this.

Later our team took it to telegram group chat for further discussions. Follow from thia chat for discussion https://t.me/postwoman_app/72

**Comment by hosseinnedaee** [comment]
@liyasthomas Assign me to this issue.

**Comment by frankli0324** [comment]
websocket support on this?

**Comment by liyasthomas** [comment]
@NBTX is working on proxy mode for WebSocket.

**Comment by DiegoMGar** [comment]
Not done yet?

**Comment by frankli0324** [comment]
need help？

**Comment by liyasthomas** [comment]
@frankli0324 we would love to have this feature implemented. do contribute.

**Comment by frankli0324** [comment]
will take a look next week... got some schedules this weekend

**Comment by interfacekun** [comment]
Not done yet?

**Comment by frankli0324** [comment]
what I've done so far:

I tried to create a single nginx server configuration for everyone who wants to build up their own proxy server:
```conf
server {
	server_name your_own_doman;
	listen 443 ssl;
	include /etc/nginx/conf.d/ssl; // certificate, key
	resolver 8.8.8.8;
	location / {
		if ( $arg_target = '' ) { return 403 'null target'; }
		if ( $arg_scheme = '' ) { set $arg_scheme 'http'; }
		if ( $arg_scheme = 'ws' ) { set $arg_scheme 'http'; }
		if ( $arg_scheme = 'wss' ) { set $arg_scheme 'https'; }
		if ( $arg_scheme = 'http' ) { set $port '80'; }
		if ( $arg_scheme = 'https' ) { set $port '443'; }
		if ( $arg_port != '' ) { set $port $arg_port; }
		set $query '';
		set $path '';
		rewrite_by_lua_block { // on debian/ubuntu: libnginx-mod-http-lua
        	ngx.var.query = ngx.unescape_uri(ngx.var.arg_query)
			ngx.var.path = ngx.unescape_uri(ngx.var.arg_path)
        }
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "upgrade";
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_pass $arg_scheme://$arg_target:$port$path?$query;
	}
}
```

and made a little change
```diff
diff --git a/components/realtime/websocket.vue b/components/realtime/websocket.vue
index fba150e..9c7e56c 100644
--- a/components/realtime/websocket.vue
+++ b/components/realtime/websocket.vue
@@ -19,9 +19,7 @@
             <button :disabled="!urlValid" id="connect" name="connect" @click="toggleConnection">
               {{ !connectionState ? $t("connect") : $t("disconnect") }}
               <span>
-                <i class="material-icons">
-                  {{ !connectionState ? "sync" : "sync_disabled" }}
-                </i>
+                <i class="material-icons">{{ !connectionState ? "sync" : "sync_disabled" }}</i>
               </span>
             </button>
           </li>
@@ -103,7 +101,19 @@ export default {
         },
       ]
       try {
-        this.socket = new WebSocket(this.url)
+        if (this.$store.state.postwoman.settings.PROXY_ENABLED) {
+          const original = new URL(this.url);
+          const proxy = new URL("your_proxy_server");
+          let proto = original.protocol;
+          proxy.searchParams.append("scheme", proto.substr(0, proto.length-1));
+          proxy.searchParams.append("target", original.hostname);
+          proxy.searchParams.append("port", original.port);
+          proxy.searchParams.append("path", original.pathname);
+          proxy.searchParams.append("query", original.searchParams.toString());
+          this.socket = new WebSocket(proxy);
+        }
+        else
+          this.socket = new WebSocket(this.url)
         this.socket.onopen = event => {
           this.connectionState = true
           this.communication.log = [
```

still trying to adopt the original version of http proxy server so we could use a single proxy for both types of requests

**Comment by frankli0324** [comment]
demo： https://proxy.frankli.site

**Comment by fzyzcjy** [comment]
Any progress? When developing it is very common to deploy on `localhost` with HTTP not HTTPS. Thus this feature is very desired and will be commonly used.

Thanks!

p.s. @franeli0324's site seems to be down.

**Comment by liyasthomas** [comment]
For localhost endpoints, you should install Browser Extension (link in readme). For other non-https endpoints turn-on Proxy from Settings> Proxy.

*The latest Chrome extension is having a minor bug which has been fixed but is currently under review. Kindly use another browser (Firefox) local endpoints.

**Comment by fzyzcjy** [comment]
Thanks! I just searched the plugin but find it 404, so I will turn to firefox or wait

**Comment by liyasthomas** [comment]
Buggy version has been taken down - use Firefox / Proxy mode.

**Comment by fzyzcjy** [comment]
OK thanks!

By the way I find another solution: Disable Chrome's security check for this particular webpage in chrome's setting.

**Comment by idling-mind** [comment]
I'm trying to access an internal http host. Couldnt get it working in anyway. Any suggestions?

**Comment by liyasthomas** [comment]
@idling-mind turn on Proxy Mode from [Settings](https://hoppscotch.io/settings).
