### ISSUE TITLE
Allow User to Choose Whether to Include Authentication in Permalink

### ISSUE THREAD

**Issue by biodrone** [liyasthomas/postwoman#178]
**Is your feature request related to a problem? Please describe.**
When sharing permalinks with others, it would be useful to have the option to not include API credentials in case users have different accounts. 

**Describe the solution you'd like**
A toggle somewhere near the Permalink button which allows the user to enable/disable including credentials.

**Describe alternatives you've considered**
The user could manually remove the credentials but this would take a lot of extra time. 

**Additional context**

**Comment by liyasthomas** [comment]
Toggle component is already used before. Please make use of that.

**Comment by liyasthomas** [comment]
@biodrone thought I should ping you to know the update on this issue.
