### ISSUE TITLE
POST request json bodies aren't sent

### ISSUE THREAD

**Issue by AndrewBastin** [liyasthomas/postwoman#180]
**Describe the bug**
The POST request body (from the built-in JSON editor) does not seem to reach the recipient.

**To Reproduce**
1. Create a test server (like [this](https://gist.github.com/AndrewBastin/a8806d4378f0aa8c51ccb3b2f846ef30) in express)
2. Send a request to the server in postwoman with some JSON
3. We get '{}' as the POST body printed on the server side

**Expected behavior**
Well, the server should display the correct body

**Comment by liyasthomas** [comment]
Can you submit a screenshot of console?

**Comment by AndrewBastin** [comment]
![The image](https://i.imgur.com/3NmRy4b.jpg)

**Comment by liyasthomas** [comment]
chuckle i'm in danger

**Comment by SimplyComplexable** [comment]
@liyasthomas I can take a look into this.

**Comment by AndrewBastin** [comment]
@SimplyComplexable feel free to do so 😊

**Comment by AndrewBastin** [comment]
Oops, sorry, it was a thing with body-parser and Content-Type definitions :sweat: 

Closing the issue, sorry guys :sweat_smile:
