### ISSUE TITLE
PWA not installable

### ISSUE THREAD

**Issue by NileshSP** [liyasthomas/postwoman#19]
**Describe the bug**
"Install PWA" button doesn't work 

**To Reproduce**
2. Click on 'Install PWA' button
4. Effect - Not installed

**Expected behavior**
Doesn't provide "Install App?" dialog to proceed

**Screenshots**
Lighthouse suggestions through 'Audit' tab in devtools for troubleshooting
![image](https://user-images.githubusercontent.com/13110493/63553172-a67a8100-c507-11e9-9456-694b581b087c.png)

**Additional context for resolution**
Try updating the "start_url" in manifest.json to 
"start_url": "https://liyasthomas.github.io/postwoman" or "." instead

**Comment by liyasthomas** [comment]
#22 fixed this.
Tested and approved.
