### ISSUE TITLE
Import and export environments from JSON

### ISSUE THREAD

**Issue by terranblake** [liyasthomas/postwoman#190]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I would like the ability to import/export an environment, with a specified environment name (at time of upload), to enable the ability to share environments.

**Describe alternatives you've considered**
N/A

**Additional context**
This issue was originally outlined in #147 as a part of the environment feature, but was moved as this is a feature that can be built after the first, but isn't *required* to have an mvp for environment configurations.

**Comment by terranblake** [comment]
Creating this to minimize scope for #147. Will require this issue to be resolve in some way for this issue to be started

**Comment by liyasthomas** [comment]
#591 resolves this, hence closing.
