### ISSUE TITLE
Chain requests. Execute a bunch of requests one by one and produce results

### ISSUE THREAD

**Issue by liyasthomas** [liyasthomas/postwoman#196]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
1. Under request section an "add new request" button.

2. This will create another request section with defaults or inherits last request's setup.

3. "Send" button on each request section as well as there's a "send all" button.

4. Sending requests will executes requests top to botton (0 to n)

5. Results will be a table of all results

**Describe alternatives you've considered**
Sending each requests one by one.

**Additional context**
An option to display results next to corresponding request will be awesome.

**Comment by anthonkendel** [comment]
Hey, 😄 I would be interested in helping out. Is this anything that you looked into @liyasthomas ?

I checked out the source code but it seems like the current implementation only keeps track of one request at a time. Correct me if I am wrong.

**Comment by liyasthomas** [comment]
@anthonkendel currently one one request can be sent at a time. This feature is a very helpful o e and it would be great if you could help us pull this off!

**Comment by NBTX** [comment]
I'd like to propose extending #139 to include this.
We could make some sort of 'timeline' or 'step by step' view, where requests can be executed one by one and optionally some script could be inserted between requests to set data for the next request.

**Comment by NBTX** [comment]
Please refer to #218.
