### ISSUE TITLE
All changes in input fields lost when you switch to another page

### ISSUE THREAD

**Issue by hosseinnedaee** [liyasthomas/postwoman#203]
**Describe the bug**
Any inserted data or change that you made in Method, URL and .. will be lost  when you switch to another page

**To Reproduce**
1. Change URL input value to something like `https://jsonplaceholder.typicode.com`
2. Go to another page, for example, Click on 'Settings' (gear icon on the top-right corner)
3. Go back to the HTTP page again
4. see the URL input, it's value turn back to default `https://reqres.in`

This happens for all other changes 

**Expected behavior**
When we go to another page the changes should remain

**Comment by liyasthomas** [comment]
Yeah this bugs me out too.
A save as you type (to localStorage) feature might fix this.

**Comment by breno-pereira** [comment]
Can I get this one?

**Comment by liyasthomas** [comment]
@breno-pereira yeah sure! every contribution helps 🙂
Assigning this to you!

**Comment by ianfabs** [comment]
@breno-pereira Need any help on this fix?

**Comment by liyasthomas** [comment]
He could use some help!🙌🏼

**Comment by peoray** [comment]
What's the status of this?

**Comment by breno-pereira** [comment]
It's almost done
