### ISSUE TITLE
Display sendRequest runtime errors in the console

### ISSUE THREAD

**Issue by nickpalenchar** [liyasthomas/postwoman#206]
Currently only a specific type of error caught in sendRequest is displayed. All others are swallowed, but the message displayed to the users instructs to check the console for errors. Let's show those errors appropriately so that the resolve makes sense.

**Comment by liyasthomas** [comment]
Thats better! Perhaps show a toast? Than console.log().

```this.$toast.error(error + error.code, {
 icon: 'error'
});```

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status

**Comment by nickpalenchar** [comment]
Toast would be good. Looking at a why-not-have both approach. Toast would display the error message but having the full error in the console is also good to easily refer to, as well as getting more verbose details like the error stack (this is being implemented as a console.error rather than console log)

**Comment by liyasthomas** [comment]
Yeah! That's correct. Just saw the branch. Make the PR. Will merge right away!
