### ISSUE TITLE
Store the time spent on fetching a response

### ISSUE THREAD

**Issue by pavi2410** [liyasthomas/postwoman#225]
**Is your feature request related to a problem? Please describe.**
It would be cool and productive to know how much time does it take to fetch a response while testing.

**Describe the solution you'd like**
Display the time difference from the start of making a request to the end of geting the response. The unit should be in milliseconds (ms)

**Comment by liyasthomas** [comment]
TTimeine required to finish current request is already visible in the toast
![Screenshot_20191027-140936](https://user-images.githubusercontent.com/10395817/67632001-a1e59680-f8c3-11e9-93c2-69d3a630751b.png)

**Comment by pavi2410** [comment]
Oh! I am sorry that I overlooked its presence! Thanks :)

**Comment by pavi2410** [comment]
Can you (or I) please make the snackbar bigger and visible for a longer time?

**Comment by NBTX** [comment]
I'll add a setting for it - though perhaps we should store the request duration for the log and as it could be quite useful.

**Comment by liyasthomas** [comment]
Solved in https://github.com/liyasthomas/postwoman/commit/f71b940197fc2cc251cabd3798df9523971ccd68
