### ISSUE TITLE
Credentials are still being included in Permalink even when "Include in URL" is turned off

### ISSUE THREAD

**Issue by reefqi037** [liyasthomas/postwoman#227]
**Describe the bug**
```Include in URL``` toggle only include/exclude ```auth``` parameter.

**To Reproduce**
1. Set ```Authentication Type``` to ```Basic``` or ```Bearer Token```
2. Set the ```Username``` and ```Password``` or ```Token```
3. Toggle ```Include in URL``` button on and off
4. See the ```httpUser``` and ```httpPassword``` or ```bearerToken``` left in URL

**Expected behavior**
```Include in URL``` toggle button should include/exclude not only ```auth```, but ```httpUser```, ```httpPassword``` and ```bearerToken``` too.

**Screenshots**
![auth](https://user-images.githubusercontent.com/44827833/67746310-9207b700-fa69-11e9-9b3a-754170488277.PNG)

**Additional context**
Related with #178 and #215

**Comment by NBTX** [comment]
Ah! I know the cause, I'll submit a PR as soon as I get home.

**Comment by reefqi037** [comment]
Yeah, thought you will figured it out since you wrote that part. I have submit a PR too but feel free to make another. I'm new to vue and still learning  😬

**Comment by NBTX** [comment]
Nope your PR works fine!
