### ISSUE TITLE
Unsupported URLs [BUG]?

### ISSUE THREAD

**Issue by seyuf** [liyasthomas/postwoman#229]
The send button is deactivated when url is:
[https:user:password-@api.domain.fr](https:user:password-@api.domain.fr)
when  password is ending with special character (i.e " *-* "), the url is considered invalid, one can't make a request.

Everything is working fine when entering:
[https:user:password@api.domain.fr](https:user:password@api.domain.fr)
or
[https:user:password-pwd@api.domain.fr](https:user:password-pwd@api.domain.fr)

**Error when *-* at the end of password**
![error-when-url](https://user-images.githubusercontent.com/3765910/67789939-23305b00-fa75-11e9-97ad-f74babaf0b95.png)

The send button should be active e.g 
![no-error-when-url](https://user-images.githubusercontent.com/3765910/67789991-3c390c00-fa75-11e9-9345-ea99ee6c4770.png)

**Comment by liyasthomas** [comment]
I couldn't reproduce the bug. By the way, I don't think the `URL` you mentioned seems to a valid url at all.

**Comment by reefqi037** [comment]
I think @seyuf meant to send username and password together with the URL in this form:
```http://username:password@example.com```

If there's ```-``` at the end of the ```password```, for example ```http://username:password-@example.com```, Postwoman will consider the URL invalid, thus disabling the ```send``` button.

You can achieve the same thing by using ```Basic Type Authentication``` function. Type 
in username and password in the field and just use ```http://example.com``` in the URL instead.

**Comment by seyuf** [comment]
Hi @liyasthomas , what @reefqi037 said, let me know if you need more info?

Hi @reefqi037, thanks for the workaround.

I still think this is an issue tough,  feel free to close this if you think otherwise.

Great project by the way, many thanks 👍
