### ISSUE TITLE
Lacking documentation and wiki

### ISSUE THREAD

**Issue by liyasthomas** [liyasthomas/postwoman#232]
**Is your feature request related to a problem? Please describe.**
Accept the fact that postwoman.io have zero docs and wiki 😞 

**Describe the solution you'd like**
Make the wiki, write the docs: https://github.com/liyasthomas/postwoman/wiki

**Describe alternatives you've considered**
Host docs on postwoman.io itself.

**Additional context**
Wiki is essential while adding new features, making any changes breaking changes, updating format/features etc.

**Comment by nickpalenchar** [comment]
I was just thinking about this. Don't want to add complexity too quickly, but [gitbooks](https://www.npmjs.com/package/gitbook) seem to produce great documentation. I need to do some research but I believe they can be hosted from a `docs/` directory in github, and would be a part of VCS along the rest of the codebase (not to mention documentation edits would be a green square for a contributors github profile 😎 )

Of course just starting to write anything in the github wiki is easy for every/anyone to do, and could easily be moved over to gitbook later as it's all markdown

**Comment by NBTX** [comment]
You can use GitHub pages and that will work from a specific branch or a docs/ directory. But to add, another perk of GitHub pages would be that we could theme it as we please.

I definitely think we should use the GitHub Wiki as a draft for the docs.

**Comment by liyasthomas** [comment]
Will wirte Github Wiki first.

GitBook for build ✔️
GitHub pages for hosting ✔️

**Comment by yubathom** [comment]
This would be nice!

Maybe a vue based doc builder should be considered. I use vuepress for documentation and I think it is awesome. A helpful feature is the capability of it to [load vue components in docs markdown](https://vuepress.vuejs.org/guide/using-vue.html#using-components). But agree that wiki is certainly a good start.

**Comment by liyasthomas** [comment]
How about we add a help **[?]** button on sections with link to its corresponding wiki pages as I finish docs.

**Comment by sabatesduran** [comment]
Have you tried Netlify? Now with every commit you can build multiple sites :smile:
