### ISSUE TITLE
Extend syntax highlighting with ACE for pre-request script textarea

### ISSUE THREAD

**Issue by nickpalenchar** [liyasthomas/postwoman#235]
Related to #218 

**Is your feature request related to a problem? Please describe.**
No syntax highlighting might confuse users in pre-request scritps. It could look like they're writing in plaintext, and common typos won't be as apparent.

**Describe the solution you'd like**
Simple syntax highlighting. Things like basic javascript types should be highlighted. Nothing too fancy needed.

**Describe alternatives you've considered**
Going without, but syntax highlighting looks more l33t.

**Additional context**
@sblasa has done some research on this after reaching out on #91

**Comment by nickpalenchar** [comment]
@sblasa are you still interested in taking this?

**Comment by liyasthomas** [comment]
HighlightJS is already implemented in the PW.
Introduced in #142 
https://highlightjs.org/

**Comment by sblasa** [comment]
> @sblasa are you still interested in taking this?

@liyasthomas and @nickpalenchar  yes, I'm still interested in this.  So, I'm using hiighlight.js instead, since highlight is already there; therefore use that. to extend  syntax highlighting for pre-request script.

**Comment by liyasthomas** [comment]
@sblasa thought I should ping you to get the latest updates on this issue...! If you need any help, ping me.

**Comment by sblasa** [comment]
@liyasthomas Hi! I pull down the latest changes--and running on my local. I'll ping you shortly for some help. Thanks!

**Comment by sblasa** [comment]
@liyasthomas Hi, noticed that the reference for highlight.js will be removed from pages/index.vue with Replace highlight.js with ace editor #292  . So we probably won't use highlight.js to create the feature since it has been removed? Use Ace Editor instead? Thanks!

**Comment by liyasthomas** [comment]
@sblasa sorry for the delayed response!
HighlightJS is being replaced with ace. Its implementation is much simpler and have out of the box support for textarea. Please use ace for pre-request scripts.

**Comment by sblasa** [comment]
@liyasthomas Okay, thanks for confirming. 👍

**Comment by liyasthomas** [comment]
@sblasa ace is in production (master branch) now! Refer the code snippets from there.

**Comment by AndrewBastin** [comment]
Yeah, I tried implementing two-way binding (v-model) onto the Ace Editor component ([components/ace-editor.vue](https://github.com/liyasthomas/postwoman/blob/master/components/ace-editor.vue)) but it had some issues with the re-render (cursor keeps staying in the first col of first line), so I dropped it...

Can somebody go into fixing that ? Or can we move Ace Editor stuff to a library (like a Ace Editor wrapper for Vue)

**Comment by liyasthomas** [comment]
I think v-model doesn't work on Ace. I too tried and failed doing it.

**Comment by AndrewBastin** [comment]
Can we look into libraries providing Vue wrappers from Ace ?

**Comment by liyasthomas** [comment]
@AndrewBastin https://stackoverflow.com/questions/57645961/vue-apply-v-model-on-user-defined-component-which-use-ace-editor there's a sollution.

**Comment by AndrewBastin** [comment]
Ooooh, if nobody is working on it, I will try implementing it and migrate the necessary views.

If nobody is working on it, can I get an assign ?
