### ISSUE TITLE
[UI] [UX] Allow app to take width of browser

### ISSUE THREAD

**Issue by sheecegardezi** [liyasthomas/postwoman#236]
**Is your feature request related to a problem? Please describe.**

I want to see the complete strings for Path and URL under the Response section. Even if I increase the size of the browser the app keeps a fixed width.

**Describe the solution you'd like**

In file default.vue 
.......
  header,
  #main,
  footer {
    margin: 0 auto;
    max-width: 1200px;
  }
.....
I want an option to unset max-width property.

**Alternative solutions or features you've considered.**
Commented out this property

**Comment by liyasthomas** [comment]
Yeah! That's okay to consider. Anyway I'm redesigning the whole UI with a 3 column design.

[History & Collections] on left
[Request, Auth, Headers, Params] on middle
Sticky [Response] on right

**Comment by sheecegardezi** [comment]
Can I be assigned to implement this feature?

**Comment by liyasthomas** [comment]
I will ping you @sheecegardezi after deploying the initial UI update today itself. Only proceed after that.

**Comment by liyasthomas** [comment]
@sheecegardezi Initial update is deployed to production. Now we can work on it! For more communications, join our public Telegram group: https://t.me/postwoman_app or Discord Server: https://discord.gg/GAMWxmR

**Comment by AtomicNicos** [comment]
UI is scrunched and overlaps on mobile devices (Android).

Steps to reproduce :
- Get a phone
- Load up postwoman.web.app on a browser
- Scroll

![photo_2019-11-01_14-12-09](https://user-images.githubusercontent.com/18284503/68027186-fb7a0680-fcb1-11e9-8b9c-bba184cbd1b4.jpg)
![photo_2019-11-01_14-12-23](https://user-images.githubusercontent.com/18284503/68027187-fb7a0680-fcb1-11e9-9571-fb08d9e6dddd.jpg)

**Comment by liyasthomas** [comment]
Will look into it ASAP

**Comment by liyasthomas** [comment]
@AtomicNicos do a hard refresh and check whether the issue persist.

**Comment by liyasthomas** [comment]
@sheecegardezi any suggestions for the UI?

**Comment by NBTX** [comment]
@liyasthomas for the nav bar - perhaps some more padding at the top and a massive z-index so the other elements don't go on to of it.

Otherwise, it's just a case of looking through on mobile and seeing which components need refining I guess.

**Comment by liyasthomas** [comment]
I can't reproduce any bugs on my mobile 😕
Everything seems to be perfect here!

**Comment by sheecegardezi** [comment]
I will test it out today and update.

**Comment by sheecegardezi** [comment]
- App does take the width of browsers in desktop 
- For me postwoman.web.app did not load on Chrome iPhone 6s, I mimicked the change in behaviors  on the desktop by rooming-in:
<img width="531" alt="postwoman-ui" src="https://user-images.githubusercontent.com/7543039/68085817-122e8200-fe99-11e9-8c1f-ec95ce427a92.png">
- The boxed icons break into rows as zoom was increased, One solution could be collapsing the boxed icons in "3 vertical dots" drop-down-menu

**Comment by liyasthomas** [comment]
Thanks for the quick response! Will look into it ASAP.

**Comment by liyasthomas** [comment]
@all-contributors please add @liyasthomas for code

**Comment by liyasthomas** [comment]
@all-contributors please add @NBTX for code

**Comment by liyasthomas** [comment]
@all-contributors please add @larouxn for code

**Comment by liyasthomas** [comment]
@all-contributors please add @yubathom @nickpalenchar @terranblake @AndrewBastin @vlad0337187 @izerozlu @JacobAnavisca @nityanandagohain @hosseinnedaee for code

**Comment by liyasthomas** [comment]
@all-contributors please add @nickpalenchar for code

**Comment by liyasthomas** [comment]
@all-contributors please add @terranblake for code

**Comment by liyasthomas** [comment]
@all-contributors please add @AndrewBastin for code

**Comment by liyasthomas** [comment]
@all-contributors please add @vlad0337187 for code

**Comment by liyasthomas** [comment]
@all-contributors please add @izerozlu for code

**Comment by liyasthomas** [comment]
@all-contributors please add @JacobAnavisca for code

**Comment by liyasthomas** [comment]
@all-contributors please add @nityanandagohain for code

**Comment by liyasthomas** [comment]
@all-contributors please add @hosseinnedaee for code

**Comment by liyasthomas** [comment]
@all-contributors please add @liyasthomas for design
