### ISSUE TITLE
Section labels don't display properly in Firefox

### ISSUE THREAD

**Issue by NBTX** [liyasthomas/postwoman#237]
**Describe the bug**
The `<legend>` elements used as category headers (styled with `flex`) don't seem to render properly in Firefox. (Tested on version 70.)

**To Reproduce**
1. Open postwoman on Firefox

**Screenshots**
<img width="1494" alt="image" src="https://user-images.githubusercontent.com/43181178/67950977-91466080-fbe2-11e9-839d-f493f5d5cce3.png">

**Comment by liyasthomas** [comment]
Ohh! Will look into it asap
