### ISSUE TITLE
Add DB cache

### ISSUE THREAD

**Issue by steviebeenz** [liyasthomas/postwoman#26]
Add Firebase DB for storage of requests, and cache with Auth to access this log. Have workspace tabs, too maybe?

**Comment by liyasthomas** [comment]
That sounds like a splendid idea :100:

**Comment by brandonros** [comment]
Couple this with UI to manage {{templateParameters}} and create environments/presets so you can toggle dropdowns for what environment you want to hit (dev/QA/CAT/UAT/prod), just like in Postman. :)

**Comment by liyasthomas** [comment]
Refer: https://github.com/davidroyer/nuxt-firebase-auth
