### ISSUE TITLE
[BUG] [UI] [Mobile] Get results not scrollable.

### ISSUE THREAD

**Issue by AtomicNicos** [liyasthomas/postwoman#266]
**Describe the bug**
When GETting a larger quantity of data, the _Results_ area does not allow scrolling (the page gets scrolled instead).

**To Reproduce**
1. On Mobile, go to PW
2. Make a GET request, where the received data exceeds the number of lines in the text area (tried with 2749, because I like breaking things).
3. Scroll down to the _Results_ area
4. Try scrolling the Text Area.

**Expected behavior**
Scroll should be deferred to Text Area instead of page.

**Screenshots**
![photo_2019-11-05_10-55-34](https://user-images.githubusercontent.com/18284503/68197685-ee635d00-ffba-11e9-95b3-1915939c9816.jpg)

**Smartphone (please complete the following information):**
 - Device: Xiaomi Redmi Note 7
 - OS: Android 9.*something*
 - Browser stock, Chrome, Firefox Focus, Opera
 - Version *latest*

**Comment by hosseinnedaee** [comment]
I checked it on the same device and it works fine (Chrome & Opera).

**Comment by liyasthomas** [comment]
Normal responses with LOC < 100 works fine.
Huge payload breaks HighlightJS render. Issue will persist until syntax highlighting is migrated to ace.

**Comment by hosseinnedaee** [comment]
I will work on it.

**Comment by liyasthomas** [comment]
Currently, response is syntax highlighted in <pre><code> tags for highlightJS implementation. Remove hljs and implement alternative (such as ace) that supports textarea highlighting

**Comment by hosseinnedaee** [comment]
> Currently, response is syntax highlighted in `<pre><code>` tags for highlightJS implementation. Remove hljs and implement alternative (such as ace) that supports textarea highlighting

Okay

**Comment by AtomicNicos** [comment]
Yup, This was fixed !
