### ISSUE TITLE
Code generation for Fetch request type of some methods (POST, PUT, PATCH) won't be shown

### ISSUE THREAD

**Issue by reefqi037** [liyasthomas/postwoman#268]
**Describe the bug**
When you try to generate fetch request type code for POST or PUT or PATCH method, the code won't be generated and TypeError log can be seen in the console log. Once the error happened, you won't be able to generate code for other methods too.

**To Reproduce**
1. Set ```Request Method``` to ```POST```
2. Click on ```Show Code``` button
3. Select ```Fetch``` from  the ```Request Type``` dropdowns
4. See error in console log

**Expected behavior**
Code is generated and shown in the ```Generated Code``` section

**Screenshots**
![TypeError](https://user-images.githubusercontent.com/44827833/68260687-10bfae00-0081-11ea-8663-395874f61d78.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Browser: Chrome
 - Version: 78.0.3904.87 (Official Build) (64-bit)

**Comment by liyasthomas** [comment]
Wow! That's a critical bug.. not sure how this happened. Will investigate it ASAP. Thanks for pointing it out.

**Comment by reefqi037** [comment]
Yeah I've realized it from last week. Just haven't got time to verify and post it.

**Comment by liyasthomas** [comment]
Any idea what went wrong?

**Comment by reefqi037** [comment]
Sorry haven't look into the details yet.

**Comment by liyasthomas** [comment]
Okay

**Comment by liyasthomas** [comment]
https://github.com/liyasthomas/postwoman/commit/d290b25f8a0ed65b021b4686315c55614dd77584 solves this. Please verify bug fix. Actually this might break some users who already faced this issue causing the store to save the wrong state into vuex.
For them, clearing cookies will fix the issue. Please let me know if there's any trouble.

**Comment by reefqi037** [comment]
Nope. I've cleared site data and perform hard reset but the issue still persist.

**Comment by liyasthomas** [comment]
Yeah! Working on it.

**Comment by liyasthomas** [comment]
5e424bb64d3af2dc15a050171438af57b6fbe24e mind giving a try once more to check if the issue persist?

**Comment by reefqi037** [comment]
Yup. This should fix the issue. Wondered if it's okay to remove the ```$this.store.commit``` part.

**Comment by liyasthomas** [comment]
Good.
Committing request Code to vuex was a foolish thing to do.
