### ISSUE TITLE
[feature]:  Add hindi language locale

### ISSUE THREAD

**Issue by Dhravya** [liyasthomas/postwoman#2733]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

There is no hindi language (`hi`) language support in https://github.com/hoppscotch/hoppscotch/tree/main/packages/hoppscotch-app/locales

### Why should this be worked on?

It would be good to support more international languages. Hindi is one of the biggest languages spoken in India.

I would love to take on this issue!

**Comment by liyasthomas** [comment]
Appreciate your interest in contributing to Hoppscotch project ❤️

Kindly open a PR for your desired translation language, and we'll consider adding it to the locales.

Since this isn't a critical feature, I'm closing this issue.
