### ISSUE TITLE
[request] localhost support

### ISSUE THREAD

**Issue by jitendra3109** [liyasthomas/postwoman#274]
**Describe the bug**
I was trying to check on my local machine process API call
 
**To Reproduce**
Check on localhost api call

**Expected behavior**
It should work as in post**man**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [MAC]
 - Browser [chrome]

**Additional context**
'http://0.0.0.0:3001/v1/path'. This request has been blocked; the content must be served over HTTPS.

**Comment by liyasthomas** [comment]
For non-https (`http`) endpoints: make use of Proxy mode.
**Settings > Turn on Proxy**

Regarding API on local server:
**We're investigating what went wrong. Will update you ASAP.**

**Comment by NBTX** [comment]
The proxy won't work for requests to localhost. You  need to self-host the proxy or turn it off and use a self-signed certificate.

**Comment by liyasthomas** [comment]
closing in favor of #267
