### ISSUE TITLE
Allow url request with `/` at eol

### ISSUE THREAD

**Issue by genk1** [liyasthomas/postwoman#275]
**Is your feature request related to a problem? Please describe.**
When we request api URL with `slush - /` at the end, it returns Error
``` Error in event handler: TypeError: Failed to construct 'URL': Invalid URL ```

**Describe the solution you'd like**
It can work both with or without `slush - /` at the end of API URL.

**Describe alternatives you've considered**
Shows us error in view, like immediate validation error on that URL fields not only in web Inspector,

**Additional context**
NA

**Comment by liyasthomas** [comment]
Thanks

**Comment by liyasthomas** [comment]
Closed by accident. Sorry.

Regarding "/" at rhe end:
We have seperate fields for `URL` and `Path`. The "/" part usually goes with the `Path` field. Anyway this is still an issue. We have a PR (WIP) redy to be deployed #189 . When it lands, this issue will be solved. 

Thanks for bring this issue upfront. We'll investigate the quickest solution for this, meanwhile use slash on Path field or if theres no Path field, simple remove the "/"
