### ISSUE TITLE
Improve UI Contrast

### ISSUE THREAD

**Issue by tomjn** [liyasthomas/postwoman#277]
**Describe the bug**

Currently the interface has very low contrast on form inputs, this needs to be increased

**To Reproduce**
1. Open the interface
2. Squint

**Expected behavior**

Clear form inputs that don't require non-corrective vision, and comply with WCAG

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Firefox
 - Version 70

**Additional context**

This affects all colour schemes in the settings area, either borders or greater background contrast will improve the UI significantly

**Comment by liyasthomas** [comment]
We seriously think, we need to update the color schemes. Me being not much of a great frontend developer, I seek help on choosing color schemes that comply with WCAG. Anyway, next commit will include more web safe colors.

**Comment by tomjn** [comment]
I think a thin but darker border around the inputs might do the job, here's a quick `border: 1px solid var(--fg-color);` on all `input` elements:

<img width="486" alt="Screenshot 2019-11-07 at 02 02 15" src="https://user-images.githubusercontent.com/58855/68353850-abac9c80-0102-11ea-98ee-208c4334824a.png">

**Comment by liyasthomas** [comment]
Thanks for the quick suggestion. Will update 🎉👍

**Comment by tomjn** [comment]
Thanks for the ultra fast reply :)
