### ISSUE TITLE
Download the request result into a file.

### ISSUE THREAD

**Issue by Daniellunsc** [liyasthomas/postwoman#278]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I would like to download in a JSON file the response of the request.

**Describe alternatives you've considered**
I considered adding another button on the side of 'COPY' on response, to just download the request in a JSON file.

**Additional context**

**Comment by liyasthomas** [comment]
Thats doable. Considering its complexity, we colud ship ship this feature today itself 👍

**Comment by Daniellunsc** [comment]
I would like to do it. Can I?
In fact, I've already done it. Just need some finish.

**Comment by liyasthomas** [comment]
Yeah sure! I was going to open my PC. You're free to send a PR ♥️

**Comment by Daniellunsc** [comment]
Thanks! I used as base the copy function. Preparing the PR!

**Comment by Daniellunsc** [comment]
Here we go @liyasthomas 
https://github.com/liyasthomas/postwoman/pull/280
