### ISSUE TITLE
Unable to edit or delete row in history table

### ISSUE THREAD

**Issue by TuraMarco** [liyasthomas/postwoman#281]
Unable to click `edit_button#n` or `use_button#n` on history table

chrome  78.0.3904.87

**Comment by liyasthomas** [comment]
The very first entry on history section seems to have this issue. If you send a second request, it seems to be fixed as well. That's a tricky bug bu the way. While we're investigating what cause this, I suggest you to send a one more dummy request and try to use the inaccessible buttons.
