### ISSUE TITLE
Mobile can't see console for request errors

### ISSUE THREAD

**Issue by WalshyDev** [liyasthomas/postwoman#283]
**Describe the bug**
I did a POST request and got a "Network Error" status, the response body said `See JavaScript console (F12) for details.`. This isn't possible on mobile. It would be nice to send that error right to the body text area instead. 

**To Reproduce**
1. Create request for invalid URL (Such as https://fail.walshy.dev)
2. Send
3. See the response body say to check console

**Expected behavior**
The error is printed to the response body so that mobile users can see what went wrong. 

**Screenshots**
![6565B2ED-4A61-47BF-BB07-0A8878A027C5](https://user-images.githubusercontent.com/8492901/68402352-1b5a7000-0173-11ea-95d7-dcc15c58dca4.png)

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: iOS
 - Browser: Safari
 - Version: 12? (iOS 12.1.2)

**Additional context**
N/A

**Comment by liyasthomas** [comment]
Ohh! That prompt was a generic one made for letting the users know some error from either server or API side has been occurred.
Originally it was intended for desktop, but anyway thanks for bringing this up. It somehow reduce user experience. Will update with a more accurate prompt on such cases

**Comment by NBTX** [comment]
9 times out of 10 it's not possible to get the details of the error on the website because if it's to do with a request failure, the browser has strict requirements on what errors and what properties of those errors can be viewed.

As there is no developer tools on mobile, I resorted to simply displaying a generic error message.
