### ISSUE TITLE
Focus Styles on Buttons

### ISSUE THREAD

**Issue by tomjn** [liyasthomas/postwoman#284]
**Describe the bug**

Focus styles on buttons could be improved, I tabbed on to this button from the URL on the API request builder, not  sure where I am if I press  tab again:

<img width="670" alt="Screenshot 2019-11-07 at 16 35 20" src="https://user-images.githubusercontent.com/58855/68408086-a2601600-017c-11ea-9f85-99d62db63e9b.png">

Similar on the main page, assuming the same style is responsible:

<img width="281" alt="Screenshot 2019-11-07 at 16 36 45" src="https://user-images.githubusercontent.com/58855/68408195-d63b3b80-017c-11ea-9753-7837d77d726e.png">

**Desktop (please complete the following information):**
 - OS: MacOS Catlina
 - Browser Firefox
 - Version 70

**Comment by liyasthomas** [comment]
Fix is on the way!

**Comment by liyasthomas** [comment]
Solved on https://github.com/liyasthomas/postwoman/commit/7a60cc25e9f0086d4e95e883a0f87ef087a5c13a
