### ISSUE TITLE
Hover Styling on Inputs

### ISSUE THREAD

**Issue by tomjn** [liyasthomas/postwoman#285]
**Describe the bug**

Buttons, dropdowns and textboxes don't have hover styling, this would make the UI feel a lot snappier/nicer/responsive

**Desktop (please complete the following information):**
 - OS: MacOS Catlina
 - Browser Firefox
 - Version 70

**Comment by liyasthomas** [comment]
Thanks for all your suggestions! Next commit is a fix⚡

**Comment by tomjn** [comment]
The tabs could do with hover styles too

**Comment by liyasthomas** [comment]
Solved on https://github.com/liyasthomas/postwoman/commit/7a60cc25e9f0086d4e95e883a0f87ef087a5c13a
