### ISSUE TITLE
Change cursor to disabled on disabled inputs

### ISSUE THREAD

**Issue by tomjn** [liyasthomas/postwoman#286]
**Describe the bug**

Hovering over a read only/disabled input gives a standard mouse cursor, but it looks like a clickable input.

Instead, using `cursor: not-allowed;` should change the cursor making it clear this input can't be accessed

**Desktop (please complete the following information):**
 - OS: MacOS Catlina
 - Browser Firefox
 - Version 70

**Comment by liyasthomas** [comment]
Solved in https://github.com/liyasthomas/postwoman/commit/2a9adfd180da661bb5414ce9d3fa0d380ea3f0ed
