### ISSUE TITLE
It's possible to tab into read only and non-form elements

### ISSUE THREAD

**Issue by tomjn** [liyasthomas/postwoman#287]
**Describe the bug**

I added the following CSS rule:

```css
:active,:focus {
    outline: 1px solid green;
}
```

I found that I could tab into some non-interactive elements such as `div` containers, and read only inputs

<img width="509" alt="Screenshot 2019-11-07 at 16 54 35" src="https://user-images.githubusercontent.com/58855/68409745-8c078980-017f-11ea-9e4c-f50461b620ef.png">

**To Reproduce**
1. Click in the input in the history section to search
2. Start pressing tab

**Expected behavior**

It should jump past the history entries to the controls at the end

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Browser Firefox
 - Version 70

**Comment by liyasthomas** [comment]
I think this should be left as it is since the user might want to copy contents from a history entry.

**Comment by tomjn** [comment]
You can still do that, it's not that the div is selected, it's that it's active/focused, it needs fixing for non-input elements at least

**Comment by liyasthomas** [comment]
Oh! Will fix that.
