### ISSUE TITLE
Make response body area expandable

### ISSUE THREAD

**Issue by michalsisak** [liyasthomas/postwoman#294]
Hello, would be very nice to have an option to make response body taller by dragging the text area. Same functionality as already implemented in a header list.

Header list implementation:
![2019-11-11 at 13 29](https://user-images.githubusercontent.com/55797176/68587434-68965480-0487-11ea-950b-fe1fba9d23d9.png)

Currently, the response body has a small box in the right bottom corner but it doesn't do anything.
![2019-11-11 at 13 28](https://user-images.githubusercontent.com/55797176/68587354-384eb600-0487-11ea-93c8-c5f1babdf278.png)

**Comment by liyasthomas** [comment]
Response area is being updated to new aec editor (#292) with line number, custom theming and many more features and bug fixes. Expect production deployment in couple of days.

**Comment by michalsisak** [comment]
Thank you for the update. Looking forward to it.
