### ISSUE TITLE
Vue template

### ISSUE THREAD

**Issue by diego81b** [liyasthomas/postwoman#31]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Why don't move to a standard vue template using vue-cli and benefit of the base configuration ?

**Describe alternatives you've considered**
Maybe could be cool to move to v3 of vue and starting with Composition API

**Additional context**
No

**Comment by liyasthomas** [comment]
Rewriting all of Postwoman to latest vue is also a prime concern for me-but I can't afford to break any features. Will surely consider your advice :open_hands:

**Comment by AndrewBastin** [comment]
Well, I don't think it will have that big of a deal on any of the features we have right now, just that it affects the current PRs....

I think we should work on a vue-cli build, build it in a separate branch perhaps...

I am not a Vue guy (React ftw :stuck_out_tongue: ) so anyone willing to take up the task feel free to make a PR...

**Comment by diego81b** [comment]
Well. i'm pretty comfortable with vue ecosystem; my doubt is only the merge because the project scaffold of vue template will change the project folder structure.

Anyway i'll be glad to contribute even if i don't have so much time, but if you consider this issue not a priority feel free to assign to me and i'll try to work on it

best regards
Diego

**Comment by AndrewBastin** [comment]
@diego81b Let it change the project structure, that's fine, please be free to work on your PR but we should assign it to a separate branch so existing PRs can still be worked on and integrated before we merge it to master...

**Comment by liyasthomas** [comment]
Keep seperate branches for development ✌️

**Comment by NBTX** [comment]
I love Vue - perhaps I could fork the project (and anyone else interested in helping to port this to Vue) could work on the fork. Then we can just PR into the main repo when it's done?

**Comment by NBTX** [comment]
Also we should totally make a PWA from this!

**Comment by liyasthomas** [comment]
I would love to migrate to Vue. Need some helping hands. Btw, PWA support has already been implemented. But Vue integration would enhance it. No offense.

**Comment by diego81b** [comment]
@NBTX 
my intention was to use this https://github.com/chrisvfritz/vue-enterprise-boilerplate
appropriately resized for our purpose

i have this issue assigned but feel free to work on your fork add maybe add me as collaborator

**Comment by NBTX** [comment]
@liyasthomas Just noticed the PWA support -- neat!
@diego81b Okay. I'll take a look at the boilerplate. I've created the fork and sent you and @liyasthomas collaborator invites: https://github.com/NBTX/postwoman-vue

**Comment by liyasthomas** [comment]
Closing the issue since #51 solved it

**Comment by liyasthomas** [comment]
@all-contributors please add NBTX for code
