### ISSUE TITLE
Make the UI more compact

### ISSUE THREAD

**Issue by tudor07** [liyasthomas/postwoman#314]
While the UI is nice, meaning that colors/elements look good, I feel like it is badly organized. I have to do too much scrolling. I think you should make everything smaller and more compact. I'm on a 13'' Macbook. Almost half of the screen is occupied just by the Request section. On Insomnia I can see so much more without any scrolling. Please consider making the UI smaller.

**Comment by liyasthomas** [comment]
Thanks for reporting the issue. We're on it. A screenshot would've been great so that we could act fast on it.

**Comment by athul** [comment]
![Screen Shot 2019-11-19 at 9 39 49 PM](https://user-images.githubusercontent.com/40897573/69164041-42228a00-0b15-11ea-9d7a-176250f6b151.png)
ScreenShot taken on Macbook Air on Chrome Version 78.0.3904.108
![Screen Shot 2019-11-19 at 9 43 06 PM](https://user-images.githubusercontent.com/40897573/69164272-b2c9a680-0b15-11ea-913f-61216838b0d7.png)
Same Mac but on Safari
