### ISSUE TITLE
Configure BaseUrl using Environment variables

### ISSUE THREAD

**Issue by Nepoxx** [liyasthomas/postwoman#315]
**Is your feature request related to a problem? Please describe.**
Deploying Postwoman elsewhere than the root url results in multiple 404s since postwoman is not aware of where it is.

**Describe the solution you'd like**
Being able to set the root/base url would allow deploying postwoman on any subpath of a website, for instance `tools.example.com/postwoman`. This would be particularly useful for Docker deployments.

**Describe alternatives you've considered**
A `json` config file could do, which combined with `docker config` would also work, but it is a less popular approach.

**Comment by liyasthomas** [comment]
Let us discuss over this feature request.

**Comment by liyasthomas** [comment]
Do a `npm run generate` to build the project and try hosting the `/dist` directory on server.
