### ISSUE TITLE
Template selector

### ISSUE THREAD

**Issue by Beelzenef** [liyasthomas/postwoman#32]
**Is your feature request related to a problem? Please describe.**
No problem at all 😄
 
**Describe the solution you'd like**
I would we awesome to have a template selector, to choose a color palettes to display in the tool ✌️ 

**Describe alternatives you've considered**
I found these and they can be useful! [color palettes in Color Hunt](https://colorhunt.co/) 🎨 

**Additional context**
No needed, I think 👍

**Comment by liyasthomas** [comment]
This is cool! We're working on core features right now, but I would love to see this implemented.

**Comment by NBTX** [comment]
I'm working on a simplified version of this feature at the moment. I do plan to incorporate the PR #18 for an overall light/dark theme toggle too.

![image](https://user-images.githubusercontent.com/43181178/63643007-4da21880-c6c0-11e9-8a1b-bfea41f746b7.png)

![image](https://user-images.githubusercontent.com/43181178/63643022-84782e80-c6c0-11e9-8627-26572da72200.png)

**Comment by liyasthomas** [comment]
Closing issue since #55 fixed it
