### ISSUE TITLE
Set response panel to fullscreen

### ISSUE THREAD

**Issue by JJLao** [liyasthomas/postwoman#320]
Current response panel is too narrow to read long JSON data. so if you add this feature, I will so appreciate it!

**Comment by liyasthomas** [comment]
Yeah. This is a good feature. Will implement today itself.

**Comment by liyasthomas** [comment]
@JJLao You you can expand/collapse response by clicking the (↕) expand/collapse response button.

**Comment by JJLao** [comment]
> @JJLao you can now expand/collapse response by clicking the [ ↕ ] button next to "copy response" button.

thanks! that is what i want.
