### ISSUE TITLE
Auth info on WebSocket connections

### ISSUE THREAD

**Issue by jensgram** [liyasthomas/postwoman#321]
**Is your feature request related to a problem? Please describe.**
I'm not able to pass auth info on WebSocket connections.

**Describe the solution you'd like**
It would be nice to port the `Authentication` component (and possibly the `Headers` component too) from `Request` to `WebSocket`.

**Describe alternatives you've considered**
I may simply not be aware of how to use the UI. Perhaps it's already possible to pass auth info on WS connections?

**Additional context**
Current WS pane:  
<img width="284" alt="Screenshot 2019-11-21 at 09 06 43" src="https://user-images.githubusercontent.com/34647282/69318842-4e563680-0c3e-11ea-9485-18a011f3ed89.png">

`Authentication` and `Headers` components in `Request` pane:  
<img width="284" alt="Screenshot 2019-11-21 at 09 06 43" src="https://user-images.githubusercontent.com/34647282/69318812-426a7480-0c3e-11ea-95a8-b6b20ef7ea03.png">

**Comment by liyasthomas** [comment]
Currently, WebSocket doesn't have `auth` or `headers` support. Will add these ASAP. Would you like to contribute to this particular feature..?

**Comment by liyasthomas** [comment]
HTTP Authorization header problem can be addressed with the following:

```ws://username:password@example.com/service```

Then, a proper Basic Authorization HTTP header will be set with the provided `username` and `password`. If you need `Basic Authorization`, then you're all set.

If you want to use `Bearer` however, and I resorted to the following trick: I connect to the server as follows:

```ws://my_token@example.com/service```

And when connection at the server side receives `Basic Authorization` header with non-empty `username` and empty `password`, then it interprets the username as a token.

**Comment by igorrocha** [comment]
For anyone finding this issue now, it seems that the trick for passing an Authorization or Bearer header in the URL doesn't work anymore. It has been deprecated, as stated [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication#Access_using_credentials_in_the_URL). 

The easiest way to pass auth information is through a querystring parameter, which doesn't pose a security issue if you're using wss. Another workaround involves server side Authentication, and is described [here](https://devcenter.heroku.com/articles/websocket-security#authentication-authorization).

**Comment by liyasthomas** [comment]
Thanks for sharing the information 🙌🏼
