### ISSUE TITLE
[Request] Use responses for next request?

### ISSUE THREAD

**Issue by MrScripter85** [liyasthomas/postwoman#324]
Hello community,

would it be possible to define variables in a request that would be filled by a previous response? 
For example I am having a SMS sending endpoint. The returned login code should be taken and being used for the next script/request as "$smscode" for example.

Is that possible to implement? I think Insomnia has something like this already, too.

**Comment by liyasthomas** [comment]
Currently only pre request scripts and variable definitions are available. But we're working on chaining requests. Please follow its active thread: https://github.com/liyasthomas/postwoman/issues/218

Closing this issue in favour of #218
