### ISSUE TITLE
Enable running proxy as a backend for Request Capture

### ISSUE THREAD

**Issue by guilt** [liyasthomas/postwoman#325]
**Often, while writing new clients, or debugging existing API's, it is often useful to use a tool such as Charles Proxy. It allows one to save traces (request + response) and reload them again for reviewing as well.**

Would be useful if Postwoman came up with a way to act as such a proxy, and one could connect existing apps / browsers on them, and look through the requests / responses. Would also be helpful to generate user signed certificates if one wishes to debug through TLS encrypted requests as well. 

Ask:

1. A standard way to load and import traces, to begin with. Please support existing HTTP capture trace formats, such as Charles' .trace files etc.
2. Look at actually enable the proxying feature.
3. Enable support for saving traces as well, so they can be reused later across app sessions.

Alternatives:
N/A

Additional Context:
N/A

**Comment by liyasthomas** [comment]
Hi there!
Postwoman have proxy support!.It allows you to request response from restricted endpoints, hide your IPs, avoid CORS issues and other functionalities.

Proxy mode is global so it'll be also enabled for GraphQL testing too.

To turn on Proxy; Settings > Proxy

**Comment by guilt** [comment]
Okay, maybe I wasn't talking about using a proxy, but being one, so that other apps could connect to Postwoman, and we can see the requests on it, and capture them for future use

**Comment by liyasthomas** [comment]
Oh! my mistake while interpreting that. Let's discuss over it.
Do you have any use cases or existing projects that does this?

**Comment by guilt** [comment]
Yes. I routinely use app packet captures to identify request patterns, time between requests and would like to save some of them for later.

**Comment by guilt** [comment]
I was looking around for libraries, a starting point may be to look at: https://github.com/alibaba/anyproxy and see if we can integrate their code / libraries into the application!

More importantly, the point of proxying may not be to allow TCP connect / tunnel, but more about per-request capturing. So HTTP CONNECT / TCP passthru method isn't what the solution will do.

**Comment by NBTX** [comment]
What if we added the functionality to the proxy server to act as a packet capture and then pass this to the postwoman interface?

So a workflow would be:
1. setup a copy of the [Postwoman proxy server](https://github.com/NBTX/postwoman-proxy/) and enable some packet capture option.
2. connect the Postwoman app to the proxy server as usual.
3. connect to the proxy server on the intended device.
4. packets are logged in a packet capture tab in Postwoman.

**Comment by guilt** [comment]
That's a very useful start :) Would love to see this in action.

**Comment by liyasthomas** [comment]
@NBTX whats the status of this issue?

**Comment by NBTX** [comment]
For sure.

**Comment by liyasthomas** [comment]
Issues can only be transferred in between repos under same profile. Can't transfer to an organization.

**Comment by Congee** [comment]
This feature is helpful when you reverse-engineer an api. I currently use Fiddler, mitm-proxy, or Charles.

**Comment by liyasthomas** [comment]
Transferred this issue to https://github.com/postwoman-io/postwoman-proxy/issues/10
