### ISSUE TITLE
Generate API documentation

### ISSUE THREAD

**Issue by threeaccents** [liyasthomas/postwoman#326]
**Is your feature request related to a problem? Please describe.**
The only reason I always stick around with Postman is that they generate api docs based on the request in a collection. I had used Insomnia for a while but always went back to Postman for that reason. Even though the docs they generate aren't the best looking or very UX friendly as a developer it is the easiest solution to generate docs.

**Describe the solution you'd like**
Have a way to generate beautiful docs based on a collection.

**Describe alternatives you've considered**
Going back to postman

**Additional context**
Example docs generated: https://documenter.getpostman.com/view/8709579/SVzw511N?version=latest

**Comment by liyasthomas** [comment]
Will work on it. We're just started and make sire to include this awesome feature in our pipeline.

**Comment by liyasthomas** [comment]
Our Export collection feature could be used to make such a similar feature.

**Comment by threeaccents** [comment]
Awesome I haven't read the code base fully yet but once I get aquatinted to it maybe I can help out some with PRs for this feature.

**Comment by liyasthomas** [comment]
Great!
