### ISSUE TITLE
Server Sent Events

### ISSUE THREAD

**Issue by ImVexed** [liyasthomas/postwoman#329]
Are there any plans to support SSE / has there been any discussion around this previously?

**Comment by liyasthomas** [comment]
This seems to be an interesting feature. Where can I read more on implementing them? Or would you like to make a contribution to it :)

**Comment by ImVexed** [comment]
SSE is used in [EventSource](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events) And is effectively just an HTTP request that is held open with content type of `text/event-stream`. At that point it's just a uni-directional pipe that allows the server to send JSON events to a client.

**Comment by ImVexed** [comment]
Implementation wise, I think this may actually be incredibly technically easy. Just setup an EventSource on the provided URL and then any time an event occurs, map it onto the UI.

**Comment by liyasthomas** [comment]
Done deal. I'll look forward on implementing this.

**Comment by liyasthomas** [comment]
@ImVexed hi there. I made a MVP of SSE debug page. But i dont have an endpoint to test it. All server scripts I found online had CORS restrictions which why I couldn't test them in development. Can you suggest one to make sure it works?

**Comment by liyasthomas** [comment]
@ImVexed hi there! I've made a quick MVP for SSE would you like to have a look at it, perhaps test any of your endpoints on it and let me know. https://deploy-preview-330--postwoman.netlify.com/websocket

#330

**Comment by ImVexed** [comment]
Looks like it'd work! But I'm afraid I don't have any CORS compliant + HTTPS SSE servers to test against.

Maybe using https://github.com/kljensen/golang-html5-sse-example with a few extra CORS headers [here](https://github.com/kljensen/golang-html5-sse-example/blob/master/server.go#L124) and a https reverse proxy would be a good test?

**Comment by liyasthomas** [comment]
Oh! Do you know why there's not even a sample/mock serve sent events endpoints available for testing?

**Comment by ImVexed** [comment]
I'm not sure, I tried searching but it's got terrible SEO since "Server Sent Events" and "SSE" aren't very unique. Alongside that most people don't even know about them and just end up using websockets so there isn't as much of a community around it as one would think.

I'm sure there's some finance API that provides data over SSE but I have yet to find one.

**Comment by liyasthomas** [comment]
Okay. Let me know if find one. I'll also look for it. I can't push to production without running some tests.

**Comment by liyasthomas** [comment]
#330

**Comment by 174255317** [comment]
when use sse, hoppscotch print a log:
This browser doesn't seems to have Server Sent Events support.

**Comment by nagado** [comment]
I really want this feature :c
Here is how you can setup a server to connect to locally:
`docker run -p 8080:8080 jmalloc/echo-server`
and then you can GET `localhost:8080/.sse`
