### ISSUE TITLE
 Internal server environment usage requirements

### ISSUE THREAD

**Issue by FatDoge** [liyasthomas/postwoman#336]
**Is your feature request related to a problem? Please describe.**
When I deploy on an internal server，I noticed that the postwoman request ```css``` and ```icon``` from ```fonts.googleapis.com```, but the internal server can not request the resources,so the layout become confusing.

**Describe the solution you'd like**
Wish the all resources can be used offline.

**Describe alternatives you've considered**
Just copy the ```css``` and ```icon``` from network ,put them into the ```dist``` and rewrite the code where import the other internet resources.

**Additional context**
![微信图片_20191125154303.png](https://i.loli.net/2019/11/25/j9qhPnEIBXAbFNd.png)

**Comment by FatDoge** [comment]
BTW, awesome project!

**Comment by liyasthomas** [comment]
Actually this request was implemented quite ago, but I had to revert that on an critical error. Since you've mentioned this again, I'll fix it today itself.

**Comment by FatDoge** [comment]
> Actually this request was implemented quite a long ago, but I had to revert that on a critical error. Since you've mentioned this again, I'll fix it today itself.
> 
> > And btw, it would be great if you gave credits to us or or atleast do not change the links to GitHub repo :)

Of course~

**Comment by FatDoge** [comment]
If it is convenient, can you tell me where is the external network resource reference involved in packaging?
I mean the ```https://fonts.googleapis.com/css?family=Poppins:500,700|Roboto+Mono:400&display=swap``` and ```https://fonts.googleapis.com/icon?family=Material+Icons&display=swap```
🤣 :

**Comment by liyasthomas** [comment]
I went quite busy, will make them available for offline ASAP.

**Comment by FatDoge** [comment]
Thanks a lot.
👍

**Comment by NBTX** [comment]
@FatDoge I'm not sure if @liyasthomas has gotten around to making the resources offline, but for your own edification, the references to the resources are here:
https://github.com/liyasthomas/postwoman/blob/master/assets/css/fonts.scss
