### ISSUE TITLE
Ability to connect to a MQTT broker

### ISSUE THREAD

**Issue by debjeetsarkar** [liyasthomas/postwoman#342]
**Is your feature request related to a problem? Please describe.**
There is no comprehensive tooling while working with MQTT brokers.

**Describe the solution you'd like**
A simple interface to connect to an MQTT broker.
Subscribe to topics
Publish to topics

**Describe alternatives you've considered**
MQTT Lens

**Comment by liyasthomas** [comment]
Will consider implementing this 👍

**Comment by liyasthomas** [comment]
@debjeetsarkar can you provide a test MQTT server address for testing?

**Comment by debjeetsarkar** [comment]
@liyasthomas , for testing we can use the following:
server: mqtt.eclipse.org
port: 1883

**Comment by NBTX** [comment]
It is impossible to work with raw TCP sockets in the browser (this would require a standalone application - though could be implemented with the proxy), however you can use a websocket implementation in postwoman: https://postwoman.io/realtime

**Comment by debjeetsarkar** [comment]
MQTT can communicate over WebSockets and the current implementation of PW works fine to connect to a broker (Example: wss://test.mosquitto.org:8081). However, the only thing missing is the UI ability to publish/subscribe to topics. Since these actions require sending Mqtt messages itself, it will be very useful to allow doing the same via UI. 

Something similar to MQTTLens in chrome store.

**Comment by liyasthomas** [comment]
I think this could be implemented.

**Comment by NBTX** [comment]
![image](https://user-images.githubusercontent.com/43181178/69651424-ac678d00-1035-11ea-9d2a-5957795a4a17.png)
I see, I was looking at this page and pointing out that the raw TCP (1883 and 8883) could not be implemented.

If all you need is a better interface / UX for working with Mqtt, that's easy enough to implement.

**Comment by rahulnpadalkar** [comment]
I would like to contribute.

**Comment by liyasthomas** [comment]
This is an Vue example with MQTT server. We can clone this.

**Comment by rahulnpadalkar** [comment]
Yes sure!

**Comment by 95jinhong** [comment]
Hi, @liyasthomas  

I'm using Hopscotch 2025.06 and I have the desktop version installed and using it.
In the official documentation, it seems to support only ws and wss for MQTT.
Maybe it doesn't support TCP-based mqtts yet?

Cheers,
Hong
