### ISSUE TITLE
Static builds on releases

### ISSUE THREAD

**Issue by joanbono** [liyasthomas/postwoman#352]
**Is your feature request related to a problem? Please describe.**
Is there any plan to release a static build?
Since it's a node package, maybe is a good idea to release a build which can be downloaded/executed automatically, without NPM installed or need to install all the dependencies.

**Describe the solution you'd like**
Use npm's static-build to release static builds under Releases

**Comment by liyasthomas** [comment]
We've already planned quite a lot of implementations:

- Offline build #267 
- VS code plugin #313

**Comment by joanbono** [comment]
Good! In this case I think we can close this one! 

Looking forward to it :)
