### ISSUE TITLE
Bearer token doesn’t work with CORS when only authorization header is allowed

### ISSUE THREAD

**Issue by mhusar** [liyasthomas/postwoman#353]
Version: commit 37c41086d20ef89a009e58cca9235360161a731b

When I use the "Authentication" tab and choose "Bearer Token" as authentication type and define a token, the "Access-Control-Request-Headers" header is faulty.

current:
Access-Control-Request-Headers: authorization,undefined
should be:
Access-Control-Request-Headers: authorization

But on the server-side I defined, that only the authorization header is allowed:
Access-Control-Allow-Headers: authorization

When I define the "Authorization" header directly in the "Headers" tab, there is no problem. Reproducable with Firefox (Nightly) and Chrome (76).

**Comment by liyasthomas** [comment]
Issue has been identified. Let us investigate what went wrong and get back to you in a jiffy.
