### ISSUE TITLE
Feature request: OAuth header support/integration

### ISSUE THREAD

**Issue by benjaminhowarth1** [liyasthomas/postwoman#358]
**Is your feature request related to a problem? Please describe.**
A number of APIs and services are protected using OAuth these days, and it would be great to integrate an OAuth-specific header builder (similar to Postman) to enable easy testing of OAuth-protected resources.

**Describe the solution you'd like**
A header "builder" to construct an OAuth Authorization header.

**Describe alternatives you've considered**
None so far.

**Additional context**
This is a list of the authentication schemes that Postman supports - for a free tool, OAuth in particular would be very useful.
![List of authentication scheme builders that Postman supports](https://user-images.githubusercontent.com/322383/69751151-63ebc480-1146-11ea-8438-e0c96b9ac60c.png)

**Comment by AndrewBastin** [comment]
Hi there,

Thanks for opening the issue. OAuth is something really important to many workloads and is indeed a high priority thing to be implemented.

@liyasthomas @jamesgeorge007 @NBTX @athul @izerozlu 
Anyone willing to pick this issue up ? I am a bit in a handful with getting native wrapper going.

**Comment by liyasthomas** [comment]
@benjaminhowarth1 isn't this how OAuth is sent in a request?

```Authorization: Bearer xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx```

**Comment by AndrewBastin** [comment]
OAuth does use some standard URL parameters though....

We can look into those ?

**Comment by liyasthomas** [comment]
I can do that.
