### ISSUE TITLE
Raw request body for POST requests and Authorization key/value in Header

### ISSUE THREAD

**Issue by beautifwhale** [liyasthomas/postwoman#36]
**Is your feature request related to a problem? Please describe.**
I use Postman and it allows raw JSON to be used for the request body. I'd like to be able to copy/paste this raw JSON to use in Postwoman :)

Also I'd like to add `Authorization` as a key/value to the Header.

**Describe the solution you'd like**
Add a dropdown to the content-type selector for `raw` and provide a text area for me to past e my raw JSON for use in a POST request body.

Add an option to set key/value pairs in the Header.

**Describe alternatives you've considered**
I don't want to have to add key/value for each piece of information in the request body.

**Additional context**
none

**Comment by liyasthomas** [comment]
Surely consider this issue. Hopefully a PR will fix this in a day or two.
