### ISSUE TITLE
[bug]: Unable to upgrade with installer

### ISSUE THREAD

**Issue by baek-sang** [liyasthomas/postwoman#3676]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Upgrade app

### Steps to reproduce

1. https://hoppscotch.com/download
2. Download and execute installer

<img width="387" alt="hop" src="https://github.com/hoppscotch/hoppscotch/assets/69100154/9d93b0c7-49b3-41ba-b17d-de308abcbc20">

- Windows 11 23H2

### Environment

Release

### Version

Local

**Comment by liyasthomas** [comment]
The release is ongoing. Kindly stay patient for a while to complete the build pipelines.
