### ISSUE TITLE
Proxy server default configuration

### ISSUE THREAD

**Issue by FatDoge** [liyasthomas/postwoman#373]
**Is your feature request related to a problem? Please describe.**
I use the postwoman-proxy to create a private proxy server, and I want to use the server url become the default configutarion. There are many files that need to be changed, may be create a common config.json to export the DEFAULT_PROXY_URL?

**Comment by liyasthomas** [comment]
@NBTX

**Comment by FatDoge** [comment]
Also met the CORS problem.I have changed the ```config.json``` to fit my private postwoman.
#365

**Comment by liyasthomas** [comment]
I think `Access-Control-Allow-Origin` is only set to allow requests from `https://postwoman.io`.

**Comment by FatDoge** [comment]
yep, the default config is that,but I have changed it to my server address.

**Comment by NBTX** [comment]
You only need to make sure that the page you're accessing postwoman from is included in the `allowedOrigins` list. If you use the Postwoman app from postwoman.io with your proxy no additional configuration is required.

**Comment by FatDoge** [comment]
I will test it today and paste the result below.
