### ISSUE TITLE
Clearing shortcut overrides browser default

### ISSUE THREAD

**Issue by sergonius** [liyasthomas/postwoman#374]
**Describe the bug**
When pressing `CMD + L`, I expect to select the address bar. Instead, clearing is done and default browser behaviour is ignored. Doesn't seem to be an issue with Safari.

**To Reproduce**
1. Go to 'postwoman.io'
2. Press `CMD + L`
4. Address bar not selected

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome, Firefox

**Comment by liyasthomas** [comment]
Okay will map to another key then.
