### ISSUE TITLE
Styling with Tailwindcss

### ISSUE THREAD

**Issue by diego81b** [liyasthomas/postwoman#38]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Same opinionated question 😄: why didn't move to a css framework, for example Tailwindcss ? I think we could gain benefit on already done variation for screen size, theming, and an increasing community 

**Describe alternatives you've considered**
No

**Additional context**
No

**Comment by liyasthomas** [comment]
Wow, thats not a relavent feature.

**Comment by Ryanb58** [comment]
Tailwindcss is a cool framework. I think we should mock up the existing design using it before pursuing this in the main project.

I'll volunteer to do the mockup if this comment gets enough interest.

**Comment by liyasthomas** [comment]
@Ryanb58 you'll have enough support from me.

**Comment by Ryanb58** [comment]
You can follow along with the progress if you want:

https://jsfiddle.net/Ryanb58/jo4g6tpu/49/

**Comment by liyasthomas** [comment]
Tailwind integration looks promising. So far so good ✌️🔥

**Comment by Ryanb58** [comment]
I am feeling pretty confident in `tailwindcss` to replicate the existing design. 

Do you want us to move forward with this switch @liyasthomas ? I don't see this as a critical task right now, so if there are more pressing matters, I am open to switching to them before putting significant time into this one.

**Comment by liyasthomas** [comment]
At present, `tailwindcss` integration isn't that much relavent. I need you to test status of #55 and see what is wrong with Send button.

**Comment by liyasthomas** [comment]
Closing absolute issues
