### ISSUE TITLE
[UX] Hide history/collections 

### ISSUE THREAD

**Issue by andreujuanc** [liyasthomas/postwoman#387]
**Is your feature request related to a problem? Please describe.**
I don't use history/collections. So I would love to hide them since it takes 1/3 of my screen. I normally have 66% of the screen on code and the rest with either a UI or API client to develop faster.

**Describe the solution you'd like**
A drawer-hide button to hide and show the right panel. 

**Additional context**
We'll get FREE REALSTATE if we do this.

![image](https://user-images.githubusercontent.com/360052/69916007-c221eb80-1455-11ea-9c16-3900c5309459.png)

**Comment by NBTX** [comment]
![giphy](https://user-images.githubusercontent.com/43181178/69916056-fabdc700-144d-11ea-88d3-4a5dfe8221bc.gif)
On it!

**Comment by liyasthomas** [comment]
I opened my laptop 😄

**Comment by liyasthomas** [comment]
@NBTX can you make the page transitions work? It's partly working. I can do this. 😌

**Comment by NBTX** [comment]
@liyasthomas okay
