### ISSUE TITLE
[UX] Setting to make sidebar buttons small

### ISSUE THREAD

**Issue by andreujuanc** [liyasthomas/postwoman#389]
**Is your feature request related to a problem? Please describe.**
In small screens, the bar takes a lot of space.

**Describe the solution you'd like**
A setting that sets those buttons smaller

**Additional context**

![image](https://user-images.githubusercontent.com/360052/69916076-9ce1ad00-1456-11ea-8431-65a972a456bc.png)

**Comment by liyasthomas** [comment]
Resizable icons? This is the first time i heard of it. 😕

**Comment by andreujuanc** [comment]
Not resizable icons, just the buttons. Sorry, fixed title. :) 

I would take it even further, but I don't have much time now: something like this for comparison:

![image](https://user-images.githubusercontent.com/360052/69918918-944d9e80-1477-11ea-9df6-63eb5b936d6b.png)

![image](https://user-images.githubusercontent.com/360052/69918923-99aae900-1477-11ea-8169-9a46facc7459.png)
