### ISSUE TITLE
websocket support

### ISSUE THREAD

**Issue by adropofilm** [liyasthomas/postwoman#40]
**Is your feature request related to a problem? Please describe.**
It'd be nice to get WSS support for the app! Postman unfortunately doesn't have this but that dont mean POSTWOMAN cant :smiling_imp:

**Comment by liyasthomas** [comment]
I got my eyes on this feature 🔥✌️

**Comment by NBTX** [comment]
Oh yes!! This feature would be *so* useful for me. I do a lot of work with websockets and I have nowhere to go to work with them.
@liyasthomas feel free to assign me and I'll get working on this immediately!

**Comment by NBTX** [comment]
A preview of #48 is now live on my GitHub pages instance.
https://nbtx.github.io/postwoman-vue/

**Comment by liyasthomas** [comment]
Closing the issue since #51 solved it
