### ISSUE TITLE
Post can't send request

### ISSUE THREAD

**Issue by Kurt-Shiwz** [liyasthomas/postwoman#401]
**Describe the bug**
Post Mode can't send request.

Error: Network Error. Check console for details.
![image](https://user-images.githubusercontent.com/7554917/70222407-03cbd280-1785-11ea-8e1e-32900fb33256.png)

**Additional context**
I start go server listen localhost:8080

**Comment by liyasthomas** [comment]
`localhost` support is not implemented yet. This is a security feature imposed browsers. Please track of it's progress on #274 and hopefully will be solved on #267
