### ISSUE TITLE
可以给团队成员分享接口信息吗？(Can share to my team?)

### ISSUE THREAD

**Issue by anarckk** [liyasthomas/postwoman#408]
Can share to my team?

**Comment by liyasthomas** [comment]
Sharing requests can be done in two ways.

a)
1. Share a single request
2. Click the "Copy request" icon under "Send" button.
3. Public share URL of current request will be shared copied to clipboard.
 Share that URL to your yeam to reuse the exact request.

_For security purposes, Authentication sections are excluded from Share URL by default. But can be turned on manually from Authentication section. (Turn on "Include in URL")_

b)
1. Add all your requests to a collection/folder.
2. Export all Collections to a JSON
3. Send JSON export to your team
4. Import/replace that JSON on team side.

**Comment by anarckk** [comment]
OK, thank you

**Comment by liyasthomas** [comment]
### Hoppscotch for Teams is now out of closed beta.

✅   Unlimited teams

✅   Unlimited shared collections

✅   Unlimited team members

✅   Role-based access control

✅   Cloud sync

✅   Multiple devices

[Read more](https://liyasthomas.hashnode.dev/create-teams-for-collaboration-in-hoppscotch)
