### ISSUE TITLE
UI improvement suggestion for request method drop down

### ISSUE THREAD

**Issue by GglServe** [liyasthomas/postwoman#409]
**Describe the bug**
- With current UI of main page, the method selection offers an editable text field along with drop down to list the request methods.
- But just clicking on the drop down does not show all methods, you have to manually delete the method text (like 'GET') to be actually able to see all methods.
- This is somewhat confusing behavior, since expected behavior is to get a list of available methods for selection when clicking on down arrow of input box.
- Just clicking the down arrow does not show cursor in the method text box to let user know to delete the text first.

**To Reproduce**
1. Click on down arrow in request method on main page.
2. Only method visible is 'GET'

**Expected behavior**
Drop down list shows all available methods, or at least let me know to edit the method text manually.

**Screenshots**
![image](https://user-images.githubusercontent.com/52504930/70387019-ff422c80-19c5-11ea-8706-5c4959a22239.png)

**Desktop:**
 - OS: Windows 8.1
 - Browser: Brave
 - Version: 1.0.1 Chromium: 78.0.3904.108 (Official Build) (64-bit)

**Suggested fixes**
- All the methods should be visible when clicking on just down arrow in the text box
- Cursor should appear in text box when only down arrow is clicked to let user know that field is editable

**Comment by liyasthomas** [comment]
Issue has been identified. Will patch it ASAP.

**Comment by GglServe** [comment]
I see that now request method options are no longer editable. It fixes the UI issue. However, in the Readme documentation under Features -> Methods, a feature is listed as 

> <custom> - Some APIs use custom request methods such as LIST. Type in your custom methods.

Is this feature now available through any other option now?

**Comment by liyasthomas** [comment]
Just went into a UI bug, that's why I had to remove it temporarily. Will update tomorrow 👍
