### ISSUE TITLE
URL input text is so stutters

### ISSUE THREAD

**Issue by sccassiel** [liyasthomas/postwoman#412]
eg:"https://www.baidu.com/sugrec?prod=pc_his&from=pc_web&json=1&sid=1446_21095_30211_22160&hisdata=&req=2&csor=0"
If I input this string in URL input text then will be happend.

**Comment by liyasthomas** [comment]
Issue have been identified. Will fix it asap. Meanwhile you can just divide the URL and PATH and use them in their respective fields.

**Comment by sccassiel** [comment]
ok,tks

**Comment by liyasthomas** [comment]
Request from PW has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

since, all other endpoint doesn't have this issue, this could a
