### ISSUE TITLE
Oh my dear god why don't we just wrap it in electron

### ISSUE THREAD

**Issue by suny-yangke** [liyasthomas/postwoman#413]
https://electronjs.org/

**Comment by liyasthomas** [comment]
No need.

**Comment by NBTX** [comment]
![image](https://user-images.githubusercontent.com/43181178/70456621-0fb0e080-1a74-11ea-9136-fa982fc71831.png)
@suny-yangke

**Comment by TheSalarKhan** [comment]
I think there should be an optional build script for people who want to use this in electron. I'm interested in hoppscotch not because its a web app, but because its open source. <3 

There are a few problems with running it in the browser because we can't make calls to localhost for example. And for api-servers that don't set cors headers it also is not usable.

I have used electron to build a personal application for my use, I can raise a PR to add an electron build for hoppscotch. 

Thank you sooo much for the lovely product.

**Comment by liyasthomas** [comment]
> we can't make calls to localhost for example.
Yes you can. Install our official browser extension to access localhost endpoints. Links are in readme.

> api-servers that don't set cors headers it also is not usable.
Turn on proxy mode from settings.

Let me know if there's any other issues.

**Comment by TheSalarKhan** [comment]
Hey @liyasthomas thanks a ton. I really did not know about the extension. Also if I install the browser extension and turn on the proxy will I be able to interface with IPs in my local network or is the localhost the only possible endpoint?

**Comment by liyasthomas** [comment]
Proxy and extension can't work at once. To access local server = use browser extension. To access CORS restricted endpoints = turn on proxy mode. Proxy mode will mask your IP with that of the Proxy. Browser extension triggers the request from local server.

**Comment by TheSalarKhan** [comment]
Okay. Well in my usecase I have to interact with multiple services that are in development, usually they are on my localhost but sometimes they are on endpoints that are not publically accessible so can't use a proxy for that case. And turning off cors on them before accessing 

So there are use cases where running in the browser doesn't cut the mustard. But I'm really happy with this tool, and I'm using it inside an electron build and it works flawlessly without a proxy or an extension.

Cheers!

**Comment by KaKi87** [comment]
How about [Tauri](https://tauri.studio) ? 😊

**Comment by im-n1** [comment]
Electron is a bloat. Huge bloat. Don't another great project into that hole. If you want desktop app learn and use appropriate language/tools.

**Comment by KaKi87** [comment]
> If you want desktop app learn and use appropriate language/tools

Or, use [Tauri](https://tauri.studio/)

**Comment by im-n1** [comment]
> Or, use [Tauri](https://tauri.studio/)

No. Less overhead but still the same :hankey:

**Comment by KaKi87** [comment]
Tauri apps are very lightweight and much less resource-consuming than Electron apps.

**Comment by AndrewBastin** [comment]
I am working on a native app, just that it is not a big priority compared to the other features we want to work on and along with extension and PWA, most of the things a native app can do is basically possible.

The native app project worked on internally is based on a subset of Tauri using only parts of it we intend to use.

**Comment by liudonghua123** [comment]
Hi, I have tried to build Windows/Linux/macOS desktop apps using `Tauri`. You can try it on https://github.com/liudonghua123/hoppscotch-app/releases.  Looking forward to any bug reports, feature requests. 😃

**Comment by DanBurkhardt** [comment]
super super curious why this isn't officially released for macOS as an electron app. You could even ship on the App Store, kind of perplexing.
