### ISSUE TITLE
When uninstall the PWA the "install PWA" link in postwoman.io isn't appear anymore

### ISSUE THREAD

**Issue by shlomisas** [liyasthomas/postwoman#419]
**Describe the bug**
First of all, great initiative! thank you for that!

I installed the PWA via https://postwoman.io and then the download link doesn't appear anymore, i wanted to have it back (to take a screenshot and share it with my team) but after i uninstalled the app via chrome://apps the link doesn't appear there anymore, i tried to delete the web-worker, disabled the cache, use incognito but it's still not there.

**To Reproduce**
1. Install the PWA version via https://postwoman.io by clicking the link on the top header (next to the GitHub link)
2. Uninstall the app via chrome://apps
3. Go back to https://postwoman.io and looks for the same installation link
4. The link isn't there

**Expected behavior**
The link should be there and you'll be able to re-install the app

**Screenshots**
https://www.screencast.com/t/PWEysHafmnK

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 78.0.3904.108 (Official Build) (64-bit)

**Comment by liyasthomas** [comment]
Once you install the PWA, "Install PWA" button will be hidden.
To restore the button:

1. Unintall the current PWA
2. Clear brower cookie and site data
3. Navigate to http://postwoman.io

**Comment by shlomisas** [comment]
I did that (as mentioned I tried Incognito mode as well) but it still not appears.

The app is uninstalled, cookies/localStorage is clean (or Incognito) but it's not there.

**Comment by liyasthomas** [comment]
I jut repeated the above steps and I was able to restore the PWA button.

**Comment by shlomisas** [comment]
Here you can see a video of it: https://www.screencast.com/t/AA2JmU69y (sorry for the SWF :( )

Cookies are cleared, and as you can see in the video, Incognito was in use as well.

**Comment by liyasthomas** [comment]
Incognito mode won't allow u to use `localStorage` which is essential to PW. Consider clearing cookies and site cache/data and reefresh.

**Comment by shlomisas** [comment]
Oh, now it's working. thank you!
