### ISSUE TITLE
Feature Request: Consumer Driven Contract Testing

### ISSUE THREAD

**Issue by Breee** [liyasthomas/postwoman#420]
**Is your feature request related to a problem? Please describe.**
APIs need to be tested, postman allows me to execute contract testing using newman. 
Contract testing is imo the most effective way to test APIs.

**Describe the solution you'd like**
I'd love a tab "contract testing" where you can (1) define contracts between Consumers and Providers and (2) execute it to validate the contracts.
In an ideal world you can use Pact to execute the contract-testing part.

**Comment by liyasthomas** [comment]
#518 resolves this, hence closing.
