### ISSUE TITLE
No 'Access-Control-Allow-Origin'

### ISSUE THREAD

**Issue by DavidSmith2018** [liyasthomas/postwoman#426]
use docker 
#run
docker run -p 3000:3000 liyasthomas/postwoman:latest

' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by AndrewBastin** [comment]
Hi there,

Could you clarify the issue a bit more ?

CORS issues can be cleared (unless your target URL is local) by enabling the proxy.

Thank you!

**Comment by badandboy** [comment]
I have the same question，
CORS be cleared by enabling the proxy on https://postwoman.io
but on my own site, it doesn`t work

**Comment by liyasthomas** [comment]
Please consider reporting issues in given https://github.com/liyasthomas/postwoman/blob/master/.github/ISSUE_TEMPLATE/bug_report.md or at least tell how to reproduce the issue so we could track it and fix it ASAP.

**Comment by badandboy** [comment]
> Please consider reporting issues in given [Issue template](https://github.com/liyasthomas/postwoman/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) or at least tell how to reproduce the issue so we could track it and fix it ASAP.

all the methods can work well On the window system， on the linux system, they don`t works, including docker, npm run dev and npm run build

**Comment by liyasthomas** [comment]
> on the linux system, they don`t work

Our CI runs, tests and builds the project in [Linux](https://travis-ci.com/liyasthomas/postwoman), and have successful [Docker builds](https://hub.docker.com/r/liyasthomas/postwoman) too. Please tell how to reproduce your issue.

**Comment by badandboy** [comment]
> > on the linux system, they don`t work
> 
> Our CI runs, tests and builds the project in [Linux](https://travis-ci.com/liyasthomas/postwoman), and have successful [Docker builds](https://hub.docker.com/r/liyasthomas/postwoman) too. Please tell how to reproduce your issue.

1.
1）Clone this repo with git.
2）Install dependencies by running npm install within the directory that you cloned (probably postwoman).
3）Start the development server with npm run dev.
site : http://postwoman.badandboy.cn


2,
1）Clone this repo with git.
2）Install dependencies by running npm install within the directory that you cloned (probably postwoman)
3) npm run build
4) config postwoman2.badandboy.cn to dir dist
site: http://postwoman2.badandboy.cn

3,
1)docker pull liyasthomas/postwoman
#run
2)docker run -p 8888:3000 liyasthomas/postwoman:latest
site :  http://postwoman3.badandboy.cn

**Comment by gaoljhy** [comment]
u just try send <https://www.baidu.com> on <https://postwoman.io>
why this can't happen in postman

**Comment by liyasthomas** [comment]
Hope this answers might help.

https://stackoverflow.com/a/10636765
https://stackoverflow.com/a/13400954

**Comment by gaoljhy** [comment]
> Hope this answers might help.
> 
> https://stackoverflow.com/a/10636765
> https://stackoverflow.com/a/13400954

Okay,I get it,Thanks

**Comment by liyasthomas** [comment]
Unless the server doesn't imply any restrictions or we have a offline build. #267

**Comment by gaoljhy** [comment]
So cool !
