### ISSUE TITLE
Can I test localhost?

### ISSUE THREAD

**Issue by yinzhenkun** [liyasthomas/postwoman#433]

**Comment by AndrewBastin** [comment]
@yinzhenkun due to CORS restrictions in the browser, we can't do it in a straight forward way.

We have [Postwoman Proxy](https://github.com/postwoman-io/postwoman-proxy) which isn't really quite stable yet, but if it works, you can just set it as the proxy and get requests to localhost working.

**Comment by yinzhenkun** [comment]
Thanks for your prompt reply

**Comment by evbo** [comment]
Update: See instructions for proxying requests to localhost here: https://github.com/hoppscotch/hoppscotch/discussions/2051#discussioncomment-1887545
