### ISSUE TITLE
multipart/form-data support

### ISSUE THREAD

**Issue by namtruong95** [liyasthomas/postwoman#434]
**Is your feature request related to a problem? Please describe.**
Nothing

**Describe the solution you'd like**
Support upload file from request.

thanks.

**Comment by liyasthomas** [comment]
For RAW payload, you can use "upload file from request section".

And regarding file/formData payload support: will be implemented in upcoming weeks.

**Comment by liyasthomas** [comment]
#555 resolved this issue hence closing
