### ISSUE TITLE
graphql and websocket work, but http and https do not

### ISSUE THREAD

**Issue by mabushey** [liyasthomas/postwoman#441]
**Describe the bug**
Doesn't work for http and https requests. I tried enabling the proxy but the same result. It gets cookies and headers from the site, but appears to throw away the content.

**To Reproduce**
1. Go to postwoman URL (in k8s cluster)
2. get https://www.google.com
Error: Network Error. Check console for details. Same result with proxy enabled.

Network: headers
```
GENERAL:
Request URL: https://www.google.com/
Request Method: GET
Status Code: 200 
Remote Address: 172.217.14.196:443
Referrer Policy: no-referrer-when-downgrade

RESPONSE HEADERS:
alt-svc: quic=":443"; ma=2592000; v="46,43",h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000
cache-control: private, max-age=0
content-encoding: br
content-length: 65078
content-type: text/html; charset=UTF-8
date: Wed, 18 Dec 2019 23:30:16 GMT
expires: -1
p3p: CP="This is not a P3P policy! See g.co/p3phelp for more info."
server: gws
set-cookie: NID=194=Y2K7S1kMidDP1VYy2kySfA0Jo5GcpC29l1lWSCEWxGVSc-0kzP-QimflDXRAEjq4exaeWoWSBCsUnqJcLEhyP9sPRnh4Wv1CvXWW0qow6tkUuvQbUqbH8YHFR6_VFQe9gloFEENVL0-L9SjQXQFovJ7MGOsQ_oCMRO4CuLWyfzw; expires=Thu, 18-Jun-2020 23:30:16 GMT; path=/; domain=.google.com; HttpOnly
status: 200
strict-transport-security: max-age=31536000
x-frame-options: SAMEORIGIN
x-xss-protection: 0

REQUEST HEADERS:
:authority: www.google.com
:method: GET
:path: /
:scheme: https
accept: application/json, text/plain, */*
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9
origin: https://postwoman.tan.cyndx.io
referer: https://postwoman.tan.cyndx.io/
sec-fetch-mode: cors
sec-fetch-site: cross-site
user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) snap Chromium/79.0.3945.79 Chrome/79.0.3945.79 Safari/537.36
```

**Expected behavior**
Page pulled from google

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: chromium-browser
 - Version: Version 79.0.3945.79 (Official Build) snap (64-bit)

**Additional context**
It would be super helpful if the request could originate from the server component, that way I could test k8s endpoints from within the private cluster, without exposing any VirtualServices. Get and Post would need to work first... Running the `liyasthomas/postwoman:latest` container on k8s using CoreOS.

**Comment by liyasthomas** [comment]
Did you tried any other endpoints? I think https://www.google.com have tight Cross-Origin Resource Sharing policies. Try out with the default endpoint and see if the issue persist.

Read more about CORS: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
Possible duplicate of #2

**Comment by mabushey** [comment]
Probably Coors. My personal Grav blog doesn't even load in Postwoman. I have found one site other than reqres.in that does load: an instance of httpbin running in my k8s cluster. I think that the proper fix is to have the "server" make the requests instead of the browser. Until then I don't think I have any choice but to use the tool that works, Postman... :/  You project is great, I wish you the best with it.
