### ISSUE TITLE
cookie not found support

### ISSUE THREAD

**Issue by BruceWayneVsSuperMan** [liyasthomas/postwoman#443]
Our server responsed cookie not found error. 
But actually,with the same param postman worked.
I wonder know if I need to add some extra param when I use postwoman.

**Comment by liyasthomas** [comment]
Under normal conditions, params are sent as (async/await XHR) HTTP requests. If there's any  specific criteria for your server, you've to append that information either in params or headers as server needs.

**Comment by BruceWayneVsSuperMan** [comment]
Thanks for your reply.
I understand your meaning. But the thing I do want to know is how to make it work like postman.
Means that I don't need to add cookie or login info.
I want to use postwoman replace postman.Because I think it looks beautiful and I can use it in explore.

**Comment by liyasthomas** [comment]
Let me look into the issue and get back to you after a while. I think there's an option to use cookies with `withCredentials: true`

**Comment by BruceWayneVsSuperMan** [comment]
All right, waiting for your good news.

**Comment by liyasthomas** [comment]
Nuxt Axios module currently support credentials option only work when axios request to `baseURL` or relative path.

This is in the specification, not a bug.

https://github.com/nuxt-community/axios-module/issues/168#issuecomment-471670927

**Comment by NBTX** [comment]
I'm reading that we can just set `withCredentials: true` to the `.$post` options...

**Comment by liyasthomas** [comment]
But isn't that only supposed to be working on requests sent to same origin?

**Comment by BruceWayneVsSuperMan** [comment]
I just found something that may help us.
Please see this pic.
I am wondering if the secret is the postman-token param.

**Comment by BruceWayneVsSuperMan** [comment]
If you can't see this pic, leave me a message.Cause I was limited on internet,and I can't see if it's uploaded.

**Comment by liyasthomas** [comment]
Can't see the image.

**Comment by BruceWayneVsSuperMan** [comment]
Very appreciate for your patience and help.
I sent it to your email.Please check it out.

**Comment by liyasthomas** [comment]
Got the mail. It seems like, a cookie is sent as a custom header along with the request.

In PW, you can add custom Headers too. In **Options** section, navigate to **Headers** tab to add custom headers.

![1223_1](https://user-images.githubusercontent.com/10395817/71330525-8c9f8800-2553-11ea-88ad-1d785edd71c1.jpg)

But I wonder how you generated this custom header `postman-token`'s value? I suppose you took Cookie from Environment variables.

Here's a screenshot of how I added a custom header and generated cURL code snippet with PW.

![Screenshot_20191223-072254](https://user-images.githubusercontent.com/10395817/71330813-14d25d00-2555-11ea-9cf5-0bebf9f87dfb.png)


If you've limited internet access, no need to download the image, this is the generated cURL:

```
curl -X GET \
  'https://reqres.in/api/users' \
  -H 'cache-control: no-cache' \
  -H 'postwoman-token: this_can_whatever_you_want' \
  -H 'content-type: application/json'
```

**Comment by BruceWayneVsSuperMan** [comment]
Let me try.

**Comment by BruceWayneVsSuperMan** [comment]
Emmm…… actually,I didn't add the postman-token. Everytime when I try to request, postman will generate a new postman-token.
I read an article about it, this is the answer.

This is primarily used to bypass a bug in Chrome. If an XMLHttpRequest is pending and another request is sent with the same parameters then Chrome returns the same response for both of them. Sending a random token avoids this issue. This can also help you distinguish between request on the server side.

**Comment by liyasthomas** [comment]
Thanks! Will look into it

**Comment by BruceWayneVsSuperMan** [comment]
I think so.It will be better with your development.
Actually I received a lot of email last weekend cause I followed and watched this project, you were solving problems anytime,anywhere...

**Comment by liyasthomas** [comment]
Just shipped API documentation feature.

**Comment by jackflyer** [comment]
Is there any option to set withCredentials from front side? or guide on where to set that option.

**Comment by liyasthomas** [comment]
https://github.com/nuxt-community/axios-module/issues/168#issuecomment-471670927
