### ISSUE TITLE
UI Display Problems

### ISSUE THREAD

**Issue by ouer1994** [liyasthomas/postwoman#447]
![image](https://user-images.githubusercontent.com/23118182/71226583-4c53c600-2317-11ea-85c7-066d6dd0a4e2.png)

左上角 显示重叠

**Comment by ouer1994** [comment]
PWA

**Comment by liyasthomas** [comment]
Which device, operating system, browser and its version?

**Comment by liyasthomas** [comment]
Looks like there's some theming extension making window action align to left instead of right 😕
