### ISSUE TITLE
Improve SEO

### ISSUE THREAD

**Issue by liyasthomas** [liyasthomas/postwoman#45]
**Is your feature request related to a problem? Please describe.**
I think Postwoman lacks SEO. Can somebody look Into it?
**Describe the solution you'd like**
Let the world know there exists Postwoman - an online open sourced API request builder.

**Describe alternatives you've considered**
If GitHub pages seems incompatible, we could think about going for a hosting service since postwoman.net and postwoman.io have been brought by our kind supporters.

**Additional context**
Need thoughts on improving Postwoman. How about we start a feature request issue ticket so that people could request and discuss further features.

**Comment by NBTX** [comment]
I'm happy to host Postwoman for you for free. (I can use the web servers for ApolloTV).
If you have domains for postwoman, I think we should get those set up - I could host a proxy application to deal with CORS and HTTP-only requests.

**Comment by liyasthomas** [comment]
@NBTX few of my supporters said me the same thing. Among them, two guys brought postwoman.net and postwoman.io domains and hosted my GitHub deployment. They contacted me via email and promised they won't alter anything and will serve as it is in GitHub pages.

Basically I'm not good with domains, hosting and stuffs except I'd some side projects hosted on Firebase and on free hosting services such as freenom.

I very much appreciate if you could help me. Shall I ask them to transfer ownership of those domains to me? I don't know whether they ask for money and all, even though both of them said they'd do it for free.

**Comment by NBTX** [comment]
Yeah I checked both and one seems to be directly mirroring the GitHub pages (the .io) and the other seems to be stagnant on the older HTML one.

I think it would be beneficial for you to take ownership of the domains, just because if there's anything that needs to be updated, you'd be the first to know.

An ideal solution might be to use CloudFlare DNS - they put in CloudFlare's nameservers and then you set up the domain with a CloudFlare account you own - then you'll be able to manage the DNS for Postwoman.

**Comment by liyasthomas** [comment]
Lemme contact them and ask for transferring the domain ownership. And will let you know.

**Comment by NBTX** [comment]
Okay, I've sent a message on Twitter.

**Comment by NBTX** [comment]
It might be an idea to encourage people to add a link to postwoman to their site.
The absolute best thing for SEO is backlinks from organic traffic.

**Comment by liyasthomas** [comment]
Finally, ownership of postwoman.io is transferred. What's next?
Can't we just use custom URL for GitHub pages..?

**Comment by liyasthomas** [comment]
:fire: Deployed to https://postwoman.io
