### ISSUE TITLE
API Documentation won't be generated

### ISSUE THREAD

**Issue by reefqi037** [liyasthomas/postwoman#456]
**Describe the bug**
API Documentation won't be generated if the Request is not saved inside folder.

**To Reproduce**
1. Save a Request directly under Collections
2. Export the Collections
3. Import it in Documentations page
4. Only Collection name will be displayed.

**Expected behavior**
API Documentation should be displayed even if the Request is not stored under folder.

**Screenshots**
![API doc](https://user-images.githubusercontent.com/44827833/71338227-64834980-2592-11ea-982c-c5d62070e02d.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Vivaldi
 - Version: 2.10.1745.21 (Stable channel) (64-bit)

**Comment by liyasthomas** [comment]
Issue has been identified. Thanks for the quick bug report.
