### ISSUE TITLE
Can WSDL be implemented, similar to SoapUI?

### ISSUE THREAD

**Issue by myucxy** [liyasthomas/postwoman#461]
如题;

**Comment by liyasthomas** [comment]
I just tried with a sample WSDL url (http://wsf.cdyne.com/weatherws/weather.asmx?wsdl) and it worked. 

Try it out by going to this public share URL: https://postwoman.io/?method=GET&url=http://ws.cdyne.com/delayedstockquote/delayedstockquote.asmx?wsdl

Play around `POST` and any other methods and report back with feedback!

**Comment by liyasthomas** [comment]
Closing since WSDL can be implemented.

**Comment by MrCaperwood** [comment]
Hello @liyasthomas 

I am evaluating hoppscotch as a single API testing tool in pretty big company, targeting on-premise setup with maybe even enterprise support from you.

We have a bunch of different REST and SOAP services across multiple departments and hoppscotch would be a perfect fit.
However, I can't find any documentation how I can import SOAP Service using WSDL Specification. I would assume you have it similar to "Import OpenAPI specification", but it is not there.

Our major use cases(currently covered by SoapUI):

1. Import service definition from WSDL URL (or wsdl file) - that creates the collection of the requests per service endpoint
2. Validating a request against the WSDL
3. Validating a response against the WSDL
4. Define assertions on certain values (usually via XPath)
5. Extract values and use them for another request (variable handling)
6. Testdata sets which can be used on a Testsuite

If you could you point me the right direction how hopscotch can cover these use cases, I would much much appreciate your help.

Thank you in advance!
