### ISSUE TITLE
[Bug] Reduce font size for alt text of icons 

### ISSUE THREAD

**Issue by abhijithvijayan** [liyasthomas/postwoman#462]
This snap is captured on postman load. And it seems to reload the icons as well.

Isnt there someway to cache this icons or even use svg components.

Also, the text shown looks ugly.

![](https://i.imgur.com/1qn0iEH.png)

**Comment by liyasthomas** [comment]
Well, this looks ugly. We use Google Material Icon font. Let me see how it could be solved.

**Comment by liyasthomas** [comment]
I afraid `alt` text size cannot be decreased. Since it's an attribute to the icon.

Currently we do have pre-caching for icon fonts import, anyway will look into make experience much more faster.
