### ISSUE TITLE
[suggestion] - Tests tab

### ISSUE THREAD

**Issue by Olyno** [liyasthomas/postwoman#465]
**Is your feature request related to a problem? Please describe.**

I really love postwoman, and I'm using it to test my rest api. Problem: I currently can't make a serie of tests. I'm searching a way to automate requests and check if everything is fine or not, like if x request returns me correctly y response.

Of course maybe it's already implemented, and in this case I didn't find the way to do that, sorry about that.

**Describe the solution you'd like**

Add a new tab named "tests" where we could add a requests we saved in our collections, and a "predictable" reponse. Postwoman could test requests automatically using 1 single button.

**Describe alternatives you've considered**

Using the documentation tab, and implement it directly inside this one.

**Additional context**

/

**Comment by liyasthomas** [comment]
Will surely look into the possibilities of implementing them.

**Comment by liyasthomas** [comment]
> like if x request returns me correctly y response.

Do you really want to mention the exact predicted response or is it okay with the response code/state like 200 or 403 (success or forbidden)..?

**Comment by Olyno** [comment]
I think status could be enough

**Comment by allquixotic** [comment]
I use the "tests" feature of Postman to store variables into the collection, then refer to them in later API requests. This is very useful for things like unique tokens, generated access keys, etc. that are used from one request to the next. Without this feature in Postwoman, I have to manually copy values out of the response from earlier requests and paste it into the next.

**Comment by liyasthomas** [comment]
#218

**Comment by nickpalenchar** [comment]
This sounds doable, and can we can definitely leverage some work in pre-request hooks from #218  to extend into this.

**Comment by liyasthomas** [comment]
@nickpalenchar ping!

**Comment by nickpalenchar** [comment]
@liyasthomas hi still working but it's been smooth development! Probably can get it merged this weekend. 

I only have some weekend time to work on open source these days so progress will look more sporadic than usual for now. But you can check out work for this on [`feature/post-request-tests`](https://github.com/liyasthomas/postwoman/tree/feature/post-request-tests), branch, which I'll keep updating.

**Comment by liyasthomas** [comment]
@nickpalenchar Just a friendly reminder: In the past few days, base branch has been updated with lot of core features. I advise you to keep the https://github.com/liyasthomas/postwoman/tree/feature/post-request-tests branch updated with the `master` branch.

**Comment by nickpalenchar** [comment]
Ooh thanks for the update. I'll be back on this tomorrow but that’s a good point for my future week hiatuses. Looking to push it out tomorrow either way
