### ISSUE TITLE
Question: Why is this popular?

### ISSUE THREAD

**Issue by PDanielY** [liyasthomas/postwoman#466]
For some reason, this repo is really popular but what's the purpose? You could use [reqbin](https://reqbin.com) instead. What makes postwoman different than other websites for this?

**Comment by liyasthomas** [comment]
Good question! Actually I don't have a clear answer, but I think devs love an open source alternative. That's why.

**Comment by sevket-yilmaz** [comment]
Good question, good answer. 😄

**Comment by NBTX** [comment]
I think reqbin and other alternatives are aimed more at being a website that allows you to make requests.

Postwoman is much more than that - whilst our service can be used as a website, it's really a lightweight application and we have a lightweight proxy server (2MB in memory) to facilitate using Postwoman for testing local services.

We also offer WebSocket and GraphQL support which isn't as common as plain HTTP requests. In other words, our application is as powerful (or getting to be as powerful) as the more heavy applications whilst remaining very lightweight.

**Comment by PDanielY** [comment]
Got it!
