### ISSUE TITLE
What about additional loaders: + Pug, TypeScript, SASS, material-vue ?

### ISSUE THREAD

**Issue by ac2epsilon** [liyasthomas/postwoman#467]
**Is your feature request related to a problem? Please describe.**
It may be good add some productivity tools to tool chain 

**Describe the solution you'd like**
What about additional loaders: + Pug, TypeScript, SASS, material-vue ? All of these are proven good with both, Vue and Nuxt. I see no point to make branch on this. It is question of one npm -D.

**Describe alternatives you've considered**
Anything here is not a question at all, excepting vue-material support is newer than vuetify's, and later  is more nuxt-ish and have longer nuxt track/ this can be point of discussion but both are stable and  no very difference which will be accepted. All of this save on typing with no addition obligations.

Not if no. Let if yes

**Comment by liyasthomas** [comment]
All our components are custom elemnts we built from time to time on request. This kept us to keep the dependency list to the minimum. But seriously, PW do lack a UI library. Vuetify seems like a solid option for that.

> Pug, TypeScript, SASS
It's amazing what bare Vue/Nuxt app can do with only SCSS and JS (HTML + CSS + JS). A transpiled TS branch or any other language is good. But nobody requested it so far. I'll wait for a discussion on that.

**Comment by AndrewBastin** [comment]
@liyasthomas Actually I have been thinking of requesting a gradual migration to TypeScript as well, having the static types are really helpful to prevent the tiny mistakes we make while coding stuff up and also with the growing complexity of the app, it makes much more sense to have typings.

**Comment by liyasthomas** [comment]
I'll add a new branch for Typescript

**Comment by liyasthomas** [comment]
Tada! TypeScript branch: https://github.com/liyasthomas/postwoman/tree/typescript
Added Initial configs.
Nuxt Offical Guide: https://typescript.nuxtjs.org/

**Edit: There seems to be a runtime bug.**

**Comment by Sn005** [comment]
@liyasthomas 
Hi!
I Want to support resolve runtime errors by TypeScript.
If so, what should I do?
Can I create a new branch and send a pull request to the typescript branch?

I look forward to your reply.

**Comment by liyasthomas** [comment]
Actually, configs have been resolved to start a MVP. Now the remaining process is to compile each methods to `typed` function. Which is a long task.

You can start contributin by:

1. Git clone https://github.com/liyasthomas/postwoman/tree/typescript
2. Install dependencies: `npm i`
3. Start local dev server: `npm run dev`
4. Convert all `*.js` to typed `*.ts` files
4. Convert all `*.vue` files to typed functions / classes

Official guide: https://typescript.nuxtjs.org/

**Comment by Sn005** [comment]
@liyasthomas 

Thank you for your reply.
OK.
I understand how to contribute.
It's a long task, but I'm working on it.

**Comment by liyasthomas** [comment]
We've Telegram group: https://t.me/postwoman_app
Amd Discord server: https://discord.gg/GAMWxmR
for communication outside GitHub.

**Comment by AndrewBastin** [comment]
@Sn005 if you don't mind, I might also be working on this, I kinda know the typescript toolchain inside out as I usually work on TypeScript (gotta love dem type checks) and I would love to get this done ASAP.

**Comment by AndrewBastin** [comment]
And also since this issue thread mostly focuses on TypeScript support, I would like this issue renamed.

**Comment by Sn005** [comment]
@AndrewBastin 
No problem.
I am grateful because my usual work is busy.
However, I'm curious about how to proceed with long tasks.
I also want to commit to this task.
So, It would be helpful if you could share how to proceed with the task each time.

**Comment by AndrewBastin** [comment]
@Sn005 sure, well, right now my PR is up on this repo, we could certainly use your help with making the typings more strong as we still have tons of `any`'s in the project still.

**Comment by liyasthomas** [comment]
- [x] [TypeScript](https://github.com/liyasthomas/postwoman/tree/typescript)
- [x] SCSS support
- [ ] ~Pug~
- [ ] ~Component Libraries~

Since:
- TypeScript support is added
- Already have SCSS support (SASS is no more preferred)
- Pug support and component libraries such as Vuetify, Vue Material Kit is not essential at this stage of development

I'm closing this issue.
