### ISSUE TITLE
Friendly minded  GraphQL

### ISSUE THREAD

**Issue by ac2epsilon** [liyasthomas/postwoman#468]
GraphQL can be friendly minded

 It's hard for decent coder and impossible for novice to input right GraphQL query or mutator from the first take. And even from third. So: clicking on query have to fill request textarea with fully working template and click on type have to produce all-in-line repr like 

query {
    characters(page:${_page}) {
        info {count...}
        results {id name status species....}
    }
} // note as we do ${_page} - yeah we make variables automatically and show them in the list below query window 

All what user have to do is to remove fields she don't  wish to see in result. And we will see how to instantiate response for further scripting...
AND also there are UX ideas of course related to naive list of GQL types and queries. It must be tree or something folding or such. As I asked in other issue and do it again I wish to use one of the toolkits namely Material or Vuetify or whatever and then we came back to UX.  

Nobody does this. We are not competing. We dominate

**Comment by liyasthomas** [comment]
GraphQL testing is very _alpha_ and do need major polishing. Aoto-suggestions on query section and Tree model etc are few of them. Let's track GQL UX improvements on this thread 👍

**Comment by AndrewBastin** [comment]
@ac2epsilon thanks for opening this issue. Sorry, for the late response, I was away from Postwoman for the holidays.

Anyways, yeah you are right, the GraphQL UX needs a ton of polish and I will work on getting that properly done in the coming days.

**Comment by liyasthomas** [comment]
Since GraphQL section has improved tremendously ovee the past few week, I think this issue is stale now.
