### ISSUE TITLE
ULR parsing and var auto creation

### ISSUE THREAD

**Issue by ac2epsilon** [liyasthomas/postwoman#469]
As I see this people work like this: a) try url in browser actually b) copy to our input c) modify PUT params and rerun. So it have to be lending input where ppl paste/drag ready made url from browser. And then we parse url to parts like
Protocol: HTTPS
      Host: github.com
      Path: /liyasthomas/postwoman/issues/new
      Params: 
              assignees=${_assignees}
              labels=${_labels}
              template=feature_request.md
              title=${_title}
It will make easy to identify and modify params/ opens door to macro and scripting (instead or with pre-scripting). And will build ground to further WDSL/Swagger/gRPS impl(s)

**Comment by liyasthomas** [comment]
We currently have such a similar implementation. URL is parsed and populated to diff categories including parameters, payload, headers etc.

Users can make a request and we append it's attributes to URL as parameters making it a universally sharable link. Anybody with that link can replicate the same request from the other side by just visiting it.

Ex: https://postwoman.io/?method=GET&url=https%3A%2F%2Freqres.in&path=%2Fapi%2Fusers%3Fpage%3D2&headers=%5B%7B%22key%22%3A%22Age%22,%22value%22%3A%221200%22%7D,%7B%22key%22%3A%22Content-Length%22,%22value%22%3A%22300%22%7D%5D&params=%5B%7B%22key%22%3A%22page%22,%22value%22%3A%222%22%7D%5D

Is this exactly what you mentioned? May be I didn't get what you really meant. Care to elaborate?

**Comment by liyasthomas** [comment]
Closing for to inactivity
