### ISSUE TITLE
Post request body is empty

### ISSUE THREAD

**Issue by Kurt-Shiwz** [liyasthomas/postwoman#473]
I send post request to localhost,the body is empty

in postwoman:
![image](https://user-images.githubusercontent.com/7554917/71758730-6b895080-2ede-11ea-9c15-9f12fab5ba60.png)

![image](https://user-images.githubusercontent.com/7554917/71758659-c53d4b00-2edd-11ea-9a56-d47829f53f11.png)

in curl:
![image](https://user-images.githubusercontent.com/7554917/71758672-dab27500-2edd-11ea-9bc4-7ae36726dabd.png)

![image](https://user-images.githubusercontent.com/7554917/71758701-1cdbb680-2ede-11ea-8f22-e6baa966bf12.png)

 OS: macos 10.15.2
 Browser chrome 79

**Comment by liyasthomas** [comment]
Is there any errors on console?

**Comment by Kurt-Shiwz** [comment]
> Is there any errors on console?

![image](https://user-images.githubusercontent.com/7554917/71758929-a68c8380-2ee0-11ea-979c-55650eceb7c8.png)

**Comment by liyasthomas** [comment]
I afraid being a PWA, Postwoman can't access `localhost` via browser without a proxy. Please use our official [Postwoman Proxy](https://github.com/postwoman-io/postwoman-proxy) to access `localhost`.

**Comment by Kurt-Shiwz** [comment]
> I afraid being a PWA, Postwoman can't access `localhost` via browser without a proxy. Please use our official [Postwoman Proxy](https://github.com/postwoman-io/postwoman-proxy) to access `localhost`.

failed
![image](https://user-images.githubusercontent.com/7554917/71759513-0c7d0900-2ee9-11ea-8a9e-2cdef9f8d4b6.png)

![image](https://user-images.githubusercontent.com/7554917/71759487-a09aa080-2ee8-11ea-9c0f-e24e11afa5b6.png)

![image](https://user-images.githubusercontent.com/7554917/71759496-cc1d8b00-2ee8-11ea-9b78-d1eb21a8908c.png)

**Comment by liyasthomas** [comment]
@NBTX

**Comment by liyasthomas** [comment]
`localhost` support is not implemented yet. This is a security feature imposed by browsers. Please track it's discussion on #274 and hopefully will be solved on #267

Regarding issue while setting up Proxy: Please consider moving the issue to [proxy repo](https://github.com/postwoman-io/postwoman-proxy)

**Comment by johnbabu021** [comment]
i also faced this problem but it's perfect when i switched the browser
