### ISSUE TITLE
import cURL error

### ISSUE THREAD

**Issue by nmvjhd** [liyasthomas/postwoman#477]
When I click "import cURL" button, input such as 
curl -X GET 'https://api.github.com/users/nmvjhd'
, then click import , the page show the "cURL is not formatted property" toast.
Am I operate wrong?help

**Comment by liyasthomas** [comment]
Fixed in c6f877
Please verify and close this issue.

**Comment by liyasthomas** [comment]
@nmvjhd
> Am I operate wrong?help

`curl -X GET 'api.github.com/users/nmvjhd'` 👎 
won't work unless you add URL `protocol` (https, http etc).
Ex:
`curl -X GET 'https://api.github.com/users/nmvjhd'` 👍

**Comment by nmvjhd** [comment]
this situation is ok but I find it can't import parameters such as:
curl "https://api.github.com/repos/vmg/redcarpet/issues?state=closed"
or
curl -G -d "state=closed" "https://api.github.com/repos/vmg/redcarpet/issues"
when imported, the parameters panel has nothing

**Comment by liyasthomas** [comment]
Okay, will fix ASAP.

**Comment by nmvjhd** [comment]
ok, thanks
