### ISSUE TITLE
Request has no response data

### ISSUE THREAD

**Issue by stajason** [liyasthomas/postwoman#478]
#### I use java project, which can be accessed normally in other channels, but I can't return response in postwoman.
![image](https://user-images.githubusercontent.com/18157487/72002262-0ccb2a80-3282-11ea-97c4-790ba4297e88.png)

**Comment by liyasthomas** [comment]
Please tell how to reproduce the bug?

**Comment by stajason** [comment]
I use Java springboot project and nginx proxy to local domain name.
Should it be a matter of proxy?
```nginx
server {
  listen       80;
  server_name  platform-services.me;


  location / {
    proxy_pass   http://127.0.0.1:7019;
  }
}
```
![image](https://user-images.githubusercontent.com/18157487/72030303-86cfd380-32c3-11ea-91be-4a414e16e3de.png)

**Comment by liyasthomas** [comment]
Were there any errors in the console?

**Comment by stajason** [comment]
> Were there any errors in the console?

I see, just cross domain problem.

**Comment by liyasthomas** [comment]
I can't reproduce the issue with any other URL. Please share public share URL (current URL of PW's state).
