### ISSUE TITLE
pages/index.vue 1736

### ISSUE THREAD

**Issue by kenzyyang** [liyasthomas/postwoman#480]
**Describe the bug**
while this.response.headers is undefined,it will cause a error.
![image](https://user-images.githubusercontent.com/27340803/72123831-9cb1c700-339d-11ea-8219-e5e456117c2f.png)

**Comment by AndrewBastin** [comment]
Well, according to the HTTP spec, you can't exactly have a response without headers, so I don't see why it will become undefined. The only thing is that response can choose to not have a `Content-Type`, but we do handle that case as seen from the above snippet

If you could bring into attention a scenario where that is possible, we will refactor the code.

**Comment by kenzyyang** [comment]
now i can't replicate the problem but i'll tell you immediately the next time.
and it's better to handle the situation where this.response and this.response.headers is undefined.
thanks for your reply
