### ISSUE TITLE
Application contains many hard-coded strings that aren't translatable

### ISSUE THREAD

**Issue by alecananian** [liyasthomas/postwoman#488]
**Describe the bug**
I've found about 150+ unique hard-coded strings in the application code for titles, placeholders, toast messages, etc that are untranslatable because they're not set up to be compatible with `nuxt-i18n`.

**To Reproduce**
1. Select any language other than English
2. Observe untranslated strings even on the homepage ("search history", "History is empty", etc)

**Expected behavior**
All phrases are available for translation in the localized JSON files

 - OS: any
 - Browser: any
 - Version: any

**Additional context**
I can create a pull request fixing as many of these as I could find, it just touches a ton of files so I wanted to confirm it's desired first or if the maintainers have any further suggestions.

**Comment by liyasthomas** [comment]
So sorry for this, `i18n` needs contributors such as you to make it complete. Core devs have been busy with other feature requests and bug fixes and have very little time to work on translations.

If you're willing to take this challenge, we're happy for that. Shall I assign this task to you?

**Comment by liyasthomas** [comment]
**`i18n` contributuion checklist:**

- [ ] **Pull the latest changes from `i18n` branch**
- [ ] Find `lang/<<your_file>>.js`
- [ ] **Replace existing dummy translations** with actual translated lacale (no need to update `nuxt.config.js` if language is already added once)
- [ ] Save changes, Commit changes, **Push to `i18n` branch only**

Refer English translation file https://github.com/liyasthomas/postwoman/blob/i18n/lang/en-US.js for reference and stylings. Ping me for any doubts.

**Comment by alecananian** [comment]
Sure! Happy to do it. Does it make sense to do this as a branch off the current `typescript` branch since they both touch many files, or just off `master`?

**Comment by liyasthomas** [comment]
Let me make `master` and `i18n` branch even and will let you know in 2 mins.

**Comment by liyasthomas** [comment]
Here you go: https://github.com/liyasthomas/postwoman/tree/i18n

**`i18n` contributuion checklist:**

- [ ] **Pull the latest changes from `i18n` branch**
- [ ] Find `lang/<<your_file>>.js`
- [ ] **Replace existing dummy translations** with actual translated lacale (no need to update `nuxt.config.js` if language is already added once)
- [ ] Save changes, Commit changes, **Push to `i18n` branch only**

Refer English translation file https://github.com/liyasthomas/postwoman/blob/i18n/lang/en-US.js for reference and stylings. Ping me for any doubts.

**Comment by alecananian** [comment]
Seems I couldn't commit directly to this repository, so I forked the `i18n` branch. Here are the changes: https://github.com/liyasthomas/postwoman/pull/489

**Comment by liyasthomas** [comment]
Fixed in #490  #491
