### ISSUE TITLE
Change import/export collection on requests page icon

### ISSUE THREAD

**Issue by freitzzz** [liyasthomas/postwoman#495]
**Is your feature request related to a problem? Please describe.**
I'm fairly new to Postwoman and I was wondering how I could export a collection. I've read README.md and noticed that it was possible, yet I've spent approximately 5 minutes browsing through Postwoman figuring out how to export my collection, and the only way I was able to find it was to search by the 'export' word in the source code. This could be a personal opinion but I think the icon that is currently being used to represent the import/export collection is not delivering the appropriate usability as its illustrative intent is to sort/reverse a list.

**Describe the solution you'd like**
Change import/export collection icon to one which properly indicates these functionalities or separate the usage of the functionalities by their own icons (e.g. Import use [`Upload`](https://cdn4.vectorstock.com/i/1000x1000/95/93/cloud-upload-icon-vector-22039593.jpg) icon and Export [`Download`](https://cdn1.iconfinder.com/data/icons/arrows-vol-1-4/24/download_1-512.png) icon).

**Describe alternatives you've considered**
Separate the usage of the functionalities by their own icons (e.g. Import use [`Upload`](https://cdn4.vectorstock.com/i/1000x1000/95/93/cloud-upload-icon-vector-22039593.jpg) icon and Export [`Download`](https://cdn1.iconfinder.com/data/icons/arrows-vol-1-4/24/download_1-512.png) icon).

**Additional context**
--

**Comment by liyasthomas** [comment]
Fix coming in next commit :+1:

**Comment by liyasthomas** [comment]
Fix coming in next commit :+1:

**Comment by freitzzz** [comment]
Thank you! :)
