### ISSUE TITLE
GraphQL String variables are null

### ISSUE THREAD

**Issue by MichalBednarz** [liyasthomas/postwoman#497]
**Describe the bug**
String variables provided for GraphQL query have null values.
Besides unquoted input I also tried to wrap String variable value with double and single quotes but result was the same.

**To Reproduce**
1. Go to /graphql
2. Provide GraphQL query
3. Provide variables (including String type variable)
4. Click "Run Query"
5. See null variables values in request preview in console

**Screenshots**
![Screen Shot 2020-01-17 at 11 10 41](https://user-images.githubusercontent.com/23276452/72603819-09870d00-391a-11ea-840e-9dcefec9ecd5.png)
![Screen Shot 2020-01-17 at 11 11 22](https://user-images.githubusercontent.com/23276452/72603871-27547200-391a-11ea-8985-c9166fb7542e.png)

**Desktop**
 - OS: macOS
 - Browser: chrome
 - Version 79.0.3945.88 (Official Build) (64-bit)

**Additional context**
Query performed with proxy disabled in settings

**Comment by liyasthomas** [comment]
@AndrewBastin @pushrbx

**Comment by pushrbx** [comment]
Assign this to me @liyasthomas please, I will do it.

**Comment by liyasthomas** [comment]
Fine. 🚀

**Comment by AndrewBastin** [comment]
Actually, me being busy with cross platform biz, I couldn't catch up on GraphQL updates.

Not gonna sugar coat this, the current implementation for variables sucks. I honestly, can't believe I let it happen.

Variables in GraphQL may not be just some simple values, but can also be complex nested objects (facilitated through stuff like [Input](https://graphql.org/graphql-js/mutations-and-input-types/) types)

The best approach to handling variables is either by providing a JSON editor which is parsed into a JS object when the query is ran and then injecting the objects, or by making the current variable editor, type sensitive and allowing stuff like nesting.

**Comment by pushrbx** [comment]
@AndrewBastin Initially when I added this feature I thought I'd add apollo-client as dependency, because it gives you proper errors for invalid variables, and it has type checking. However it seemed too much effort because a major refactor would be required. God bless laziness.
