### ISSUE TITLE
Ability to run all requests of a folder/collection

### ISSUE THREAD

**Issue by freitzzz** [liyasthomas/postwoman#498]
**Is your feature request related to a problem? Please describe.**
Sending multiple requests of a collection takes to much time due to being necessary to change between requests each time these are to be sent.

**Describe the solution you'd like**
A list-item that allows the to send all requests of a folder/collection.

**Describe alternatives you've considered**
A button that performs this action is also desirable.

**Additional context**
--

**Comment by liyasthomas** [comment]
Request for "chaining requests" is already raised before on #218
