### ISSUE TITLE
Readable

### ISSUE THREAD

**Issue by jgroom33** [liyasthomas/postwoman#5]
A test flow should be readable in a repository. It should not require a UI to run the tests. It should be succinct and compact.

Reference [ansible uri](https://docs.ansible.com/ansible/latest/modules/uri_module.html) and [strest](https://github.com/eykrehbein/strest) for examples.

Handling loops, if conditions, and wait should also be possible without requiring the tester to write JavaScript.

**Comment by liyasthomas** [comment]
I didn't get what you meant. Please elaborate what you tried to convey. I would like to hear what you've to share.

**Comment by jgroom33** [comment]
one of the challenges with Postman is that it requires a UI to run and update tests.  The json output of a postman collection is unreadable because it is too complex.  because of this complexity, when these json collections are committed to a git repository they are essentially binaries that require a UI.

A better solution is to use YAML that implements a DSL for executions.  This eliminates the need for writing javascipt in `pre-request scripts` and `tests`

Ansible URI and stREST are examples of a yaml syntax with a DSL for executions.

**Comment by liyasthomas** [comment]
Thanks for you quick clarification. I'll look into it.

**Comment by liyasthomas** [comment]
#209 fixes this, hence closing.

**Comment by jgroom33** [comment]
This project has implemented all the things I was suggesting:
Yaml, cache, var storage, test assertion
https://testmace.com/
