### ISSUE TITLE
Sync collection with a cloud storage (e.g: Google drive)

### ISSUE THREAD

**Issue by AdityaAnand1** [liyasthomas/postwoman#507]
What is the feature? Postman Teams essentially, without any dedicated backend, we just piggy back off a cloud storage provider.

So, how it would work is basically like:

1. You're using postwoman, making changes
2. You decide to simultaneously share collection with your teams, so both frontend and backend (multiple members) can collaborate and get access to the same - always up-to-date - collection without having to export/import over and over again.
3. User connects with their Google drive
4. Postwoman collection gets saved in google drive
5. User gets a unique URL for collection
6. Anyone can access URL (as per google doc like sharing feature)
7. Any changes made to collection are synced with the google drive backed collection file.

This would essentially obsolete Postman's biggest use-case.

Check out this application

https://www.draw.io/

Draw.io has a fantastic implementation of this, highly recommend trying out the experience. It's a diagram drawing tool (with not much of a backend for itself, it just piggy backs off of google drive), you can save a diagram to a folder in your google drive, share the diagram link with someone, and you can both work on the same file together.

So, essentially google drive APIs allow you to add real-time collaboration (and other cloud storage goodies) to an app (like Postwoman).

This would literally be a (postman-)killer feature.

Would love to collaborate on this (or anything else in this direction). What are your thoughts on adding collaborative functionalities? (@liyasthomas @jamesgeorge007 @AndrewBastin @NBTX)

**Comment by liyasthomas** [comment]
@AdityaAnand1 feature suggestion sounds great! Would love to work on it.

And the mention website does the job neatly. Will plan for an MVP, and we would love to add you as a collaborator.

**Comment by liyasthomas** [comment]
We can certainly make use of Firebase functions, auth, etc for initial prototype. Google sign in seemes to ba piece of cake with Firebase Auth.

**Comment by Congee** [comment]
Then I can really ditch Postman.

**Comment by liyasthomas** [comment]
MVP is ready 🎉 

checkout `auth` branch for development: https://github.com/liyasthomas/postwoman/tree/auth

- [x] Auth with Google
- [x] Auth with GitHub
- [x] Add data to Firestore
- [ ] Delete data from Firestore
- [ ] UI 50% completed
- [ ] Sync and test all the above

**Comment by Congee** [comment]
@liyasthomas you da best!

**Comment by liyasthomas** [comment]
I've also add few bugs to be fixed later 😉

**Comment by AdityaAnand1** [comment]
Awesome speed!

Is it now possible for a team to collaborate on the same collection?

**Comment by liyasthomas** [comment]
Oh no, teams are not yet implemented.
We now have Auth + Sync for a single user account.
Well that's not enough isn't it!
..
..
Okay lets build teams now. ✌️

**Comment by AdityaAnand1** [comment]
Do check out the draw.io website @liyasthomas.

Since the current implementation uses firebase storage, the draw.io approach (originally described here as above) might offer significant benefits, including not having to maintain your own backend. And it'd make implementing collaboration (#580) way easier.
