### ISSUE TITLE
Support S3 as saving/sharing collections backend-storage

### ISSUE THREAD

**Issue by bbkgh** [liyasthomas/postwoman#514]
Hi. I think supporting S3 interface as a storage backend can be very useful feature for storing states server-side and facilitates collection sharing/syncing.

**Comment by liyasthomas** [comment]
Great suggestion!

Well, we've already working on an Auth + Sync feature and is in beta testing #513 using Firebase Auth and Firestore.

Checkout the deploy preview and see whether it is enough or not: https://deploy-preview-513--postwoman.netlify.com/
