### ISSUE TITLE
Add max-height and overflow: auto to "parameter list" textarea

### ISSUE THREAD

**Issue by KytoSai** [liyasthomas/postwoman#532]
**Is your feature request related to a problem? Please describe.**
When i try to put on a parameter is too long, then the display of the "parameter list" taking up too much space, which make me have to scroll up/down serveral times very annoying.
(actual situations we might encounter as parameter will be the content of an article)

**Describe the solution you'd like**
I think postwoman should set a max-height and overflow: auto to avoid this

**Additional context**
![https://i.imgur.com/gzaeoW5.jpg](https://i.imgur.com/gzaeoW5.jpg)

Thanks !

**Comment by liyasthomas** [comment]
Did you tried "Raw input" for parameter list?

1. Turn on "Raw input" toggle.
2. Paste you "lengthy" paramaters
3. Send request

**Comment by KytoSai** [comment]
Thanks you! it work, i try turn off after turn on, it will show scrollbar

Demo: https://i.imgur.com/AJuHq3H.jpg

**Comment by liyasthomas** [comment]
Turn on RAW input > Paste parameters > Send.
Text area will expand up to 16 lines and then show vertical scrollbar. 

> (turn off to switch to key-value pair)
