### ISSUE TITLE
Feature request: Keyboard shortcuts for folder creation

### ISSUE THREAD

**Issue by Grayda** [liyasthomas/postwoman#539]
**Is your feature request related to a problem? Please describe.**
It's mildly annoying to have the "Create Folder" box not Save & Close when you press Enter, or close when you press Escape.

**Describe the solution you'd like**
I'd like to see the Create New Folder dialog box updated so when you press Enter, it'll create the folder. Additionally, it'd be good to have Escape close out of the box, which would make it consistent with a typical desktop experience (as well as the behaviour when creating folders in Postman)

**Describe alternatives you've considered**
I tried both Ctrl+Enter and Ctrl+S. Ctrl+Enter did nothing, and Ctrl+S brought up the "Save Request" box.

**Additional context**
This also applies to other dialogue boxes, such as the "Save Request" box.

**Comment by liyasthomas** [comment]
That's a good suggestion! 👍
