### ISSUE TITLE
Feature Request: Subfolders

### ISSUE THREAD

**Issue by Grayda** [liyasthomas/postwoman#540]
**Is your feature request related to a problem? Please describe.**
I've got an API I wish to document that has several sub-APIs (e.g. one from a status monitor hosted elsewhere), but I can't create folders deeper than directly under the collection.

**Describe the solution you'd like**
I'd like to create sub-folders within a collection. For example: `api.auroras.live (Collection)` => `v2 (Folder)` => `alerts (Folder)` => `Get all alerts (Request)`.

It'd be great to allow folders a few levels deep, but within reason of course (e.g. 2-3 levels deep would cover most peoples' needs)

**Describe alternatives you've considered**
I've considered naming my folders with a hyphen to denote levels, such as `v1 - users`, `v1 - products` etc. which would work, but take some careful planning, especially since you can't drag to re-order folders.

**Additional context**
Might look something like this:

![image](https://user-images.githubusercontent.com/4891563/73433102-30bcf000-4398-11ea-9fb7-655392b82e05.png)

**Comment by liyasthomas** [comment]
I don't think this is a required feature. Anyways, will try to implement if anyone else raises this issue again.
