### ISSUE TITLE
relative module not found during start

### ISSUE THREAD

**Issue by fazzomurata** [liyasthomas/postwoman#552]
**Describe the bug**
1. Downloaded latest version. 
2. npm install
3. npm run dev  
During npm run dev a module was not found:

Failed to compile with 1 errors
This relative module was not found:           
* ..**/.postwoman/version.json** in ./node_modules/babel-loader/lib?ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./layouts/default.vue?vue&type=script&lang=js&

**To Reproduce**
1. npm run dev

**Comment by liyasthomas** [comment]
#327

**Comment by AndrewBastin** [comment]
@fazzomurata if the above solution fixed your issue, please close the issue
