### ISSUE TITLE
Disable SSL cert for websockets

### ISSUE THREAD

**Issue by and7ey** [liyasthomas/postwoman#557]
There should be an option to disable SSL certificates validation for websockets.
Sample python example:
`ws = websocket.WebSocket(sslopt={'cert_reqs': ssl.CERT_NONE}, origin='http://example.com/')`

**Comment by liyasthomas** [comment]
Are you using a self-signed cert for the purpose?

**Comment by and7ey** [comment]
No. 
Use websocket_client python library, https://github.com/websocket-client/websocket-client. FAQ there says that it disables ssl cert verification. 
If I try to connect to the same webserver with postwoman, then connection is immediately closed. If I do it with python script and ssl cert verification disabled - it works fine.

**Comment by liyasthomas** [comment]
This seems to be a subset of #392 . And both implementation have same scope. Closing this issue temporarily for tracking the previously requested feature.
