### ISSUE TITLE
firebase_app__WEBPACK_IMPORTED_MODULE_2___default.a.firestore is not  a function 

### ISSUE THREAD

**Issue by pz9042** [liyasthomas/postwoman#558]
os : mac 10.13.6
npm:6.13.7
nodejs:v12.14.1
postwoman :master

when run ` npm run dev`，and then open http://192.168.3.94:49420/, js error: firebase_app__WEBPACK_IMPORTED_MODULE_2___default.a.firestore is not a function

**Comment by liyasthomas** [comment]
Due to security concerns, Firebase functionalities are restricted to the following URLs:
- https://postwoman.io
- `http://localhost` port:3000, 5000 (testing)

Either serve the prohect in mentioned ports or disable Firestore functionalities.

**Comment by jackflyer** [comment]
How to disable Firestore functionalities, while using ports than 3000?

**Comment by liyasthomas** [comment]
You've to manually disable those.
