### ISSUE TITLE
Can't send request to localhost via Chrome extention

### ISSUE THREAD

**Issue by erfanium** [liyasthomas/postwoman#560]
I can't send request to my localhost server. I get Network Error message.

**Screenshots**
![Link to Screenshot from 2020-02-07 13 49 24](https://user-images.githubusercontent.com/47688578/74023457-f1545c00-49b4-11ea-8c23-e755b5a582e0.jpeg)

![Screenshot from 2020-02-07 13 54 21](https://user-images.githubusercontent.com/47688578/74023492-05985900-49b5-11ea-9eb9-00a1f1741f46.jpeg)

![Screenshot from 2020-02-07 13 57 22](https://user-images.githubusercontent.com/47688578/74023506-0d57fd80-49b5-11ea-9a52-97db3946867f.jpeg)

 - OS: Elementary os
 - Browser: Chrome
 - Version: 79.0.3945.88 (Official Build) (64-bit)

**Comment by AndrewBastin** [comment]
Thanks for opening up the issue, I will look into this ASAP.

**Comment by AndrewBastin** [comment]
Okay, I have uploaded the patch to Chrome Web Store. It will take a couple of days to go through reviews (have some updated permissions), I will close this issue when the new version is live on the Chrome Web Store.

**Comment by AndrewBastin** [comment]
Okay the update is up.

Closing issue.

**Comment by erfanium** [comment]
@AndrewBastin 
I still have that problem using chrome extension version 0.3.

**Comment by erfanium** [comment]
@liyasthomas  @AndrewBastin 
This problem is found again in the new version 1.9.0 + chrome extension 0.5.0
![Screenshot from 2020-03-19 19-49-30](https://user-images.githubusercontent.com/47688578/77089320-ee6c7280-6a1a-11ea-874b-441ae3e6fc24.png)

**Comment by AndrewBastin** [comment]
@erfanium The latest version of the Chrome Extension is Version 0.5. Please update your Postwoman Extension and report back if the issue still persists.
