### ISSUE TITLE
Auto Theme Selection is kinda difficult to see

### ISSUE THREAD

**Issue by AndrewBastin** [liyasthomas/postwoman#563]
**Describe the bug**
In Postwoman's Settings, the Auto theming mode is usually difficult to spot and usually takes the background color of the selected theme. Especially in the Just Black theme.

**To Reproduce**
1. Go to Settings
2. Try changing the themes

**Comment by liyasthomas** [comment]
Yeah, just saw that. Will fix it with default "prefered color theme"

**Comment by liyasthomas** [comment]
Fixed in 0b6671d538221b27c46aa36c32c9bcea152d4026
