### ISSUE TITLE
Get correct response data but occurs with error "Cannot read property 'value' of undefined"

### ISSUE THREAD

**Issue by ishowman** [liyasthomas/postwoman#575]
**Describe the bug**
After send the request, and get the error info "Cannot read property 'value' of undefined", while the request shows that it get data success when I check  the api in devtool Network
**To Reproduce**
1. Fill with `Method: Get, Url: 'https://dxhdyy.ga.sz.gov.cn',  Path: '/2019ncov/js/home.js?v=202002132300'`
2. Click on 'Send'
3. Scroll down to 'Response'
4. See error  "Cannot read property 'value' of undefine"
5. check the api in Network, it is success
```
success: true
data: "..."
status: 200
```

**Expected behavior**
Response show the data of data field

**Desktop (please complete the following information):**
 - OS: Win10 X64 19041
 - Browser: Chorme
 - Version: 80

**Additional context**
It's happend today, while it's absolute normal yesterday

**Comment by liyasthomas** [comment]
Can you give the sharable link of your request setup?
Does this setup meets your mentioned setup? https://postwoman.io/?method=GET&url=https://dxhdyy.ga.sz.gov.cn&path=/2019ncov/js/home.js?v=202002132300&params=%5B%7B%22key%22:%22v%22,%22value%22:%22202002132300%22%7D%5D

**Comment by yterletskyi** [comment]
I'm experiencing the same issue, however CORS is working correctly.
For example see the request to a public api: 
https://postwoman.io/?method=GET&url=https%3A%2F%2Fworldtimeapi.org
(https://worldtimeapi.org/api/timezone)

![image](https://user-images.githubusercontent.com/11182351/83031370-24daf500-a03d-11ea-8103-e215456fbfb5.png)

Could you please help?

**Comment by liyasthomas** [comment]
@yterletskyi endpoint: `worldtimeapi.org/api/timezone` seems to be working fine at my end.
Open in an incognito tab and test:  https://postwoman.io/?method=GET&url=https://worldtimeapi.org&path=/api/timezone

**Comment by yterletskyi** [comment]
@liyasthomas works good in an incognito tab. 
Do you think some configurations on browser fail it?

**Comment by liyasthomas** [comment]
@yterletskyi no, browser configs may not be an issue. Confirm it is working by clearing the cache and testing on regular tab. Let me know if the issue persists.

**Comment by yterletskyi** [comment]
Worked by your recipe. I'm not sure what caused it, if you need more details from my end let me know thanks.
