### ISSUE TITLE
don't run

### ISSUE THREAD

**Issue by alterem** [liyasthomas/postwoman#577]
✖ Client
  Compiled with some errors in 6.20s

 WARN  Compiled with 1 warnings                                                                                                                                               friendly-errors 16:36:37

 WARN  in ./node_modules/yargs-parser/index.js                                                                                                                                friendly-errors 16:36:37

Critical dependency: the request of a dependency is an expression                                                                                                             friendly-errors 16:36:37
                                                                                                                                                                              friendly-errors 16:36:37

 ERROR  Failed to compile with 1 errors                                                                                                                                       friendly-errors 16:36:37

This relative module was not found:                                                                                                                                           friendly-errors 16:36:37
                                                                                                                                                                              friendly-errors 16:36:37
* ../.postwoman/version.json in ./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./layouts/default.vue?vue&type=script&lang=js&    friendly-errors 16:36:37
ℹ Waiting for file changes                                                                                                                                                                    16:36:38
ℹ Memory usage: 225 MB (RSS: 534 MB)                                                                                                                                                          16:36:38

**Comment by liyasthomas** [comment]
Instead of downloading the zip and starting the server, try cloning with `https://github.com/liyasthomas/postwoman.git`.

#327
