### ISSUE TITLE
500 this.isValidURL is not a function

### ISSUE THREAD

**Issue by Looper-01** [liyasthomas/postwoman#58]
**Describe the bug**
internal error
500 this.isValidURL is not a function

**To Reproduce**
1. git clone the master branch
2. npm install and run dev
3. visist http://localhost:3000/  then mock a request

**Screenshots**
![image](https://user-images.githubusercontent.com/13216359/63646046-f0e54300-c73d-11e9-9842-9458a239591c.png)
![image](https://user-images.githubusercontent.com/13216359/63646047-fa6eab00-c73d-11e9-97b3-c29921098d70.png)

**Comment by liyasthomas** [comment]
https://github.com/liyasthomas/postwoman/commit/5a8c9f5533df3fe153a82b88190334aff6c94ffa fixed this issue. Thanks @Looper-01 for quick issue ticket
