### ISSUE TITLE
Parameter list not showing JSON object fields (force raw?)

### ISSUE THREAD

**Issue by leomp12** [liyasthomas/postwoman#597]
**Describe the bug**
JSON body is not being properly parsed to _parameter list_, when _raw input_ is disabled the body seems to be empty even with a valid object set.

> I'm not really sure if it's a bug, Imho the best approach is just force _raw input_ for `application/json` content type and hide the switch input (feature request ?).
I can give a try if you agree :bowtie:

**To Reproduce**
1. As example, go to [this request](https://postwoman.io/?method=POST&url=https://api.e-com.plus/v1&path=/applications.json&contentType=application/json&headers=%5B%7B%22key%22:%22X-Store-ID%22,%22value%22:%221056%22%7D,%7B%22key%22:%22X-My-ID%22,%22value%22:%221234%22%7D,%7B%22key%22:%22X-Access-Token%22,%22value%22:%22123%22%7D%5D&rawParams=%7B%0A%20%20%22app_id%22:%209000,%0A%20%20%22title%22:%20%22My%20Awesome%20E-Com%20Plus%20App%22,%0A%20%20%22slug%22:%20%22my-awesome-ecom-plus-app%22,%0A%20%20%22type%22:%20%22external%22,%0A%20%20%22state%22:%20%22active%22,%0A%20%20%22authentication%22:%20true,%0A%20%20%22modules%22:%20%7B%7D,%0A%20%20%22auth_scope%22:%20%7B%0A%20%20%20%20%22stores/me%22:%20%5B%0A%20%20%20%20%20%20%22GET%22%0A%20%20%20%20%5D,%0A%20%20%20%20%22procedures%22:%20%5B%0A%20%20%20%20%20%20%22POST%22%0A%20%20%20%20%5D,%0A%20%20%20%20%22products%22:%20%5B%5D,%0A%20%20%20%20%22brands%22:%20%5B%5D,%0A%20%20%20%20%22categories%22:%20%5B%5D,%0A%20%20%20%20%22customers%22:%20%5B%5D,%0A%20%20%20%20%22orders%22:%20%5B%5D,%0A%20%20%20%20%22carts%22:%20%5B%5D,%0A%20%20%20%20%22orders/fulfillments%22:%20%5B%5D,%0A%20%20%20%20%22orders/payments_history%22:%20%5B%5D,%0A%20%20%20%20%22products/quantity%22:%20%5B%5D,%0A%20%20%20%20%22products/variations/quantity%22:%20%5B%5D,%0A%20%20%20%20%22products/price%22:%20%5B%5D,%0A%20%20%20%20%22products/variations/price%22:%20%5B%5D%0A%20%20%7D,%0A%20%20%22auth_callback_uri%22:%20%22https://us-central1-ecom-app-boilerplate.cloudfunctions.net/app/ecom/auth-callback%22,%0A%20%20%22version%22:%20%221.0.0%22%0A%7D);
2. Disable _raw input_ if enabled;
3. Any property is shown on _parameter list_;

**Expected behavior**
On provided example, I was expecting to see `app_id`, `title` and the other body object properties on _parameter list_, or just force _raw input_ for `application/json` and then show JSON body as is (Imo it would be even better than fix parameter list behavior).

**Screenshots**
![Screenshot_2020-02-24 Postwoman • A free, fast and beautiful API request builder(1)](https://user-images.githubusercontent.com/10326572/75189720-8ed9ba80-572d-11ea-9910-7f627935ddb9.png)
![Screenshot_2020-02-24 Postwoman • A free, fast and beautiful API request builder](https://user-images.githubusercontent.com/10326572/75189723-900ae780-572d-11ea-9936-5727e2c3cde7.png)

**Desktop (please complete the following information):**
 - OS: Linux 5.5.5-arch1-1 (Arch Linux)
 - Browser: Firefox
 - Version: 73.0.1 (64-bit)

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by liyasthomas** [comment]
well, the raw parameter feature for payload enables us to send nested arrays, import JSON file contents etc. So I afraid we can't directly map the raw parameter objects to key -value pairs.

And regarding forcing whether key-value pair or raw parameters toggle, well this seems like a better option since even though the provided example request had raw parameters enabled, I was served with the default key-value pairs at first. I'd to manually toggle to raw parameters to see tje payload.

**Comment by leomp12** [comment]
@liyasthomas great! You want me to give a try? If so, you can assign me to the issue.

**Comment by liyasthomas** [comment]
sure! We'd love to have you onabroad! Assigning this to you.

**Comment by liyasthomas** [comment]
@leomp12 how's the progress on this issue?

**Comment by leomp12** [comment]
Hey @liyasthomas ,
I haven't had time yet, sorry :disappointed:
I was planning to do it next week, probably on Monday or Tuesday, it's ok for you to wait?

**Comment by liyasthomas** [comment]
yeah sure! ✌️💯
