### ISSUE TITLE
Editorconfig file

### ISSUE THREAD

**Issue by izerozlu** [liyasthomas/postwoman#60]
**Is your feature request related to a problem? Please describe.**
Related to development process. In some files indentations are not synchronized.

**Describe the solution you'd like**
It'd be useful to have an `.editorconfig` file to synchronize formatting between files.

**Describe alternatives you've considered**
Manual formatting. It was painful.

**Additional context**
```
[*.vue]
indent_style = tab
indent_size = 4
```

**Comment by liyasthomas** [comment]
I personally use StandardJS on all my projects.

**Comment by NBTX** [comment]
@sfrankian Remember to take .editorconfig out of .gitignore.
I edited this myself, so I'll just remove my copy of the file

**Comment by Ryanb58** [comment]
Looks like this issue has been solved:
https://github.com/liyasthomas/postwoman/pull/82

**Comment by liyasthomas** [comment]
Closing fixed issues
