### ISSUE TITLE
Why does the URL input field display only one line

### ISSUE THREAD

**Issue by notfound945** [liyasthomas/postwoman#604]
When I was debugging the API interface, I found a very unfriendly experience.
When I type in a long URL, I often need to scroll through the URL field to see the URL I typed in, because it only displays on one line, which is inconvenient.
So, I wonder if there is a way to cope?

**Thank you !**

**Comment by liyasthomas** [comment]
Thanks for the bug report! The issue has been identified. Sorry for the bad UX, we're working on it as we speak.

Please follow the initial issue ticket: #62 and #581 
PR to fix the issue: #603 

Closing this issue in favor of #62 and #581
