### ISSUE TITLE
Can't login on Brave Browser

### ISSUE THREAD

**Issue by taksumaki** [liyasthomas/postwoman#607]
**Describe the bug**
I try to log in from the PC with Google or with Github but I only get an error that the action has been denied.

**To Reproduce**
1. Go to 'Sign in options'
2. Click on 'Google or Github options'
3. Scroll down to 'Nothing'

**Expected behavior**
I was hoping to be able to log in as well to be able to synchronize all my requests.

**Screenshots**
![Captura de pantalla de 2020-02-26 12-03-14](https://user-images.githubusercontent.com/56084970/75378486-6373de80-5899-11ea-91fc-c04492182f50.png)

**Desktop:**
 - OS: Linux (Solus Os Latest)
 - Browser: Brave browser
 - Version 1.3.118

**Comment by dmitryyankowski** [comment]
Thanks for starting an issue thread for this @taksumaki We'll make sure we get this sorted out ASAP! Thanks for your patience :)

**Comment by dmitryyankowski** [comment]
I'm wondering if this was a temporary thing? Can you reset the application cache and then right click -> `Inspect Element > Application > Clear site data` and then refresh and try again @taksumaki ? I can login with Github and Google just fine, at the moment. 

If not, this could also be an issue with Firebase not set to allow multiple accounts with the same email address. I know that I already signed up with Github with an email address, and if I try to login to Google with that email address it won't let me login. There's an option in Firebase to disable this.

![image](https://user-images.githubusercontent.com/20114263/75380292-c0c15d00-58a4-11ea-93f5-8b86544970b3.png)

**Comment by taksumaki** [comment]
No, my Github account and my Google account have totally different emails.

Also try the steps of deleting the site data as you said, and the same result.

Attached video of the page.
![2020-02-26 14-18-21](https://user-images.githubusercontent.com/56084970/75384828-3c6eda00-58a4-11ea-957a-a030f9fe189b.gif)

**Comment by dmitryyankowski** [comment]
I see you're using the Brave browser. Can you use the regular Chrome browser, and tell me if it works then? @taksumaki

**Comment by taksumaki** [comment]
With Google Chrome it seems to work perfect, I can log in normally. I don't understand why with **Brave Browser** you can't.

**Comment by dmitryyankowski** [comment]
Hmm yeah interesting! Atleast we found the root of the issue :) Thanks for the troubleshooting steps. @liyasthomas

**Comment by liyasthomas** [comment]
There'll be a 3rd party extension or prolly an in-built feature that restrict access to store cookies.

Track issue ticket on Brave community: https://community.brave.com/t/cant-sign-in-to-any-website-using-google-sign-in/38109
