### ISSUE TITLE
Requests to local API returning error response

### ISSUE THREAD

**Issue by taksumaki** [liyasthomas/postwoman#608]
**Describe the bug**
I try to make the "POST" request (the same goes for the other types) and I don't get an answer, just an error message that says there was an error in the connection, I even tried it with Postman and it works perfect. In the attached Gif video you can see the problem with better clarity.

**To Reproduce**
1. Go to 'Make a new request'
2. Click on 'Send button after filling in the request data.'
3. Scroll down to 'Response section'

**Expected behavior**
I expected to see the message from the api showing me the data sent by that request.

**Screenshots**
![2020-02-26 14-48-54](https://user-images.githubusercontent.com/56084970/75386937-2400be80-58a8-11ea-81aa-d3532544aad9.gif)

**Desktop**
 - OS: Linux (Solus Os Latest)
 - Browse: Google Chrome
 - Version: 79.0.3945.130

**Comment by dmitryyankowski** [comment]
Thanks for the report! My fellow contributors should be able to assist you more than I can at the moment :) @NBTX @jamesgeorge007 @liyasthomas

**Comment by liyasthomas** [comment]
You need to install our official Browser Extension to support `localhost`. Link can be found in `readme`.

#433 #274 #56
