### ISSUE TITLE
HTTP request with different library

### ISSUE THREAD

**Issue by diego81b** [liyasthomas/postwoman#61]
**Is your feature request related to a problem?**
No

**Describe the solution you'd like**
Why the need to use xhr instead, for example, Axios.
One factor should be the need to use interceptors before or after request

**Describe alternatives you've considered**
Any

**Additional context**
No

**Comment by izerozlu** [comment]
@diego81b I suppose the main reason for this decision is to keep the application as light as possible.
But in my opinion, it'd be easier to maintain the application with a proper library.

**Comment by liyasthomas** [comment]
As I've mentioned in #76 we could possible use anyone from of these:
- NuxtJS HTTP Module https://http.nuxtjs.org
- Axios https://axios.nuxtjs.org

**Comment by NBTX** [comment]
I vote axios.

**Comment by diego81b** [comment]
Another solution could be use Fetch Api but is not supported on IE11 ( damn IE 😄) and do not have interceptor.
On the same way intersting will be the abort Api (they works with xhr) but it is another matter 😅

**Comment by NBTX** [comment]
As I'm working on building a proxy to bypass the Same-Origin policy, I'm going to address this issue, as axios interceptors will make implementing the proxy much cleaner.
