### ISSUE TITLE
Support SocketIO connections on Realtime page

### ISSUE THREAD

**Issue by ilomon10** [liyasthomas/postwoman#611]
**Is your feature request related to a problem? Please describe.**
I need to test my socketio server

And then install postwoman to test but i dont know how to config connection to server.
I ever test with `ws://localhost:3001` or `wss://localhost:3001`

**Describe the solution you'd like**
Maybe you can add option socketio client with minimal config.

**Additional context**
![image](https://user-images.githubusercontent.com/25215779/75400627-c5385500-593a-11ea-82bd-7bbe39ff0aca.png)

- Thank you

**Comment by dmitryyankowski** [comment]
I believe @NBTX was going to be working on some Realtime page improvements! It would definitely be great to have an option for testing SocketIO! Great suggestion @ilomon10 :)

**Comment by NBTX** [comment]
As at @dmitryyankowski has mentioned, I do intend to revamp the Realtime page.

**Comment by moonrailgun** [comment]
@NBTX  Hi , i am a deep user of socketio. And i am glad to postwoman can support socketio soon.

Can i join it? Hopes to contribute my power to this work.

**Comment by liyasthomas** [comment]
@moonrailgun Welcome to the team! We're busy with other improvements, can I assign this to you?

**Comment by moonrailgun** [comment]
@liyasthomas Of course. I am glad to add this feature.

**Comment by konradkalemba** [comment]
Hey @moonrailgun, great work with adding socket.io support. One thing I noticed is the lack of ability to listen to all events, not only `message`. 

I believe [this package](https://github.com/hden/socketio-wildcard) can solve the problem.

**Comment by konradkalemba** [comment]
I went ahead and created a PR which resolves the problem. Any feedback is welcome.
