### ISSUE TITLE
Fast URL entry

### ISSUE THREAD

**Issue by NBTX** [liyasthomas/postwoman#62]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Similar to Postman's interface, I think we should make the URL entry a single bar at the top, with the method on the left. Then we should just parse the URL and fill in the relevant information.

We could keep the extra sections but this would make Postwoman a lot more intuitive and faster to use.

**Describe alternatives you've considered**
n/a

**Additional context**
![image](https://user-images.githubusercontent.com/43181178/63654349-20fa0980-c771-11e9-8a7c-4a94e9b199d7.png)
*As shown, Postman parses the URL as it is entered and automatically fills in the relevant sections.*

**Comment by NBTX** [comment]
I'm happy to implement this myself, but I wanted to open a discussion on the matter.

**Comment by liyasthomas** [comment]
This fact might surprise you: other than seeing some screenshots on internet, I haven't used Postman or seen its UI (this is just because, my 7 year old pc can't afford to run another Electron app). Afterall, I didn't intend to create an alternative to Postman, in my opinion this project should outperform any other such tools, since its lightweight, faster & opensource.

If there's any feature we'd like to add, all are free to discuss here. Everything is better when there's freedom and customisation in it.

**Comment by liyasthomas** [comment]
@NBTX see #63 and share your thoughts. Me too think this is an essential feature somehow I forgot at the first place. My bad. Anyway thanks for pulling it up.

**Comment by NBTX** [comment]
I'm actually only drawing the parallel to Postman's interface from experience, rather than because the names are similar, and this is the UI I'm used to - but this, as I said is something I would find useful.

I already very much prefer Postwoman because it's so much lighter. Even on my pretty decent systems Postman takes upwards of 7 seconds to start up, and then usually has several annoying pop ups to deal with.

**Comment by liyasthomas** [comment]
#93 needs similar kinda approach

**Comment by terranblake** [comment]
@liyasthomas and @NBTX i'd like to take this one for hacktoberfest 😄

**Comment by liyasthomas** [comment]
@terranblake you are free to contribute to this 🔥👌 assigning to you.

**Comment by terranblake** [comment]
@liyasthomas for this feature to be implemented, i do have a couple questions about a proposed design. 

1. can the `path` field be removed as a part of the solution?
2. can i move the `permalink` and `show code` buttons below the `url` field on the same plane as `import cURL`?

**Comment by liyasthomas** [comment]
@terranblake yes you can. `permalink` & `show code` can be moved to bottom of the section. 

currently `path` is appended to request, you must resolve that while making changes.

there are binding for `path` in various methods, you must resolve that too.

**Comment by NBTX** [comment]
@terranblake I imagine you would just use the JavaScript URL object:
`const target = new URL("https://example.com/test");`

In which case you can just get `.path`, `.host`/`.hostname`, etc.
As @liyasthomas mentioned, `path` is in a separate variable so you will need to split the URL and handle them separately but part of the goal of this ticket is to have the entire URL (querystring and all) handled in a single input box as it is with postman.

**Comment by terranblake** [comment]
Hopping on this one tonight. Will keep this issue updated.

**Comment by terranblake** [comment]
<img width="1254" alt="Image 2019-10-07 at 8 06 36 PM" src="https://user-images.githubusercontent.com/8795767/66364295-0bfec180-e93e-11e9-93ed-e8e7640f8175.png">
This is what I have so far. Nothing too crazy.

**Comment by liyasthomas** [comment]
@terranblake you tested? Any bugs?

**Comment by terranblake** [comment]
Query params are imported directly into the parameters section. I am having an issue with the `Referer` field of the request getting blown up...

**Comment by liyasthomas** [comment]
Lemme take a look at it and possibly help you 🙂

**Comment by terranblake** [comment]
Alrighty. I'll fork. One sec

**Comment by terranblake** [comment]
Should be available on [this branch](https://github.com/terranblake/postwoman/tree/terranblake/fast-url-entry)

**Comment by dmitryyankowski** [comment]
This seems to have been implemented. Can this be /closed? @NBTX @liyasthomas

**Comment by liyasthomas** [comment]
I afraid, this feature was incomplete and branch became stale. Lemme run some tests.

**Comment by liyasthomas** [comment]
#591 resolve this hence closing

**Comment by JacobAnavisca** [comment]
Heyo! Just made a PR for this https://github.com/liyasthomas/postwoman/pull/603
used a regex and I did some testing but might be good for others to try it out as well
