### ISSUE TITLE
[HELP] Auth permission denied

### ISSUE THREAD

**Issue by mzch** [liyasthomas/postwoman#621]
**Describe the bug**
I set up firebase and Github Oauth, but authentication fails because of permission denied.
How can I fix this issue?

**To Reproduce**
1. Go to homepage
2. Click on Github
3. See error: `PERMISSION DENIED`

**Expected behavior**
Login successfully.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 10.15.3
 - Browser Chrome
 - Version 80.0.3987.122

**Additional context**

**Comment by dmitryyankowski** [comment]
Are you running the repo locally or are you on the live site https://postwoman.io? More info is appreciated @mzch thanks!

**Comment by mzch** [comment]
Sorry, I'm running locally, https://postfellow.com

**Comment by dmitryyankowski** [comment]
I see you are running MacOS and I can confirm there is an issue when I just tried to login on a Mac w/ Chrome. (I was logging in with 2Factor auth as well; Not sure if that matters)

![image](https://user-images.githubusercontent.com/20114263/75509591-349f5a80-59b6-11ea-96f5-28b144dafb02.png)

@liyasthomas @NBTX @jamesgeorge007 @AndrewBastin

**Comment by mzch** [comment]
I tried to login via Postwoman (Postwoman is running on Debian 10.3)...

<img width="1736" alt="ScreenShot 2020-02-28 13 23 27" src="https://user-images.githubusercontent.com/621178/75510300-d615c300-5a2d-11ea-9012-252637832611.png">

I have already added `postfellow.com` to authorized domains in the console of Firebase.

**Comment by dmitryyankowski** [comment]
@liyasthomas

**Comment by liyasthomas** [comment]
Auth + sync is only tailored to postwoman.io

**Comment by mzch** [comment]
@liyasthomas 
Is it impossible to auth Google/Github by modifing functions/fb.js?

**Comment by mzch** [comment]
Oh, when rerunning `npm run build`, then fixed. Thanks!
