### ISSUE TITLE
How to debug localhost (cors)

### ISSUE THREAD

**Issue by liuyibo123** [liyasthomas/postwoman#630]
How to debug localhost api?

**Comment by dmitryyankowski** [comment]
Click the dropdown at the top right and click extensions. And install the Postwoman extension for your browser! This will allow development to your localhost address :) @liuyibo123

**Comment by liuyibo123** [comment]
Thank you for your answer ,but my really question is that I deployed postwoman on my own server and I want use it to debug localhost. Is there a solution？

**Comment by liuyibo123** [comment]
@dmitryyankowski 
Thank you for your answer ,but my really question is that I deployed postwoman on my own server and I want use it to debug localhost. Is there a solution？

**Comment by dmitryyankowski** [comment]
@liuyibo123 we don't formally have support for hosts other than https://postwoman.io and http://localhost:3000, at this time!

**Comment by liuyibo123** [comment]
@dmitryyankowski Okay . Thank you  all the same
