### ISSUE TITLE
How to use postwoman for local development and testing

### ISSUE THREAD

**Issue by McRaeAlex** [liyasthomas/postwoman#634]
I am trying to use postwoman to test an API I have built. I have installed the PWA but I still get CORS issues.

My understanding is that since the PWA is just a browser I will continue to have this issue.

Has this problem been solved already? Is there a build of postwoman I can run that will allow me to run with localhost:port as the domain?

**Comment by liyasthomas** [comment]
Use Browser extensions to resolve `CORS` issues.

 - [Firefox](https://addons.mozilla.org/en-US/firefox/addon/postwoman/)
 - [Chrome](https://chrome.google.com/webstore/detail/postwoman-browser-extensi/amknoiejhlmhancpahfcfcfhllgkpbld)

#433 #274

**Comment by allthesignals** [comment]
I do not understand how to use Postwoman for local development. I can't get localhost:3000 to point to my locally-running API. I

**Comment by allthesignals** [comment]
I have the chrome extension and the proxy setting enabled but i cannot get it to access localhost:3000

**Comment by AndrewBastin** [comment]
@allthesignals

If you want use Postwoman for a local API, do not use the proxy, proxy routes your request through a separate server which means it can't connect to your local server.

Just use the browser extension and disable the proxy, thank you 😁

Please report back even if disabling proxy didn't work.

@liyasthomas, this is becoming a common occurance. Should we discuss about adding a warning or something of that sort ?

**Comment by liyasthomas** [comment]
I think the "Enable Proxy" toast on every failed request is what makes users to enable proxy. Shall we open extensions modal instead of it? since all exceptions of Proxy is covered with extension and those who wanna turn on proxy can enable that by going to settings > proxy.

**Comment by allthesignals** [comment]
Ah, thank you about that and sorry for not reading closely enough. I believe when it asked about the proxy, I gave that a shot. 

Amazing project, by the way.

**Comment by liyasthomas** [comment]
Thanks for replying. If there's anything you'd like to know, ping us.

**Comment by allthesignals** [comment]
The only thing is that for some reason, this endpoint gives a blank response body. Note the content-type is application/vnd.api+json: https://applicantmaps-api.herokuapp.com/projects

![image](https://user-images.githubusercontent.com/5004319/77215288-b1bb7c80-6ae9-11ea-966a-5dbe7453d610.png)

**Comment by allthesignals** [comment]
Oh, interesting: when I hit the "copy response," I see this:

`[object Object]`

Going to open an issue... would love to dig in and help! I _love_ this app (PWA!)
