### ISSUE TITLE
A suggestion for UI 

### ISSUE THREAD

**Issue by erfanium** [liyasthomas/postwoman#635]
![Screenshot from 2020-03-02 20-53-04](https://user-images.githubusercontent.com/47688578/75701075-59524580-5cc8-11ea-9dbc-e27930ab79af.png)

Hi
As you see, Parts of Contents like Status, connection, content-length, content-type & date are too much big, They aren't that important either, And they can take up much less space.
Also for right panel

Better to have more space for more important parts, Like Response Part

**Comment by liyasthomas** [comment]
Noted 📝

Thanks for the suggestions, we'll consider these tweaks in next major UI revamp.

**Comment by dmitryyankowski** [comment]
Definitely agree with @erfanium here! I've been trying to work on that, on the GraphQL page. Things need to be compressed down in size, and only have the more important aspects larger.
