### ISSUE TITLE
Info: The current domain is not authorized for OAuth operations Error

### ISSUE THREAD

**Issue by Allakazan** [liyasthomas/postwoman#637]
I'm trying to deploy Postwoman in my server and i'm getting this error: "Info: The current domain is not authorized for OAuth operations".
Apparently the Firebase just let me login with localhost or postwoman.io domain. How can i bypass it ?

**Comment by liyasthomas** [comment]
Current Auth logic is tailored only for postwoman.io and localhost:3000. To configure custom domains, create your own Firebase app and change configs on `functions/fb.js`
