### ISSUE TITLE
Environment variable in path won't update

### ISSUE THREAD

**Issue by Bettelstab** [liyasthomas/postwoman#641]
I would like to test different environments with the same set of requests. So I create an environment variable `root` (via environment management or pre-request) and use it in the request's path:
```<<root>>/public/blogger```
That works as expected, however, when I change `root` later on, the path is not updated. I would expect it to update.

Video: https://fashiontale.org/index.php/s/njZSJDrnj6qQqYM

As a quick fix, it's possible to just save the path again (programmatically). But I guess it would be nicer to store the raw path without variable replacement, which would also solve #642  .

Thanks for running this project, it's amazing what happened here in such a short time!

**Comment by Bettelstab** [comment]
I just figured out that everything (including saving to collections) works as expected, if `root` is not set before it's used. Still unexpected ;)

**Comment by liyasthomas** [comment]
I think this issue could be solved as #642 gets fixed. Closing this to track the issue #642.
