### ISSUE TITLE
Environment variables in collections

### ISSUE THREAD

**Issue by Bettelstab** [liyasthomas/postwoman#642]
I have a request with path ```<<root>>/public/blogger```, which I want to run against different environments. I save this request in a collection. I would expect to be able to change the environment (and, hence, `root`) again later. But when I load the saved request, `root` is already replaced with the value it had when I saved the request.

Video: https://fashiontale.org/index.php/s/Aaz77P7breqAeK8

**Comment by liyasthomas** [comment]
Thanks for reporting the issue.
