### ISSUE TITLE
Test script is not run after failing request

### ISSUE THREAD

**Issue by Bettelstab** [liyasthomas/postwoman#644]
I run an unauthenticated request against an endpoint requiring authentication, so I get a 401 response. In the test script, I want to test for that response:
```
pw.expect(pw.response.status).toBe(401);
```
But the test script is not executed, as it seems.

Edit:

Steps to reproduce:
1. Put `https://api-staging.fashiontale.de/protected/address` as URL
2. Click 'Add test script' and uncomment the example code
3. Click 'Send'.
4. 401 response is shown, but nothing happens in regards of the test.

Expected behaviour: Show that the test failed. (As 'variable' !== 'value')

System: Chome 80 installed PWA with browser extension.

**Comment by liyasthomas** [comment]
Please explain steps to reproduce the issue
