### ISSUE TITLE
Running app from downloaded zip fails to compile

### ISSUE THREAD

**Issue by MuckT** [liyasthomas/postwoman#651]
**Reproduction Steps:**

1. Download the zip form github
2. Extract the contents
3. Navigate to the folder
4. run npm install
5. npm run dev

**Expected Results:**

- Application Runs

**Actual Results:**

- Build Error:

```
 ERROR  Failed to compile with 1 errors                                                       friendly-errors 09:26:41

This relative module was not found:                                                           friendly-errors 09:26:41
                                                                                              friendly-errors 09:26:41
* ../../.postwoman/version.json in ./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./components/layout/footer.vue?vue&type=script&lang=js&
i Waiting for file changes                                                                                    09:26:41
i Memory usage: 257 MB (RSS: 454 MB)                                                                          09:26:41
```
**Work around:**

- Cloning the repository is working fine.

**Comment by liyasthomas** [comment]
#327 #444

**Comment by MuckT** [comment]
Possible root cause of this issue:

> When you download the repo, you just download the source files of the most recent commit of the default branch without the .git folder. Essentially, when you download you can’t make use of any git commands, you can’t view the commit messages, you are just not using git at all. [source](https://www.ajonit.com/git/git-clone/)
