### ISSUE TITLE
An unknown error occurred whilst the proxy was processing your request.

### ISSUE THREAD

**Issue by Byron4j** [liyasthomas/postwoman#656]
When I use postwoman to access local tomcat server: http://localhost:8080，and enable proxy；
I get a 500 error， and tips like :  An unknown error occurred whilst the proxy was processing your request.
![image](https://user-images.githubusercontent.com/18253211/76166004-3d521680-6196-11ea-95d4-504e91844faa.png)

**Comment by AndrewBastin** [comment]
@NBTX

**Comment by AndrewBastin** [comment]
Umm, I just now read the issue description fully 😅 

The proxy cannot connect to local servers. Please use the Postwoman browser extensions ([Chrome](https://chrome.google.com/webstore/detail/postwoman-extension-for-c/amknoiejhlmhancpahfcfcfhllgkpbld) or [Firefox](https://addons.mozilla.org/en-US/firefox/addon/postwoman/)) to be able to send requests to local servers.


Thanks for trying Postwoman! 😄

**Comment by gasbi** [comment]
I'm experiencing the same problem, and is certainly when trying to connect to localhost.

I have proxy enabled and chrome extension installed, and still getting the same error:
```
{  "success": false,  "data": {    "message": "An unknown error occurred whilst the proxy was processing your request."  }}
```

Am I missing something here to be able to connect to localhost?

Thanks!!

**Comment by AndrewBastin** [comment]
Well, the Proxy cannot talk to your local server because the proxy is in the internet and your local server isn't 😅 . Use the browser extension with the proxy disabled to access your local server.

Cheers! 😄

**Comment by AndrewBastin** [comment]
> I'm experiencing the same problem, and is certainly when trying to connect to localhost.
> 
> I have proxy enabled and chrome extension installed, and still getting the same error:
> 
> ```
> {  "success": false,  "data": {    "message": "An unknown error occurred whilst the proxy was processing your request."  }}
> ```
> 
> Am I missing something here to be able to connect to localhost?
> 
> Thanks!!

@NBTX is the proxy supposed to a message like this on failing to resolve a url, can we like get a proper axios like error thingy with error codes and stuff maybe ?

**Comment by AndrewBastin** [comment]
If the issue persists, feel free to message below.

Closing the issue meanwhile.
