### ISSUE TITLE
Last added history entry is removed automatically after refresh

### ISSUE THREAD

**Issue by liyasthomas** [liyasthomas/postwoman#66]
**Describe the bug**
Entries are added to history[] but after refresh, the last added entry were automatically removed.

**To Reproduce**
1. Send a mock request
2. History entry will be added to history section
3. Refresh the page
4. Last added history entry automatically removed
5. Further refresh won't remove entries though

**Expected behavior**
History shouldn't be removed

**Additional context**

**Comment by liyasthomas** [comment]
@izerozlu could you please double check #59 because I think this PR introduced this error.

**Comment by izerozlu** [comment]
@liyasthomas Will check as soon as possible.

**Comment by liyasthomas** [comment]
#67 fixes this hence closing

**Comment by liyasthomas** [comment]
@all-contributors please add @izerozlu for code
