### ISSUE TITLE
[Bug] - Can't login to Github and Google

### ISSUE THREAD

**Issue by Olyno** [liyasthomas/postwoman#661]
**Describe the bug**
Using PWA or just the website, with cookies available, postwoman can't log me using Github connection method. 

**To Reproduce**
1. Go to the key icon top right
2. Click on it to deploy connections methods
3. Click on Github
4. The popup opens and closes itself instantly, without get any connection

**Expected behavior**
Be connected using Google or Github

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Vivaldi (chromium based)
 - Version 2.11.1811.47

**Comment by liyasthomas** [comment]
This is clearly an issue with Browser itself.
