### ISSUE TITLE
Error: Network Error. Check console for details.

### ISSUE THREAD

**Issue by wuyish** [liyasthomas/postwoman#673]
![run](https://user-images.githubusercontent.com/1539167/76680076-a4e9e500-6620-11ea-909a-2932f63ca732.gif)
When sended "get url https://www.qq.com",response:**Error: Network Error. Check console for details.**
But it was normal when enabled official proxy.
![test](https://user-images.githubusercontent.com/1539167/76680086-b92de200-6620-11ea-8919-d3d48c47a55b.gif)

I think it wasn't have to enable the proxy,I just used the postwoman as a client.

**Comment by liyasthomas** [comment]
@wuyish please tell how to reproduce the issue.

**Comment by wuyish** [comment]
> @wuyish please tell how to reproduce the issue.
I tried again，but it didn't work when enabled the proxy  now.

**Comment by liyasthomas** [comment]
The mentioned endpoint: `www.qq.com` seems to be blocking requests from https://postwoman.io

For these kinda situations, we implemented Proxy. Enable Proxy to intercept such request endpoints.
