### ISSUE TITLE
Looking forward to    that  the postwoman Compatible 'swagger ' at next version  

### ISSUE THREAD

**Issue by liuyang001** [liyasthomas/postwoman#675]
1

**Comment by liyasthomas** [comment]
Hiya!

Due to the current corona crisis, development and next major version release PW is postponed until further notice. Please stay indoors, stay safe.

**Comment by liyasthomas** [comment]
I just ran few swagger endpoints (`https://petstore.swagger.io/v2/store/inventory`) and it seem to be working fine.

What we're lacking is an UI for selecting requests from swagger Definition file (`https://petstore.swagger.io/v2/swagger.json`)
