### ISSUE TITLE
[bug] - Can't make a request to HTTP

### ISSUE THREAD

**Issue by Olyno** [liyasthomas/postwoman#676]
**Describe the bug**

When trying a request to a link with no http**s**, it throws this error:
```
Mixed Content: The page at 'https://postwoman.io/?method=GET&url=http://edu2.shareyourtime.fr&path=/apijs/messages&rawParams=%7B%7D' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://edu2.shareyourtime.fr/apijs/messages'. This request has been blocked; the content must be served over HTTPS.
```

**To Reproduce**
1. Try to make a request to ``http://edu2.shareyourtime.fr/apijs/messages``
2. Press F12 and See console

**Expected behavior**

Get result of request.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Vivaldi (chromium based)
 - Version 2.11.1811.47

**Additional context**

Tested on Firefox Developer edition too.

**Comment by Olyno** [comment]
To note: I tested with Postman, it works fine. Should be able to work with Postwoman too.

**Comment by liyasthomas** [comment]
Enable proxy to access `non-https` endpoints.
