### ISSUE TITLE
Save collections on account sync turn on

### ISSUE THREAD

**Issue by leomp12** [liyasthomas/postwoman#679]
**Describe the bug**
Already saved collections are not uploaded on sync turn on.

**To Reproduce**
1. Save some request to collection;
2. Login first time;
3. Go to _Settings_;
4. Click to turn on sync;
5. Login again in another browser or private tab;
6. Saved collection will not be there;

**Expected behavior**
Upload the collection :stuck_out_tongue_closed_eyes: 

**Screenshots**
![Screenshot_2020-03-17 Postwoman • A free, fast and beautiful API request builder](https://user-images.githubusercontent.com/10326572/76875160-f081d600-684e-11ea-9fbd-0a533f587160.png)
![Screenshot_2020-03-17 Postwoman • A free, fast and beautiful API request builder(1)](https://user-images.githubusercontent.com/10326572/76874927-9b45c480-684e-11ea-83da-bee2c29b49f6.png)

**Desktop (please complete the following information):**
 - OS: Linux 5.5.9-arch1-2 (Arch Linux)
 - Browser: Firefox
 - Version: 74.0 (64-bit)

**Additional context**
N/A

**Comment by liyasthomas** [comment]
Currently, collections are uploaded whenever a change (such as adding/deleting/moving/renaming a request or colection) happens in the Collections sections.

**Comment by leomp12** [comment]
@liyasthomas yup, but you don't think it should be uploaded when sync is toggled?

**Comment by liyasthomas** [comment]
yes indeed. Should be synced on toggle.

**Comment by rizkyarlin** [comment]
If I may ask, where does postwoman store the collection for syncing purposes?

**Comment by leomp12** [comment]
@rizkyarlin Firestore I think, take a look here https://github.com/liyasthomas/postwoman/blob/master/functions/fb.js

**Comment by liyasthomas** [comment]
Fixed on #854
