### ISSUE TITLE
Docs request: how to prevent secrets from leaving local storage wrt. sync.

### ISSUE THREAD

**Issue by neverendingqs** [liyasthomas/postwoman#686]
**Is your feature request related to a problem? Please describe.**
I am not sure how I should set up sync to prevent secrets (e.g. OAuth 2.0 access tokens) from leaving local storage.

**Describe the solution you'd like**
Help text or documentation describing what exactly is synced and/or suggestions for how to manage secrets and syncing.

**Describe alternatives you've considered**
I think using Environments to store secrets and referencing them in request collections might be the way to go?

**Additional context**
N/A

**Comment by liyasthomas** [comment]
Synced sections are:
- History
- Collections
- Environments
- Notes

Secrets including 0Auth key or access tokens are synced with `localStorage` only.

**Comment by sachaventura2** [comment]
Hi there,

What are the best practices to store API keys, passwords etc. in Team collections?
Coming from Postman, we usually store them in the environment, as "current values" which are only stored locally.
> Secrets including 0Auth key or access tokens are synced with localStorage only.
How are 0Auth keys and access token identified as such?

Thanks for clarifying!

**Comment by dakujem** [comment]
This should not have been closed. There are values we **never** want to save anywhere, neither sync. So how do we do this? I'm searching like crazy, but can't find anything.

Trivial example: I want to authenticate to an API, but I do not wish to store/sync the credentials anywhere. How to?

@liyasthomas Thanks.
