### ISSUE TITLE
Report Portal integration

### ISSUE THREAD

**Issue by deepakbandela** [liyasthomas/postwoman#691]
**Is your feature request related to a problem? Please describe.**
I would like to see integration with the report portal (reportportal.io) when I run the tests on my postwoman.

**Describe the solution you'd like**
Customising the existing report portal agents to postwoman so that they will be able to report all the tests ran in PW

**Describe alternatives you've considered**
No alternatives yet for this feature.

**Additional context**
I want to have a test runner in PW similar to Postman and once the tests are run we should show them in report portal. 

Is there a plan to do so in future?

**Comment by liyasthomas** [comment]
Currently we've post-request hooks in which tests are carried out within the request section.

As of now, we do not have a plan to support 3rd party interrogations.
