### ISSUE TITLE
Support preview of JSON:API's "application/vnd.api+json" Content-Type

### ISSUE THREAD

**Issue by allthesignals** [liyasthomas/postwoman#694]
**Describe the bug**
When I issue a GET request to an endpoint responding with the [content type "application/vnd.api+json"](https://jsonapi.org/format/#content-negotiation-clients), I see a 200 success response, but the reponse field is blank (see screenshot).

When I click "copy response", and paste the value in a text editor, I see:

`[object Object]`

This leads me to believe that it isn't recognizing this particular content-type and doesn't know to parse it as JSON? Just a guess.

I've alluded to this in this issue: https://github.com/liyasthomas/postwoman/issues/634.

I believe other similar tools are able to recognize this.

**To Reproduce**
1. Make a request to a JSON API having a `application/vnd.api+json` Content-Type
2. Scroll down
3. Response body is blank but request is 200 okay.

**Screenshots**
![image](https://user-images.githubusercontent.com/5004319/77215667-d0bb0e00-6aeb-11ea-889b-868835a87daa.png)

**Desktop (please complete the following information):**
 - OS: Catalina
 - Browser Chrome
 - Version v1.9.0

**Additional context**

**Comment by AndrewBastin** [comment]
Thanks for opening the issue!

We will get into fixing that right away!

**Comment by allthesignals** [comment]
You bet! I'm taking a look right now fwiw...
