### ISSUE TITLE
[UI/UX] - Change place of Send button

### ISSUE THREAD

**Issue by Olyno** [liyasthomas/postwoman#696]
**Is your feature request related to a problem? Please describe.**

Sometimes, I need to do again the same request to see if my server receives this request, and to continue to work. Currently, ``send`` button has a big issue when we scroll down: it hiddes other buttons on the right side top right (see screen below).

**Describe the solution you'd like**

We could simply move it from right side top right to right side bottom right, like this: ![Demonstration image](https://i.imgur.com/GSrfz5u.png)

**Describe alternatives you've considered**

I was thinking about middle side bottom, it could work too. Anyway, the best place should be at the bottom and not the top when we scroll down.

**Additional context**

/

**Comment by liyasthomas** [comment]
If we place the end button at bottom, the toasts will overlaps it in mobile view :(

**Comment by Olyno** [comment]
We can put the button just here (see image below). User can scroll down a little more to show button, without toasts overlap it
![](https://i.imgur.com/MFK926c.png)

So the send button could be at the right side top, it should fix the main issue which is the overlap of the navigation bar at the right side.

**Comment by liyasthomas** [comment]
![localhost_3000_](https://user-images.githubusercontent.com/10395817/77240142-88454280-6c08-11ea-9bc8-2479b3a43127.png)
 
send button being positioned fixed for easy access, we should align it horizontally center to view port. Lemme find a workaround on it.
