### ISSUE TITLE
Broken "proxy privacy policy" link

### ISSUE THREAD

**Issue by Aswathprabhu** [liyasthomas/postwoman#699]
The link for Apollo Software private policy is a bad link.

**To Reproduce**
1. Go to 'settings'
2. Scroll down to 'Proxy module'
3. Click on 'Apollo Software privacy policy'

**Expected behavior**
A redirection to a valid link.

**Screenshots**
<img width="1336" alt="image" src="https://user-images.githubusercontent.com/25875367/77295398-e60e8300-6d0b-11ea-97d9-323a09624e01.png">

**Desktop**
 - OS: Mac OS Catalina
 - Browser Chrome
 - Version 80

**Comment by liyasthomas** [comment]
Will update ASAP.  Thanks for noticing that.

**Comment by liyasthomas** [comment]
@NBTX It seems like the server is down :(

**Comment by dmitryyankowski** [comment]
We should really consider deploying our own proxy to either Netlify or Cloudflare Workers. We've had alot of issues thus far with proxy stuff 🤔
