### ISSUE TITLE
Why da fuq is your name plastered all over the README?

### ISSUE THREAD

**Issue by wle8300** [liyasthomas/postwoman#70]
I get it. You're a special person but if you wanna seem like a normal person try to limit posting your name and "personal branding" all over the README.

**Comment by izerozlu** [comment]
That's just toxic talking. Unrelated and not even creates a proper discussion.

Projects like these doesn't need this kind of behavior.

**Comment by NBTX** [comment]
Well I suppose now we know why you don't put your name on the front page of your projects...
