### ISSUE TITLE
Add a description to the request or collection when saving it

### ISSUE THREAD

**Issue by taksumaki** [liyasthomas/postwoman#706]
**Is your feature request related to a problem? Please describe.**
It would solve the problem of better understanding what "X" request or "X" collection does by adding a description of what it does and what it is for.

**Describe the solution you'd like**
Add a "Description" field in the save request or collection form and thus be able to determine in a better way what each thing does.

**Describe alternatives you've considered**
In the "Save" form add a field that says description and be able to assign one to the request or collection when saving. And to see that description you can see a Toolip when you mouse over the title of the request or collection and to see the description in full by right-clicking on the title and saying "View description" or reusing the 3-point menu which is next to the title with an option called "See description".

**Additional context**
In context, add a description field when saving a request or collection and be able to see it by pressing the menu option "See description" of the 3-point menu that is next to the title of the collection or request.

**Comment by liyasthomas** [comment]
You can label a request. To distinguish multiple requests, please consider assigning relevant name to requests and collections.
