### ISSUE TITLE
CORS issue when hosting

### ISSUE THREAD

**Issue by phantompepper** [liyasthomas/postwoman#707]
Hello! I have been working on a project that uses Postwoman, and while working local, using the proxy works fine. However, when hosting, i am unable to use the proxy. I get this notorious error:

```Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://postwoman.apollosoftware.xyz/. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).```

**Comment by liyasthomas** [comment]
Proxy mode is only available for Official https://postwoman.io domain. You'll have to host your own server for proxy.
