### ISSUE TITLE
Postwoman raiase a connection error when communicate with localhost.

### ISSUE THREAD

**Issue by CodeMokee** [liyasthomas/postwoman#708]
**Description**
Console print an "net::ERR_CONNECTION_REFUSED" when I try to access my nginx welcome page on my localhost.  But the interface work nomarly request by chrome or postman.

**Reproduce**
1. Start nginx service on my local env, and welcome page could be access by chrome and postman. url: http://localhost:80 
Get the welcome page: 
![image](https://user-images.githubusercontent.com/23649645/77601925-1c841200-6f47-11ea-8625-dc0273a738c8.png)

2. Open the same page on the postwomen. 
request the same api by postwomen. 
![image](https://user-images.githubusercontent.com/23649645/77601996-43424880-6f47-11ea-9f16-ececc928a264.png)

**Expected behavior**
the response is show correctly.

**Screenshots**
network on the developer tools: 
![image](https://user-images.githubusercontent.com/23649645/77602406-5efa1e80-6f48-11ea-808c-e8edf291c8d3.png)

![image](https://user-images.githubusercontent.com/23649645/77602356-3bcf6f00-6f48-11ea-8872-04693e57db30.png)

**Desktop (please complete the following information):**
 - OS: windows 10 
 - Browser： chrome 
 - Version  80.0.3987.149 (Official Build) (64-bit)

**Additional context**
Tips: Fisrt time I meet this issue when I debug my vert.x api by postwomen. and I found this connection error. But the service log show reciew the request. So  I think the issue may raised when postwomen to process the response.

**Comment by liyasthomas** [comment]
https://github.com/liyasthomas/postwoman/issues/704#issuecomment-603219828

**Comment by liuxueyiTest** [comment]
![image](https://user-images.githubusercontent.com/75476346/101156513-ae5e2600-3663-11eb-994a-1a93a4750673.png)

**Comment by liyasthomas** [comment]
Install browser extension. Links are in README.
