### ISSUE TITLE
Not working on Brave Browser anymore

### ISSUE THREAD

**Issue by guastallaigor** [liyasthomas/postwoman#71]
**Describe the bug**
When the project was released, I was using it on [Brave](https://brave.com/) and everything was fine. The code right now is very different from before, but is not working anymore.
I know that this is a small project, but I'm just opening this issue because it was working before and now it isn't, maybe it's just a small fix that someone can do it :)

The error message that is showing in the console is:

```js
TypeError: Cannot read property 'className' of undefined
```

**To Reproduce**
Open https://liyasthomas.github.io/postwoman/ on a up to date Brave Browser.

**Expected behavior**
It should work like Chrome, because for me it's still working on Chrome.

**Screenshots**
![image](https://user-images.githubusercontent.com/22016005/63808543-94795380-c8f6-11e9-83ec-9c9594ff0aec.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 or Window 10
 - Browser Brave 
 - Version 0.68.131 Chromium: 76.0.3809.100 (Official Build) (64-bit)

**Additional context**
If you don't want to support Brave you can close this issue, no problem, I can still use it on Chrome.

**Comment by izerozlu** [comment]
That problem is not about the brave browser.

It's a common bug right now. It'll be fixed soon.

Thanks for the heads up!

**Comment by izerozlu** [comment]
I'll try to create the required PR tomorrow.

**Comment by liyasthomas** [comment]
@guastallaigor have you tried to clear the cache perhaps history data too and try again?

**Comment by NBTX** [comment]
I cannot reproduce this issue.

- OS: Windows 10 (1709)
- Browser: Brave
- Version 0.68.131 Chromium: 76.0.3809.100 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/43181178/63811277-eb931e80-c91e-11e9-9f32-b880cbf1a600.png)

Have you installed the PWA or got any cached copies?
Try going to Developer Tools -> (might need to click the double right chevron ») Application tab -> Service Workers -> Unregister and reload the page.
