### ISSUE TITLE
Provide post-build resources and default setting files

### ISSUE THREAD

**Issue by cn-src** [liyasthomas/postwoman#714]
1. Provide pure static resources to facilitate rapid deployment.
2. Provide a settings file to initialize the default settings. such as: settings.json
3. Support import from with url.

**Comment by liyasthomas** [comment]
1. Please go through the README.md to view how to [develop](https://github.com/liyasthomas/postwoman/blob/master/README.md#developing-) and [build](https://github.com/liyasthomas/postwoman/blob/master/README.md#releasing-%EF%B8%8F) the project.
2. As of now, there's no strictly dependent environment variables. Feel free to edit `nuxt.config.js` for global variables and environment variables
3. (I didn't get what you meant by "Import from URL".)

**Comment by cn-src** [comment]
1. If there are pure static resources, it is convenient to deploy postwoman offline for people who are not familiar with node.js technology.

2. "settings" refers to the postwoman's ui settings.A default settings.json file can change the default appearance during pure static deployment.

3. "Import from with URL",  "Postwoman -> Collections -> Import " function.

Forgive me for bad english.

**Comment by cn-src** [comment]
Because postwoman only needs pure static resources to deploy, I want to package it into a jar file, just like "webjars". It can be easily integrated with java web projects.

**Comment by liyasthomas** [comment]
Will think about this and add to our roadmap. Feel free to contribute 🙌

**Comment by dmitryyankowski** [comment]
If only we used NextJS instead of Nuxt 😅

**Comment by liyasthomas** [comment]
Oh! I guess there's such a `settings.json` on NextJS right? Sounds exciting. I'll look into it and see if there's any available implementations

**Comment by liyasthomas** [comment]
I afraid default settings file is not supported by Nuxt.
For static build files, kindly follow instructions in README.
Importing Collections from URL has been added to future development road map.
