### ISSUE TITLE
Add docker Images for all Tags

### ISSUE THREAD

**Issue by JanoschDeurer** [liyasthomas/postwoman#722]
**Is your feature request related to a problem? Please describe.**
I try to always use version pinning in docker-compose for all docker images. This ensures that when a problem occurs I can go back by playing back my backup.

**Describe the solution you'd like**
It would be great to have docker tags for all the git tags.

**Comment by liyasthomas** [comment]
@JanoschDeurer I'm a noob at docker stuffs. Can you help me resolve this issue?

**Comment by JanoschDeurer** [comment]
Yes, gladly, actually Dockerhub has a rather nice integration for this. If you click on your Docker repository and then on the `Builds` tab you can click on `Configure Automated Builds`. In the section for Build Rules you can configure additional rules. In your case the rule would be:

- Source Type: `Tag`
- Source: `/^v[0-9.]+$/`
- Docker Tag: `{sourceref}`
- Dockerfile location: `Dockerfile`
- Build context: `/`
- Autobuild: true
- Build Caching: true

It will the build automatically when a new tag is pushed that matches the regex in Source. For the existing tags it will not run a build.

**Comment by liyasthomas** [comment]
Done! Thanks for the help.

**Comment by JanoschDeurer** [comment]
Nice, thanks :) If you ever need any other help with Docker just let me know.
