### ISSUE TITLE
Getting cannot read value of undefined

### ISSUE THREAD

**Issue by aashutoshrathi** [liyasthomas/postwoman#731]
**Describe the bug**
All my request imported from cURL are getting this error 
![image](https://user-images.githubusercontent.com/21199234/78327482-9dbc5400-759a-11ea-912f-484d2fbcd12f.png)

**To Reproduce**
1. Click on import from cURL
2. import a get curl
3. send request

**Expected behavior**
The request should be sent as the curl is valid.

**Screenshots**
Added above

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Browser: Chrome
 - Version: 80.0.3987.149

**Comment by liyasthomas** [comment]
@aashutoshrathi Can you please share the masked cURL to reproduce the bug at our side.

**Comment by aashutoshrathi** [comment]
Sure.
```sh
curl -X GET "http://localhost:4242/people/search?type=HUMAN&queryString=a" 
-H "accept: application/json" 
-H "access-token: some-access-token" 
-H "firm: someFirm" -H "user: admin"
```

Also, @liyasthomas I tried on Chrome as well as PWA.

**Comment by liyasthomas** [comment]
Make sure you've installed Browser Extension to access `localhost` endpoints.

**Comment by aashutoshrathi** [comment]
Yeah. It worked.

**Comment by AndrewBastin** [comment]
@liyasthomas even if this is a browser extension issue, the app shouldn't be doing that.

Definitely a bug.

**Comment by liyasthomas** [comment]
@AndrewBastin yes, you're right. reopening issue to track it.

**Comment by liyasthomas** [comment]
@aashutoshrathi can you please explain in which instance/action you had the mentioned console errors as in the screenshot.

**Comment by aashutoshrathi** [comment]
The cURL above was not working, but some other cURL worked later.
Also, the import isn't working properly for me, the URL doesn't change for some reason.

![2020-04-04 11 24 49](https://user-images.githubusercontent.com/21199234/78419831-2274a400-7667-11ea-86e3-06b38f5a3d06.gif)

**Comment by diego-vergara** [comment]
Hi, I get this error when I logged with Github, the request was correct, if I log out works fine.
PS: I'm not sure if is the same error.

![image](https://user-images.githubusercontent.com/16439985/81487511-a81ddd80-922b-11ea-8a8e-478ff2c5749e.png)

**Comment by liyasthomas** [comment]
@diego-vergara 

Well, I can't reproduce the issue at my end. Possible reason for this issue may be a cached build in localstorage.

**Try uninstalling service worker**
Goto Developer Tools (F12) > (might need to click the double right chevron ») Application tab > Service Workers > Unregister and reload the page.

If the issue is still persisting, try clearing app data. Notice: This clears all local synced History, Collections and Environments.
Goto Developer Tools (F12) > Application tab > Clear storage sidebar > Clear site data and reload the page.

**Comment by liyasthomas** [comment]
I've pushed a hotfix, please let me know if the issue still persist.
