### ISSUE TITLE
Broken link to translations branch

### ISSUE THREAD

**Issue by gugacavalieri** [liyasthomas/postwoman#737]
**Describe the bug**
* The link to the translations branch is broken on Readme
* Is there still a translations branch? How can people contribute with translations?

**To Reproduce**
1. Go to [https://github.com/liyasthomas/postwoman/blob/master/README.md](https://github.com/liyasthomas/postwoman/blob/master/README.md)
2. Click on the link that says: **All i18n contributions are welcome to i18n [branch](https://github.com/liyasthomas/postwoman/tree/i18n) only!**
3. See error (404)

**Expected behavior**
I was wondering if the translation branch was deprecated.

**Screenshots**
![image](https://user-images.githubusercontent.com/4624484/78453592-1f7ab300-7669-11ea-8950-c69fca6b1fba.png)

**Desktop (please complete the following information):**
 - OS: Fedora 31
 - Google Chrome
 - Version 79.0.3945.130 (Official Build) (64-bit)

**Comment by liyasthomas** [comment]
Hi there, sorry for the broken link. Fixed it.

**Comment by gugacavalieri** [comment]
Thanks @liyasthomas ! :+1:

**Comment by liyasthomas** [comment]
Not protected at all. Can't you make the PR?

**Comment by gugacavalieri** [comment]
actually you can do it only if you are one of the `admins` of the repo by going to `Settings > Branches`.

Here is the full guide:
[https://help.github.com/en/enterprise/2.15/admin/developer-workflow/configuring-protected-branches-and-required-status-checks](https://help.github.com/en/enterprise/2.15/admin/developer-workflow/configuring-protected-branches-and-required-status-checks)

:smile:

**Comment by liyasthomas** [comment]
yes it is. You can make the PR to `i18n` branch.

**Comment by gugacavalieri** [comment]
ah, cool! I will try then! Thanks @liyasthomas :+1:
