### ISSUE TITLE
App is broken with old history in localStorage

### ISSUE THREAD

**Issue by nickpalenchar** [liyasthomas/postwoman#74]
**Describe the bug**
Starting after [`271bd06`](https://github.com/liyasthomas/postwoman/commit/271bd061765f1d2d065aac8cf2b82a36d8e68117) (or perhaps around then), old localStorage from a user agent causes the app to break when navigating to the app.

**To Reproduce**
1. Open the browser and open devTools
2. Go to the tab for storage, click on localstorage
3. Edit the history section to be `[{"time":"2:57:54 PM","method":"POST","url":"https://reqres.in","path":"/api/users"},{"time":"2:56:30 PM","method":"GET","url":"https://reqres.in","path":"/api/users"},{"time":"10:33:28 AM","method":"GET","url":"https://reqres.in","path":"/api/users"}]`
4. Go to the postwoman page to get the app to break

**Expected behavior**
The app should fully load, any old history that can't be deciphered should be displayed with as much information as possible.

**Desktop (please complete the following information):**
 - OS: Mac OS Sierra
 - Browser: Firefox
 - Version 68.0 (64-bit)

**Comment by liyasthomas** [comment]
I suspect this is the reason for few other issues that have reported and solved on flushing cache and local storage 🤔

Btw, these kinda people (@nickpalenchar) are 💎

**Comment by liyasthomas** [comment]
@all-contributors please add @nickpalenchar for code
