### ISSUE TITLE
Add GraphQL syntax highlighting

### ISSUE THREAD

**Issue by danilofuchs** [liyasthomas/postwoman#741]
**Is your feature request related to a problem? Please describe.**

GraphQL view does not have any syntax highlighting on queries

![image](https://user-images.githubusercontent.com/17657014/78503032-8f0ca300-773a-11ea-9d0a-cfe0161432a3.png)

**Describe the solution you'd like**

Something like GraphiQL or other editors have

![image](https://user-images.githubusercontent.com/17657014/78503095-e3b01e00-773a-11ea-9bc6-cbf681b8d39c.png)

**Describe alternatives you've considered**

Considering Postwoman already uses `graphql-language-service-interface`, maybe it's possible to extract tokens from there.

**Comment by AndrewBastin** [comment]
Ace Editor (which powers Postwoman's code editors) doesn't come with a graphql query highlighting mode, hence the query editor just used the json mode to get as much similar editor characteristics down as possible.

I am looking into implementing a editor mode for it myself.


Thanks for opening the issue  ^_^

**Comment by danilofuchs** [comment]
Maybe these help:
https://github.com/ajaxorg/ace/blob/master/lib/ace/mode/graphqlschema.js
https://github.com/ajaxorg/ace/blob/master/lib/ace/mode/graphqlschema_highlight_rules.js

**Comment by levrik** [comment]
@AndrewBastin @liyasthomas I just wonder if integrating https://github.com/microsoft/monaco-editor, the editor component that powers VS Code, would be also an idea. I think it has by far better support for stuff like this. If this sounds interesting to you, I'm also willing to work on a PR and/or do some research on this.

**Comment by AndrewBastin** [comment]
@levrik Yes, I have indeed thought about Monaco. We could get it implemented, which is fine, but the problem is that Monaco doesn't work on mobile devices. Which I am not really sure about with going through with.
