### ISSUE TITLE
Improve documentation on how to use environments

### ISSUE THREAD

**Issue by danilofuchs** [liyasthomas/postwoman#742]
**Is your feature request related to a problem? Please describe.**

Immediately after opening Postwoman and adding Environments, it is not clear how I should reference them in my requests.

Can I use `{{ variable_name }}`? 

**Describe the solution you'd like**

Postman has [great documentation about it](https://learning.postman.com/docs/postman/variables-and-environments/variables/).

I think the Wiki needs to have a section about Environments and the app should have some tooltips or indications as to how one should use environments.

**Comment by liyasthomas** [comment]
Sorry for the incomplete Wiki. We're working on it.
By the way, here's the Wiki regarding Pre-request scripts and environments: https://github.com/liyasthomas/postwoman/wiki/Pre-Request-Scripts
 This link is visible on pre-request script section.

Feel free to contribute to Wiki if you find any issues.
