### ISSUE TITLE
I used it to post test,but response network error 

### ISSUE THREAD

**Issue by flystarfly** [liyasthomas/postwoman#750]
![image](https://user-images.githubusercontent.com/20432934/78964965-3ff5b200-7b2e-11ea-90ba-c2c0b5659721.png)
![image](https://user-images.githubusercontent.com/20432934/78964977-4a17b080-7b2e-11ea-9da8-fa4e7f949dbe.png)
I use same way in postman to test api, and it worked. but I try to send request by postwoman. it reponsed newwork error! why

**Comment by liyasthomas** [comment]
To test endpoints in `localhost`, install browser extension. Links can be found in readme.

**Comment by flystarfly** [comment]
I hava  installed,browser extension,andI also open use the browser extension in Settings. but it's response network error too.

**Comment by fxk2006** [comment]
me too...
