### ISSUE TITLE
Request headers kept same after changing request type

### ISSUE THREAD

**Issue by bilencekic** [liyasthomas/postwoman#752]
**Describe the bug**
I have 2 request get and post. GET is using X-CSRF-TOKEN =  FETCH parameter to get token from server and POST is using X-CSRF-TOKEN = <TOKEN_VALUE> .
Due to header values kept same, i can't have GET and POST with different parameters, i need to change manually everytime.

**To Reproduce**
1. Go to URL bar and simply call a GET request with a custom header
2. Save the request.
3. change request to POST
4. See the request header is still same and cannot have different request header between requests.

**Expected behavior**
Headers should be belong to each saved request and should be cleared for each request type.

**Comment by liyasthomas** [comment]
The current state is preserved for easy reference to request configuration. Please manually save the `GET` and `POST` request once and click the saved request to restore it.

**Comment by bilencekic** [comment]
Sorry i think my bad. After saving parameters, i noticed parameters were kept same but it was a glitch i think. I can save request with different header parameters now (somehow strange).
Thanks
