### ISSUE TITLE
Option to Copy request as Fetch or XHR Or CURL 

### ISSUE THREAD

**Issue by edisonaugusthy** [liyasthomas/postwoman#76]
**Is your feature request related to a problem? Please describe.**
Please Provide a way to copy the request as Fetch/XHR/CURL
 this link may help [https://github.com/postmanlabs/postman-code-generators](postman-code-generators)

**Comment by liyasthomas** [comment]
Some references for me to remember while considering this issue:
- NuxtJS HTTP Module https://http.nuxtjs.org
- Axios https://axios.nuxtjs.org

**Comment by edisonaugusthy** [comment]
@liyasthomas  am not requesting for HTTP request with different library #61 
am expecting a feature to Copy The current request code snippet as fetch or XHR and directly use in the application 
EG:
![image](https://user-images.githubusercontent.com/22213856/63853984-b2f45300-c9b9-11e9-8976-e6af683436ea.png)

**Comment by liyasthomas** [comment]
Oh I get it! Option to generate code snippets of current request on fetch/XHR/CURL

**Comment by jgroom33** [comment]
Possible implementation option:
Convert to curl. 
Then use this: https://github.com/NickCarneiro/curlconverter

**Comment by JacobAnavisca** [comment]
Created a pull for this https://github.com/liyasthomas/postwoman/pull/132 it may not be the best way to do this but I'd be glad to rework this.

**Comment by liyasthomas** [comment]
#132 solved this hence closing
