### ISSUE TITLE
Mobile responsiveness issues

### ISSUE THREAD

**Issue by yoav-lavi** [liyasthomas/postwoman#760]
- On iPhone XS Max both on Safari and the PWA, the notes button and the end of the history view are outside the viewport width, expanding the view and adding horizontal scroll. See [here](https://imgur.com/F18xrhR)

**Comment by liyasthomas** [comment]
Thanks for reporting the issue. Will look into it ASAP.

**Comment by yoav-lavi** [comment]
I'm seeing that the accordion buttons look the same on desktop so that specifically is probably not an issue
