### ISSUE TITLE
Request : Copy response headers

### ISSUE THREAD

**Issue by rdhar** [liyasthomas/postwoman#763]
**Is your feature request related to a problem? Please describe.**
Honestly, not really a problem as much as an improvement suggestion. Love this project and the ease-of-use brought about by it!

**Describe the solution you'd like**
Often, I compare response headers of different requests. Despite the clear display of headers information, there's no way to select all of the data together, let alone copy it to clipboard to paste and compare elsewhere. A button like "Copy response" for response headers would be ideal.

**Describe alternatives you've considered**
None that I'm currently aware of, beyond constantly switching between windows and copying one field at a time.

**Additional context**
Hopefully, I'm not the only who cares about copy-pasting headers. Please feel free to let me know if you'd like any more information I can help provide. Thanks for your time!

I'm using Chrome v81 on Windows 10 v1903.

**Comment by liyasthomas** [comment]
There's already a "copy response" button that lets you to copy the entire response to clipboard, alog with download as `JSON`. If you insist, we can add a seperate _copy button for headers_ even though it doesn't seems like an enhancement.

![Screenshot_20200412-230709](https://user-images.githubusercontent.com/10395817/79075851-e8fd0200-7d12-11ea-9096-0ac540649abd.png)

**Comment by rdhar** [comment]
Thanks so much for your prompt response, @liyasthomas, I really appreciate it!

That's pretty curious because I don't seem have any of the headers available within the response panel, otherwise this would be complete non-issue. Could this be an API specific thing? For reference, I'm using [PagerDuty API](https://developer.pagerduty.com/api-reference/) and this is what I see:

![image](https://user-images.githubusercontent.com/19497993/79076083-2ea7d380-7cef-11ea-86b6-c0121516b032.png)

**Comment by liyasthomas** [comment]
can you share the endpoint without creds/token so that I could reproduce the issue at my end?

**Comment by rdhar** [comment]
Certainly, I should've shared it earlier: [LINK](https://postwoman.io/?method=GET&url=https://api.pagerduty.com&path=/incidents&headers=%5B%7B%22key%22:%22Accept%22,%22value%22:%22application/vnd.pagerduty+json;version=2%22%7D,%7B%22key%22:%22Authorization%22,%22value%22:%22Token%20token=obfuscated%22%7D,%7B%22key%22:%22%22,%22value%22:%22%22%7D%5D).

The accompanying cURL looks like:
```
curl -X GET 
  'https://api.pagerduty.com/incidents' 
  -H 'Accept: application/vnd.pagerduty+json;version=2' 
  -H 'Authorization: Token token=obfuscated' 
```

Thanks once again for looking into this on my behalf, really grateful for your time (and patience!)

**Comment by liyasthomas** [comment]
Let me look into it. The response data surely plays an important role on how headers and other response fields are displayed. I'll update once I figure out a way to tackle this issue.

**Comment by rdhar** [comment]
Sounds good, just glad I hadn't overlooked a button that does this already!

It is kinda curious that the response headers are [clearly found and parsed by Postwoman](https://postwoman.io/?method=GET&url=https%3A%2F%2Fapi.newrelic.com&path=%2Fv2%2Falerts_events.json&headers=%5B%7B%22key%22%3A%22Accept%22,%22value%22%3A%22application%2Fjson%22%7D,%7B%22key%22%3A%22X-Api-Key%22,%22value%22%3A%22obfuscated%22%7D%5D&params=%5B%7B%22key%22%3A%22%22,%22value%22%3A%22%22%7D%5D) (screenshot attached below), even when they're not shown as part of the response body itself. 

Hence, I do wonder if a separate _Copy headers_ button might add some value to extract the relevant dataset regardless of response body format from various endpoints "standards".

![image](https://user-images.githubusercontent.com/19497993/79077195-8a765a80-7cf7-11ea-9afd-7bbb322b38d2.png)

**Comment by liyasthomas** [comment]
seperate copy button for headers are not required.
