### ISSUE TITLE
Body scroll after modal is open

### ISSUE THREAD

**Issue by nainardev** [liyasthomas/postwoman#766]
**Describe the bug**

**To Reproduce**
1. In mobile
2. Click 3 dots menu
3. Click Shortcuts
4. Now body is scrollable after the modal is open

**Expected behavior**
Scroll should be locked

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by liyasthomas** [comment]
Scroll on "modal opened state" is a good thing.
Allows you to check data on body without closing modal.

**Comment by nainardev** [comment]
Upgrading to vue 3 soon or after its stable release?

**Comment by liyasthomas** [comment]
Hahaha. Only after stable release. And only if it's possible. All our codebase is spaghetti sauce 🤣

**Comment by nainardev** [comment]
Off topic but are to using a ui framework, the design is ❤️

**Comment by liyasthomas** [comment]
No UI frameworks used. Each styles are written by ne ✌️
