### ISSUE TITLE
Add Format Body option

### ISSUE THREAD

**Issue by aashutoshrathi** [liyasthomas/postwoman#767]
**Is your feature request related to a problem? Please describe.**
Generally, the imported cURLs have a body, but the body (mostly in JSON) is not formatted, there should a single button to format the body so that it can be edited easily further.

**Describe the solution you'd like**
I think there should be one button inside the body input box, which onClick prettify body.

**Additional context**
I propose a button like this which on press lints the body

![image](https://user-images.githubusercontent.com/21199234/79136563-d811c680-7dce-11ea-9d72-9ffd760d4074.png)

**Comment by sboulema** [comment]
Added a PR for this:
https://github.com/liyasthomas/postwoman/pull/847
