### ISSUE TITLE
You send data my request to Google 

### ISSUE THREAD

**Issue by skar404** [liyasthomas/postwoman#780]
You send data my request to Google

Is correct  work? 

<img width="1680" alt="Screenshot 2020-04-17 at 00 50 33" src="https://user-images.githubusercontent.com/8483941/79510346-e3baf280-8045-11ea-8778-0ffe02d64d9c.png">

```
{"streamToken":"EAMZEGhCAoH0tbU=","writes":[{"update":{"name":"projects/postwoman-api/databases/(default)/documents/users/a6BknWI6jvOJ4QARGV8PDP7WjWo1/history/5tIpN32M3Q6zNc3vrdF1","fields":{"label":{"stringValue":""},"status":{"integerValue":"200"},"date":{"stringValue":"4/17/2020"},"time":{"stringValue":"12:50:21 AM"},"method":{"stringValue":"POST"},"url":{"stringValue":"http://127.0.0.1:8080"},"path":{"stringValue":"/api/user/auth"},"usesScripts":{"booleanValue":true},"preRequestScript":{"stringValue":"// pw.env.set('variable', 'value');"},"duration":{"integerValue":"35"},"star":{"booleanValue":false}}}}]}
```

OS: Firefox

**Comment by liyasthomas** [comment]
For those enable "sync" feature (only for signed in users), following fields are saved to Firestore database:
- History
- Collections
- Environments
- Notes

Each of these can be toggled on/off from setting > account.
Read, write access is only allowed for authenticated users.
