### ISSUE TITLE
Unresolved merge conflict in index.vue.orig

### ISSUE THREAD

**Issue by Pau1fitz** [liyasthomas/postwoman#786]
https://github.com/liyasthomas/postwoman/blob/05cd1fd0a830d47f5b1b534ccd276bdaea1ca1b2/pages/index.vue.orig#L40

It was added as part of this [PR](https://github.com/liyasthomas/postwoman/pull/603).

**Comment by liyasthomas** [comment]
Thanks for noticing the issue. Actually that file is stale now. Will delete innext commit.
