### ISSUE TITLE
How can I synchronize my data on local?

### ISSUE THREAD

**Issue by kobeumut** [liyasthomas/postwoman#794]
**Describe the bug**
Using local, with cookies available, postwoman can't log me using Github connection method. 

**To Reproduce**
1. Go to the key icon top right
2. Click on it to deploy connections methods
3. Click on Github
4. The popup opens and closes itself instantly, without get any connection

**Expected behavior**
Open github or google auth window

**Desktop (please complete the following information):**
 - OS: Macos Catalina
 - Browser Chrome Dev
 - Version 84.0.4115.5 (Official Build) dev (64-bit)

**Additional context**
Also i tried with Vivaldi, Opera, Safari Browsers.
I am not sure its a bug. Maybe the real question is how can I sync with firebase on my local?

**Comment by liyasthomas** [comment]
sync with Firebase on local development is disabled intentionally to minimise unwanted write / read to Firestore, we're currently operating on free plan :)

When signed out on web app, we sync with `localstorage` and once user signs in, we syncs with Firebase.
In local development, only sync with `localstorage`is available. As we grow further, we'll consider allowing Auth on local development. Thanks for understanding.
