### ISSUE TITLE
The history doesn't show a date with the timestamp.

### ISSUE THREAD

**Issue by iruoy** [liyasthomas/postwoman#81]
**Describe the bug**
The history doesn't show a date with the timestamp.

**To Reproduce**
1. Send a request
2. Send another request a day later
3. Scroll down to History
4. There's no distinction between the 2 entries

**Expected behavior**
A clear representation of when exactly I executed the request.

**Screenshots**
![Screen Shot 2019-08-28 at 13 23 27](https://user-images.githubusercontent.com/5859352/63851792-1faa2600-c997-11e9-88a5-27a2dc3064c2.png)

**Desktop (please complete the following information):**
 - OS: MacOS Mojave 10.14.6
 - Browser: Firefox 68.0.2
 - Version: up-to-date master

**Comment by iruoy** [comment]
I'd like to suggest we show the time since execution.
For example: "23 minutes ago" , "6 hours ago", "2 days ago"

We lose some precision by this, but we can show the actual datetime on hover maybe

**Comment by NBTX** [comment]
We can use moment.js and I think showing the true date/time is a good idea but, to be honest, it's probably not very helpful after more than 5 minutes have passed.

**Comment by izerozlu** [comment]
I'm with the @NBTX on this. Showing date might not be that useful. 
Maybe we can show the date on a `hover`?

**Comment by liyasthomas** [comment]
Confession: It's been 4 years since I've have been using JS, still I Goggle `"get local time in javascript"` :man_facepalming: 

My current implementation is prolly a hacky one.
