### ISSUE TITLE
How to run postwoman under reverse proxy

### ISSUE THREAD

**Issue by IamIpanda** [liyasthomas/postwoman#812]
1. As a service, I hope to run postwoman under https. I use nginx to make https work, what should I set except proxy_pass?
2. Is it possible to run postwoman under subdomain like /postwoman? I found env TRAVIS_REPO_SLUG && DEPLOY_ENV in code, but that is obviously not an official parameter.

**Comment by liyasthomas** [comment]
1. `HTTPS` support is given out of the box. Please host the build directory `dist` to any protocol you want.
2. The current build process make use of environment variables in build config to host in subdomain. For ex: `TRAVIS_REPO_SLUG` is used to host PW in GitHub pages which is available in `your_username.github.io/postwoman`.
