### ISSUE TITLE
Body in Request

### ISSUE THREAD

**Issue by Noorullah-Ahmadzai** [liyasthomas/postwoman#815]
There is no way I could manage to send a body attached to the request for testing RESTFUL API. 
If I want to login, I need to submit an email and password in request body in a Post Request.

**Comment by liyasthomas** [comment]
1. select method type post
2. either choose key-value pair/raw json or formData
3. send request

![pw](https://user-images.githubusercontent.com/10395817/80330871-0e862180-8864-11ea-89ef-b5fd3f8982b9.png)
