### ISSUE TITLE
Add an option to hide and/or collapse the right panel

### ISSUE THREAD

**Issue by jahirfiquitiva** [liyasthomas/postwoman#818]
Hello

I'm enjoying postwoman so far, but I don't find the right panel (`History | Collections | Environments | Notes`) necessary to be shown all the time, so I wanted to ask for an option to hide, collapse it, or maybe even move it to the left menu maybe

Thanks in advance

**Comment by jahirfiquitiva** [comment]
Another option would be moving `Authentication | Headers | Parameters` to the right side

**Comment by liyasthomas** [comment]
sorry for the clutter in the current design. As of now, the right sidebar contains secondary actions and main view contains primary actions.

Let's see if anybody else raise you concerns.  Then we'll act on it.
