### ISSUE TITLE
The UI could use some improvements

### ISSUE THREAD

**Issue by mrchief** [liyasthomas/postwoman#825]
**Is your feature request related to a problem? Please describe.**

- It is very hard to find anything in the UI because of the layout and color combination. Everything looks kinda the same.
- The response area doesn't need to be laid out linearly - it eats up real estate and forces a scroll to see the response

![image](https://user-images.githubusercontent.com/781818/80646684-311e6300-8a3b-11ea-8700-6f932e8b615b.png)

**Describe the solution you'd like**
 - Overall, the UI needs to be judicial about real estate. We don't need all those fancy margins/paddings and oversized fonts.
 - Using different color backgrounds to demarcate request/response will help improve readability and reduce cognitive strain
 - I see mentions about UI revamp - if there's a beta version out, I'd love to give it a spin.

**Describe alternatives you've considered**
 - keep using postman :) 
 - or use insomnia? But I don't really want to!

**Comment by liyasthomas** [comment]
fyi, PW passes accessibility test by Lighthouse. Hope this settles the readability of the color contrast. However, you can switch themes from settings > themes to choose one that looks good in your monitor.

![image](https://user-images.githubusercontent.com/10395817/80657735-0f0bfb80-8aa2-11ea-9dd3-4e3b1bc98b1b.png)

Will work on tweaking the response area to optimise long scrolling issues 👍

**Comment by mrchief** [comment]
Thanks. 

> fyi, PW passes accessibility test by Lighthouse.

LOL, wish Lighthouse was a real person.
