### ISSUE TITLE
'Documentation Generated' response stacking past top of page if submit clicked enough times/fast enough

### ISSUE THREAD

**Issue by DGKSK8LIFE** [liyasthomas/postwoman#826]
**Describe the bug**
On the `/doc` route, if one clicks on generate documentation fast enough, the response oval shaped "tab" can stack almost infinitely, and clears over time; ie: there is no limit to how much it can stack.

**To Reproduce**
1. Go to `/doc`
2. Click on 'Generate Documentation` rapidly with an empty array in import collections
3. Response "tabs" will stack and block the button/stack above the top of the page

**Expected behavior**
There to be one notification or a verification that collections are actually imported before responding.

**Screenshots**
Unable to add screenshots, as they disappear quickly, but it happened.

**Comment by liyasthomas** [comment]
Quick fix: Don't do that

**Comment by DGKSK8LIFE** [comment]
> Quick fix: Don't do that

Why not just implement a stacking limit?

**Comment by DGKSK8LIFE** [comment]
> The current hotfix clears all previous toasts before triggering another. So kinda same effect with a simpler approach.

Ok! Is it merged to master branch/deployed yet or?

**Comment by liyasthomas** [comment]
Merged to master 14 hours ago.

**Comment by DGKSK8LIFE** [comment]
> Merged to master 14 hours ago.

Thanks!
