### ISSUE TITLE
Error: Network Error. Check console for details.

### ISSUE THREAD

**Issue by bloodzer0** [liyasthomas/postwoman#827]
I use docker to deploy postman, and there is an error in requesting https://www.baidu.com. I confirm that my docker can access the domain name.
![1](https://user-images.githubusercontent.com/17638514/80667188-067ee980-8ad1-11ea-8838-f9c62bcdc807.png)
![2](https://user-images.githubusercontent.com/17638514/80667215-18f92300-8ad1-11ea-92f2-1d3ab825c562.png)

**Comment by liyasthomas** [comment]
It's not an issue with PW. The endpoint: `https://www.baidu.com` doesn't allow Postwoman to fetch data. Servers can restrict specific URL based on different criterias such as geography.

Enable Proxy Mode (Settings > Proxy) to access such restricted endpoints. Proxy mode seems to be working.
