### ISSUE TITLE
Access to nonexistent routes will not be redirect to page 404

### ISSUE THREAD

**Issue by Xiphin** [liyasthomas/postwoman#849]
As the title:
https://postwoman.io/en
https://postwoman.io/xxx
![image](https://user-images.githubusercontent.com/3348428/81282679-175dcb00-908e-11ea-8979-9cf2a39b69df.png)
Console log:
![image](https://user-images.githubusercontent.com/3348428/81282843-50963b00-908e-11ea-9ef3-a26eebc3cd24.png)

**Comment by liyasthomas** [comment]
Issue have been identified. Will roll out a fix asap. Thanks for reporting.

**Comment by Xiphin** [comment]
> Issue has been identified. Will roll out a fix asap. Thanks for reporting.

It seems a vue-router problem:
https://github.com/vuejs/vue-router/issues/2881
But I'm not sure...

**Comment by Xiphin** [comment]
Bumping nuxt-i18n from 6.11.0 to 6.11.1 fixed it.

**Comment by liyasthomas** [comment]
Already bumped `nuxt-i18n`. We're facing a build deploy error with Netlify for the past 4 builds. Hopefully it will be fixed by EOD. Will close this issue then.

**Comment by liyasthomas** [comment]
We're currently facing a delayed production deploy issue with Netlify. Kindly be patient while changes are propagated to live site. Hopefully Netlify will fix this technical issue asap. I'll ping once changes are up on live.

**Comment by Xiphin** [comment]
Visiting postwoman.io in China is too slow, I built a Chinese version:
https://reqres.cn

**Comment by liyasthomas** [comment]
@Xiphin Good, kindly mention original repo. Also, if you make any enhancements - do shoot a PR.
