### ISSUE TITLE
Proxy privacy policy link

### ISSUE THREAD

**Issue by pr0gramista** [liyasthomas/postwoman#865]
**Describe the bug**
Link for Privacy Policy of proxy hosted by Apollo Software isn't working. Link appears in README file and settings page.

The link address is:
https://apollosoftware.xyz/legal/postwoman

The page does not exist.

**To Reproduce**
Go to the proxy section of settings or README page.

Click the link for Privacy Policy.

**Expected behavior**
I should be able to know how Apollo Software use collected data.

**Comment by liyasthomas** [comment]
@NBTX can you look into this real quick?

**Comment by liyasthomas** [comment]
Privacy page is back again - hence closing this issue.
