### ISSUE TITLE
Make docs on self-hosting Postwoman

### ISSUE THREAD

**Issue by jack1142** [liyasthomas/postwoman#868]
Some information on deploying Postwoman on your own would be useful.

Documents I think would be worth adding:
- how to host Postwoman on regular Linux machine
- how to host Postwoman using Netlify
- how to host Postwoman using Github Pages (? - not sure if that's possible but I saw mentions of it in this repo - I'm guessing that if it is, it's done with some CI like Travis or GH Actions)
- how to get Firebase functionalities working

I'm sure newcomers who want to self-host Postwoman could really appreciate such addition to the wiki

**Comment by liyasthomas** [comment]
Hi @jack1142 , thanks for raising concerns about hosting PW for a beginner. We do lack a quality Docs section. I admit that. But our readme is quite informative. You can find instructions on how to [develop](https://github.com/liyasthomas/postwoman/blob/master/README.md#developing-), serving the [Docker image](https://github.com/liyasthomas/postwoman/blob/master/README.md#docker--), and at last [releasing](https://github.com/liyasthomas/postwoman/blob/master/README.md#releasing-%EF%B8%8F) the build.

PW being a 100% static web app, I guess hosting it is a piece of cake 🍰. Anyways, I'm gonna write a "Hosting" section in Wiki which might resolve this issue.

**Comment by liyasthomas** [comment]
Here you go: https://github.com/liyasthomas/postwoman/wiki/Hosting

**Comment by jack1142** [comment]
@liyasthomas what about the firebase functionalities (the login through GH functionality for example)?

**Comment by liyasthomas** [comment]
Will update in an hour.

**Comment by jack1142** [comment]
@liyasthomas hi, just wanted to remind you about this issue since it might be easy to forget when it's already closed. If you didn't forget, sorry for bothering 😄

**Comment by liyasthomas** [comment]
@jack1142 I've updated the Wiki with basic Firebase integration docs. This is incomplete since Firebase functionalities are deeply coupled with our essential features.  I'll update as we move forward.
