### ISSUE TITLE
Show request completion time

### ISSUE THREAD

**Issue by sboulema** [liyasthomas/postwoman#871]
**Is your feature request related to a problem? Please describe.**
Not related to a problem. This is a feature request,

**Describe the solution you'd like**
We get a lot of extra info back when getting a response. Body, status code, etc.
But I would like to see how long the request took to complete. This would help in spotting any performance issues.

**Describe alternatives you've considered**
No alternatives that I know of...

**Additional context**
Possible solutions:
- https://stackoverflow.com/questions/49874594/how-to-get-response-times-from-axios
- https://github.com/BrockReece/axios-timing

**Comment by liyasthomas** [comment]
We're already showing a toast with request completion time. This might've been gone unnoticed.
![Screenshot_20200514-061213](https://user-images.githubusercontent.com/10395817/81880061-08a17780-95aa-11ea-8396-8340845b62f5.png)

**Comment by liyasthomas** [comment]
Feel free to reopen if the current implementation isn't enough.

**Comment by lewislbr** [comment]
Just to give an idea about this: could the time be saved in the request history, for example next to the HTTP method? So it doesn't get lost after the toast is gone.

**Comment by liyasthomas** [comment]
@lewislbr we're already saving request completion time to history. Toggle "show more" on history section to view all options.

![image](https://user-images.githubusercontent.com/10395817/83118591-2ca5a280-a0ec-11ea-997b-508d36c0f535.png)

**Comment by lewislbr** [comment]
@liyasthomas Awesome! Didn't see that, thanks!
