### ISSUE TITLE
Can't find Desktop app link anywhere

### ISSUE THREAD

**Issue by sa-** [liyasthomas/postwoman#872]
All links around the "Desktop App" section lead to the webpage for progressive webapps (which is not super helpful imo) and not an install link. 

Where can I download the desktop app?

**Comment by liyasthomas** [comment]
There's no installable native desktop app yet, you can install PWA in you desktop browser though.

**Comment by aradalvand** [comment]
Why wouldn't you just wrap it in Electron and release a standalone desktop version?!
