### ISSUE TITLE
Add support for "application/hal+json" Content-Type

### ISSUE THREAD

**Issue by davidyscott** [liyasthomas/postwoman#88]
**Is your feature request related to a problem? Please describe.**
Working with a HATEOAS service that uses HAL, I would like to be able to make requests with the "application/hal+json" media type.

**Describe the solution you'd like**
I would like an additional option from the content type dropdown.

**Additional context**
I believe I have made the necessary code changes, but as the CONTRIBUTING.md file for this repo has no information, I'm not sure how to submit the PR.

**Comment by liyasthomas** [comment]
If you believe you've made necessary changes to solve this issue, go on and make a PR. The contributing guidelines for this repo are still a WIP

**Comment by davidyscott** [comment]
@liyasthomas Done, #90, thanks!
