### ISSUE TITLE
Cannot connect my local websocket server

### ISSUE THREAD

**Issue by WafeiBaBa** [liyasthomas/postwoman#880]
![image](https://user-images.githubusercontent.com/34429036/82281551-30d31100-99c4-11ea-839a-84b395b17912.png)

Like this picture above, the connect button is disable.

**Comment by liyasthomas** [comment]
@WafeiBaBa Thanks for reporting the issue. Will fix it ASAP. Meanwhile you can access your local WebSocket endpoints from `wss://127.0.0.1:8080/ws`

**Comment by AndrewBastin** [comment]
@liyasthomas any progress ? else I will pick it up.

**Comment by liyasthomas** [comment]
@AndrewBastin sorry for the delay. I caught up with some personal stuffs. The issue is regarding the newly implemented regex for WSS url validation. Port number on localhost isn't passing. Think you can add that to regex.
