### ISSUE TITLE
Handle JSON Parameter list validation

### ISSUE THREAD

**Issue by someshkar** [liyasthomas/postwoman#891]
**Is your feature request related to a problem? Please describe.**
The ability to add and remove fields when POSTing JSON bodies to an API is only limited to key value pairs. When trying to POST data to a REST API which consumes a JSON array, I don't see a clear way to do this. The JSON body looks like this:

```json
{
	"domains": ["google.com", "facebook.com"]
}
```

**Describe the solution you'd like**
I'd like to be able to add an array as the value of a key in the JSON body.

**Describe alternatives you've considered**
One good solution would be having sub entries under one key-value pair in the UI.

**Additional context**
This is what currently happens when I try to use an array as a key-value pair in the JSON body:

![image](https://user-images.githubusercontent.com/14039437/82537839-53059400-9b68-11ea-90cc-ffa8252bf8ac.png)

And attempting to use single quotes just results in the array getting converted to a string on it's own:

![image](https://user-images.githubusercontent.com/14039437/82537963-93651200-9b68-11ea-8abf-f8eeba757401.png)

**Comment by AndrewBastin** [comment]
@someshkar Thank you for opening the issue.

We will look into the issue ASAP.

For now, I suggest you use the Raw Input mode to edit the JSON directly.

**Comment by someshkar** [comment]
> @someshkar Thank you for opening the issue.
> 
> We will look into the issue ASAP.
> 
> For now, I suggest you use the Raw Input mode to edit the JSON directly.

@AndrewBastin How exactly do I access the Raw Input mode for editing the JSON directly?

**Comment by liyasthomas** [comment]
@someshkar toggle "Raw Input" 
![InShot_20200522_084334764](https://user-images.githubusercontent.com/10395817/82627758-b941f380-9c08-11ea-9d97-775c2d3350f5.jpg)

**Comment by someshkar** [comment]
@liyasthomas Alright thanks!

**Comment by liyasthomas** [comment]
key - value pairs should only be used for string types. For arrays, switch to "Raw input".

**Comment by AndrewBastin** [comment]
@liyasthomas won't it be nice if there is warning or toast or something about this ?

**Comment by liyasthomas** [comment]
Okay, a toast should be appropriate.

**Comment by someshkar** [comment]
Yeah, a toast makes sense for now.
