### ISSUE TITLE
Add authentication to MQTT

### ISSUE THREAD

**Issue by BOZG** [liyasthomas/postwoman#898]
**Is your feature request related to a problem? Please describe.**
The MQTT function works great but doesn't allow connections to MQTT servers that require authentication. 

**Describe the solution you'd like**
The ability to use authentication with the MQTT feature. 

**Describe alternatives you've considered**
I haven't considered any as I don't know what's needed to implement this feature!

**Comment by rahulnpadalkar** [comment]
Authentication using username and password @BOZG ? Thanks!

**Comment by BOZG** [comment]
> Authentication using username and password @BOZG ? Thanks!

In my case I meant username and password but MQTT also allows for X509 certificate authentication and client ID authentication.

Client ID can be used as a standalone authentication method, as an additional layer to basic auth (so that username, password and client ID must match) or a simple client identifier (which I use it for).

**Comment by rahulnpadalkar** [comment]
Postwoman uses paho-mqtt library
Ref doc -  https://www.eclipse.org/paho/files/jsdoc/Paho.MQTT.Client.html

I don't see certificate base authentication option available (Correct me if i am wrong). Any suggestions?

**Comment by BOZG** [comment]
> Postwoman uses paho-mqtt library
> Ref doc - https://www.eclipse.org/paho/files/jsdoc/Paho.MQTT.Client.html
> 
> I don't see certificate base authentication option available (Correct me if i am wrong). Any suggestions?

Sorry for the delay in replying! Unfortunately that side of things is a little beyond me. Certificate authentication is definitely a thing though but maybe it's just not supported by Paho?

**Comment by liyasthomas** [comment]
Adding auth to MQTT broker isn't in roadmap. Hence closing this issue for now.
