### ISSUE TITLE
Collections & Environments not synced

### ISSUE THREAD

**Issue by dhemas** [liyasthomas/postwoman#900]
**Describe the bug**
My collections & environments not synced, even after toogling sync option in setting. Only my request histories were synced.

**To Reproduce**
1. Open postwoman
2. Signin with google
3. Import collections
4. Toggling on sync option
5. Try to open postwoman in incognito and in my smartphone, logged in with google
6. Got blank collections & environments, only my histories were synced

**Expected behavior**
All collections & environments are synced

**Desktop:**
 - OS: Manjaro
 - Browser Chromium
 - Version 81.0.4044.138

**Additional info**
I use postwoman v1.9.7, where [#854](https://github.com/liyasthomas/postwoman/pull/854) already merged

**Comment by liyasthomas** [comment]
@dhemas is there any errors in console log?

**Comment by dhemas** [comment]
> @dhemas is there any errors in console log?

Console log is clean, no error or exception whatsoever. If you my help to do something to debug I'll gladly help

**Comment by liyasthomas** [comment]
Please make sure toggles for sync in Settings are turned on. Also try logging out and in once again to check the settings are synced.

**Comment by myussufz** [comment]
I also have the same issue, the environment and collection are not synced when opening in another browser, I realize this happen because of the collection and environment are reading from Vuex state instead of reading from firebase.

**Comment by myussufz** [comment]
@liyasthomas  I have created a pull request for this fixed, https://github.com/liyasthomas/postwoman/pull/926, you may review this pull request.
