### ISSUE TITLE
`pw.response` seems not to work

### ISSUE THREAD

**Issue by lapo-luchini** [liyasthomas/postwoman#905]
**Describe the bug**
Examples from the wiki page seem not to work (yet?).

**To Reproduce**
1. create GET JSON call
2. copy test from wiki: `pw.expect(pw.response.status).toBe(200);`
3. execute call
4. see error: `Expected Cannot read property 'value' of undefined to be 200`

**Expected behavior**
A successful test.

**Screenshots**
![image](https://user-images.githubusercontent.com/420454/83029688-3e773f00-a033-11ea-9ce7-3ca030c17427.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 83
(using extension to do the clal locally, since it's only accessible via a VPN)

**Comment by liyasthomas** [comment]
@lapo-luchini can you share a reproducible endpoint/link?
I can't reproduce the issue at my end.

**Comment by lapo-luchini** [comment]
I seem to be able to reproduce that with any RESP API really (thankfully, because my own is only accessible via private VPN) and even without variables / environments:
URL: `http://dummy.restapiexample.com/api/v1/employees`
Test code:
```
pw.test('Response', () => {
    pw.expect(pw.response.status).toBe(200);
});
```
Same result:
![image](https://user-images.githubusercontent.com/420454/83035647-01627b00-a03a-11ea-9691-4895d3f0ae09.png)
Application reports itself to be v.1.9.7, by the way.

**Comment by liyasthomas** [comment]
The endpoint: `http://dummy.restapiexample.com/api/v1/employees` won't work because it is served with `http` protocol. I tried with `https` but it refused to connect.

Postwoman being hosted in `https` protocol - browser will restrict all non-secure `http` requests.

To test non-https endpoints, please use **Browser extension** (link in readme) or Toggle Proxy mode on from settings > proxy.

And also, tests works fine - let me know whether the issue still persists.

**Comment by lapo-luchini** [comment]
But _I am_ using the browser extension, in fact.
And, watching the extension's background page, the request worked correctly too:
![image](https://user-images.githubusercontent.com/420454/83053744-8016e280-a051-11ea-8e35-cb49a0ee29ef.png)

**Comment by liyasthomas** [comment]
Can you check if there's any errors in console log?

**Comment by lapo-luchini** [comment]
Yes there is, I tried debugging but the (internally beautified) code isn't clear to me.
(I tried with a local `git clone` + `npm run serve` but then it's in `http` and doesn't happen)
Do you have an `https` deploy with included SourceMaps?
(I also tried deploying it in `https` on my own, but then it fails connecting to my Chrome extension)

Console error:
```
TypeError: Cannot read property 'value' of undefined
    at 519987073f102793edd6.js:1
    at 519987073f102793edd6.js:1
    at d (90e58649f81013ae3376.js:2)
    at Generator._invoke (90e58649f81013ae3376.js:2)
    at Generator.S.forEach.t.<computed> [as next] (90e58649f81013ae3376.js:2)
    at r (90e58649f81013ae3376.js:2)
    at l (90e58649f81013ae3376.js:2)
```

Innermost line:
`null !== F.a.currentUser && F.a.currentSettings[2].value && F.a.writeHistory(r)
`
Third line:
`return { type: "normal", arg: t.call(e, n) }`

**Comment by liyasthomas** [comment]
Try clearing all app cache and uninstalling service worker from dev tools.

**Comment by lapo-luchini** [comment]
Cleaned app cache & unregistered worker: **it works now!**
I was logged in with GitHub, yes.
Now I logged again and it seems to be still working.
