### ISSUE TITLE
Cant Import Postman Global Environment Variables

### ISSUE THREAD

**Issue by AllanOricil** [liyasthomas/postwoman#907]
I tried to import my global environment variables from postman to postwoman and it did not work. It also did not show any error or warning messages.

How to reproduce:
1 - create global variables in Postman
2 - Export the global variables
3 - Import the file into Postwoman

Expected Behavior:
To have the Global variables available inside Postwoman.

Actual Behavior
Global variables imported from Postman don't appear in Postwoman.

**Comment by liyasthomas** [comment]
@AllanOricil can you share a sample exported json file?

**Comment by AllanOricil** [comment]
Hi liyasthomas. Follow the json for the Globals.

How can I see the console?

````json
{
	"id": "5097f72d-5549-4e77-8336-a9b1e4db4b59",
	"values": [
		{
			"key": "SALESFORCE_TEST_URL",
			"value": "https://test.salesforce.com",
			"enabled": true
		},
		{
			"key": "SALESFORCE_PRODUCTION_URL",
			"value": "https://login.salesforce.com",
			"enabled": true
		}
	],
	"name": "My Workspace Globals",
	"_postman_variable_scope": "globals",
	"_postman_exported_at": "2020-05-26T13:59:05.571Z",
	"_postman_exported_using": "Postman/7.25.0"
}
````

**Comment by liyasthomas** [comment]
Found the issue. Pushing a hotfix now :+1:

**Comment by AllanOricil** [comment]
Thanks. Im gonna do another test :)

**Comment by AllanOricil** [comment]
It worked
![image](https://user-images.githubusercontent.com/55927613/83075343-0e876600-a04a-11ea-92f6-2346b94edbcf.png)
