### ISSUE TITLE
Integrate PostWoman In our Webapp

### ISSUE THREAD

**Issue by ivpnoida-tj** [liyasthomas/postwoman#918]
Hi,

We have an Web application based ETL tool that comprises a generic UI driven API Runner Component. Our backend is currently in C# as well as java.

We wish to integrate within our API Runner a UI (something like POSTMAN/POSTWOMAN) that provides a variety of features to configure an API run on UI, along with the backend written in C# and Java that would trigger the API.

Would it be possible to integrate postwoman within our ETL tool?

**Comment by liyasthomas** [comment]
Hi @ivpnoida-tj check out our Wiki on Hosting Postwoman here: https://github.com/liyasthomas/postwoman/wiki/Hosting

Let me know if there's any difficulties following the Wiki.
