### ISSUE TITLE
Search on History

### ISSUE THREAD

**Issue by liyasthomas** [liyasthomas/postwoman#92]
**Is your feature request related to a problem? Please describe.**
User must be able to search for queries such as method, URL, path etc on History entries.

**Describe the solution you'd like**
Search input is shown inside History section. On each input, filtered list appear below.

**Describe alternatives you've considered**
Filter the history entries based on parameters: method, URL, path etc.

**Additional context**
10x feature: Sort history based on time, status code and any other applicable parameters

**Comment by izerozlu** [comment]
Resolved with #106.

**Comment by izerozlu** [comment]
@liyasthomas I haven't seen the additional context before. Will look into that as well.

**Comment by liyasthomas** [comment]
Tha's okay! Thanks for the quick PR :ok_hand:

**Comment by liyasthomas** [comment]
@izerozlu any updates on the sort feature for history entries?

**Comment by izerozlu** [comment]
For now I couldn't have found the time for it. I'll try to get something g
up this week, if that's okay.

I've been quite busy with these past few weeks. I'll be marrying in a month
😊
Sorry about the delay!

**Comment by liyasthomas** [comment]
Congratulations ✨💞🎉
Wish both of you a happy married life 💜

**Comment by izerozlu** [comment]
Thanks! 💕
That and the load on the work have been holding me from the postwoman these
weeks.

I'll try to catch up to the project soon!

**Comment by nityanandagohain** [comment]
I would love to work on the sort feature.

**Comment by izerozlu** [comment]
@nityanandagohain be my guest, go for it!

**Comment by linpan** [comment]
hope can search body keywords
