### ISSUE TITLE
Support downloading binary responses

### ISSUE THREAD

**Issue by pryon** [liyasthomas/postwoman#929]
**Describe the bug**
When a binary file (e.g. an image) is requested, the binary content of the response is properly displayed in the response body window, however if the **Download file** button is clicked, a corrupted blob of data is downloaded instead of the actual binary file that was requested.

**To Reproduce**
1. Go to postwoman.io
2. Set `http://tim.org/images/TIMtitle.GIF` as the request URL
3. Click **Send**
4. When the response has arrived, click on the **Download file** button above the response body textfield
5. Examine contents of the downloaded binary file (e.g. with a hex editor), or just try to open the image

**Expected behavior**
The same binary file gets downloaded that was requested from the remote server.

**Screenshots**
Hexdumps of the original and postwoman-downloaded image file.
Left: original image file, downloaded via *right-click, Save image as...*
Right: image file downloaded via postwoman.io

![image](https://user-images.githubusercontent.com/12021392/84259358-a68c5180-ab18-11ea-8959-e1f19895b2a8.png)

**Desktop:**
 - OS: Windows 10 1909
 - Browser: Chrome
 - Version: 83.0.4103.97

**Additional context**
When looking at the corrupted file, notice the double-quote in the very beginning and the very end, the unicode-escaped sequences and the occasional new `EF BF BD` byte triplets. Its size is also 2-3 times bigger than that of the original file.

**Comment by liyasthomas** [comment]
@pryon Thanks for reporting the issue. We used `Blob()` for generating binary file to download. Actually it was intented for `text/json` formats.

Need to redo how to handle binary files :+1:
