### ISSUE TITLE
Show "Send" button all over the page or enable hotkeys

### ISSUE THREAD

**Issue by tiagoa** [liyasthomas/postwoman#94]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when configuring the request and then having to scroll up the page just to hit the "Send" button.

**Describe the solution you'd like**
Set a fixed position for the button "Send" or/and enable hotkeys.

**Comment by NBTX** [comment]
What if we made the request section sticky to the top of the window as you scroll?
Though, either way, hotkeys does seem like a good idea.

**Comment by izerozlu** [comment]
I'm working on an implementation with the [IntersectionObserver](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API).
After that implementation i'll look into enabling some hotkeys as well.

**Comment by liyasthomas** [comment]
I did a UI with sticky request section, but it broke responsiveness. Looking forward for suggestiongs.
