### ISSUE TITLE
Unable to fetch schema from localhost GraphQL server.

### ISSUE THREAD

**Issue by prashant1k99** [liyasthomas/postwoman#940]
**Describe the bug**
Unable to fetch GraphQL schema or do any query when running on Localhost

![Postwomen Err](https://raw.githubusercontent.com/prashant1k99/testing-graphql/master/postwomen%20err.png)

**Comment by liyasthomas** [comment]
@prashant1k99 did you install the browser extension?

**Comment by prashant1k99** [comment]
No,  i have added the app to home screen. PWA...

**Comment by liyasthomas** [comment]
You've to install [Browser extension](https://github.com/AndrewBastin/postwoman-extension) to access `localhost`
