### ISSUE TITLE
POST requet error

### ISSUE THREAD

**Issue by chenyu9390** [liyasthomas/postwoman#947]
POSTWOMAN post request
![TIM截图20200620184246](https://user-images.githubusercontent.com/8199403/85199934-f42d6900-b325-11ea-83ca-c317f8e7fd4e.jpg)
postman post request
![TIM截图20200620184313](https://user-images.githubusercontent.com/8199403/85199938-fabbe080-b325-11ea-8d87-0ec0115d5a0c.jpg)

**Comment by liyasthomas** [comment]
Kindly install Browser extension (link in readme) to test endpoints served locally
