### ISSUE TITLE
Enable user-select on websocket and other realtime message logs 

### ISSUE THREAD

**Issue by 01010101lzy** [liyasthomas/postwoman#951]
**Is your feature request related to a problem? Please describe.**

It's very often for someone to select and/or copy the log of some websocket communication for debug purposes, so it should be `user-select` = `text` or something similar.

**Describe the solution you'd like**

Make websocket communication log `user-select`-able

**Describe alternatives you've considered**

Directly copy stuff out of developer tool (F12 menu)

**Additional context**

None

**Comment by AndrewBastin** [comment]
@01010101lzy thank you for opening the issue, I will look into this ^_^

**Comment by 01010101lzy** [comment]
So fast! Thanks!
