### ISSUE TITLE
TypeError: Cannot read property 'value' of undefined - when logged in

### ISSUE THREAD

**Issue by imambungo** [liyasthomas/postwoman#961]
**Describe the bug**
Javascript error after sending requests. Only happens when logged in using either GitHub or Google account.

**To Reproduce**
1. Login using either GitHub or Google account
2. Do a GET request to https://httpbin.org/get
3. Scroll down to Response

**Expected behavior**
Get 200 HTTP response status code, no error.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Chrome
 - Version 80

**Comment by liyasthomas** [comment]
I can't produce issue at my end. Can you please try a force-reload after logging out and logging in again?

**Comment by imambungo** [comment]
Did that already, still getting the error tho

**Comment by liyasthomas** [comment]
Can you try another endpoint in which I can reproduce issue at my end. Generally this issue is caused when there's No internet connectivity / web app isn't loaded completely.

**Comment by liyasthomas** [comment]
Fixed in latest release of [Chrome extension v0.13](https://chrome.google.com/webstore/detail/postwoman-browser-extensi/amknoiejhlmhancpahfcfcfhllgkpbld).
Extension should update automatically on Chrome, if not do manual update form `chrome://extensions`.

Do let me know if the issue persists.

**Comment by ninformations** [comment]
This is happening when you have just logged in and not yet enabled your sync in settings page. After enabling sync from setting the error goes away and everything works normally.
