### ISSUE TITLE
Textarea display problem in super hi-dpi

### ISSUE THREAD

**Issue by RickoNoNo3** [liyasthomas/postwoman#965]
While I was using postwoman in chrome, I found a problem: **all of textareas (with linenumber) undisplayed**.
(only happened in chrome/new edge, no ff/old edge)

You will easily reappear the problem:
make your screen dpi in a super high mode, such as 1920x1080 with 150% scales. And switch to POST method in the postwoman. Then check raw input. you will see that textarea of raw request body has been undisplayed.

Magically, when I changed browser display scale (ctrl + as you know). In any way, the textarea redisplayed.

----

![issue](http://rickonono3.top/postwoman.1.jpg)

**Comment by liyasthomas** [comment]
@RickoNoNo3 I tried to reproduce the issue at my end but I couldn't. Can you tell a little more about you device. which operating system? Chrome version? etc..
![image](https://user-images.githubusercontent.com/10395817/86070475-76422e00-ba9a-11ea-8ff4-25c117017dfe.png)

**Comment by RickoNoNo3** [comment]
@liyasthomas I use Chrome 83.0.4103.116 (latest) on Windows 10 2004. Screen: 1920x1080 (150% as 1280x720)

I tried more about how to make it reappeared and noticed:

-  In 100% default scaling of my Chrome, `document.body.clientWidth` shows `1020`, **with issue**
-  In 90% scaling(`1134`), **with issue**
-  In l/e 80%(`1275`), no issue
-  In g/e 110%(`927`), no issue
-  In media keyword triggered, no issue
- When textareas are undisplayed, adjusting the zoom to safe scale on the same page will make them show.
- Once textareas are displayed, no operations can make it restored to undisplay. 

These conclusions are established, unless you reload a textarea(maybe turn off raw input and check it again). reloading a textarea has the same behavior with reloading the page.

So in my mind, this issue appears in a kind of environment with specific width. And it is a problem that occurs when generating textarea elements (not related to css).

btw `body.clientWidth` in default scaling of firefox is `1280` while in Chrome is `1020`. The true width of 150% of 1920x1080 is indeed `1280`. So my Chrome has an unexpected over zooming (bigger text as well). Edge too.

**Comment by RickoNoNo3** [comment]
nonono, not just page client width, I cannot get it appeared by resizing my browser window to the "problem width". Instead, it still make issue in 90% and 100% scaling no matter how big the window is.
Maybe It is directly related to the total width of the screen? or the dpi?

**Comment by liyasthomas** [comment]
Noted. Looking into it.

**Comment by liyasthomas** [comment]
I guess we can ignore this UI issue since it's only reproducible in such an edge case of super-high dpi. Let me know if you it is reproducible in normal situations.

**Comment by RickoNoNo3** [comment]
You are right. It works well to set a different zoom ratio as default of Chrome.
