### ISSUE TITLE
Installing postwoman locally

### ISSUE THREAD

**Issue by Owez** [liyasthomas/postwoman#969]
**Describe the bug**
I cannot find any documentation to install postwoman as I would like a local install and not have to publish my debugging api publically. It seems like https://github.com/liyasthomas/postwoman/wiki/PWA is all PR for what is suppost to be docs, could anyone lead me to some actual docs?

**To Reproduce**
1. Find easy-to-read installation docs

**Expected behavior**
Some simple documentation that underlines how to install postwoman locally

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 + Windows
 - Browser: Firefox
 - Version: Latest, ~75

**Comment by liyasthomas** [comment]
https://github.com/liyasthomas/postwoman#local-development-environment

1. Clone this repo with git.
2. Install dependencies by running npm install within the directory that you cloned (probably postwoman).
3. Start the development server with npm run dev.
4. Open development site by going to http://localhost:3000 in your browser.

**Comment by Owez** [comment]
Ah, I see. Assumed that "developing" was for developing (e.g. contributer setup)

**Comment by Spriithy** [comment]
Any way you could bundle this ? It's pretty annoying to have to install something by hand

**Comment by liyasthomas** [comment]
Do you mean bundle "as a installer"?

**Comment by Spriithy** [comment]
Yeah, something like that. I'm using the docker image, but maybe a snap, deb package or something would be interesting

**Comment by sheecegardezi** [comment]
having a snap install will be awesome!
