### ISSUE TITLE
Add version number in footer

### ISSUE THREAD

**Issue by NBTX** [liyasthomas/postwoman#97]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Simply add the version number (with short commit hash) to the footer.
Perhaps display a 'Check for updates' or 'Install update' if there is an update available.

**Describe alternatives you've considered**
n/a

---

If this is implemented, should we use the [GitHub releases](https://github.com/liyasthomas/postwoman/releases) version number or get it from `package.json`?

**Comment by liyasthomas** [comment]
That's a good suggestion.
