### ISSUE TITLE
localhost request error

### ISSUE THREAD

**Issue by xiaogu-space** [liyasthomas/postwoman#979]
![image](https://user-images.githubusercontent.com/8435230/86589817-f4359600-bfc0-11ea-9f40-1d52a1a2ae6d.png)

![image](https://user-images.githubusercontent.com/8435230/86589843-fd266780-bfc0-11ea-8bf4-a7722b9ceff3.png)

![image](https://user-images.githubusercontent.com/8435230/86589802-ebdd5b00-bfc0-11ea-8ff3-eca1bf54bfa4.png)

**Comment by liyasthomas** [comment]
This is a known issue with the current published Chrome extension (v.0.12). A patched version is under review waiting to be published. Kindly stay tuned for the next update which will be published in upcoming days. Meanwhile use Firefox extension or downgrade chrome extension.

**Comment by xiaogu-space** [comment]
OK,thanks

**Comment by Sensanaty** [comment]
@xiaogu-space As a temporary workaround, you can send requests to an `ngrok` tunnel if you enable Postwoman's default proxy.
