### ISSUE TITLE
Saving response data in env variable

### ISSUE THREAD

**Issue by Sensanaty** [liyasthomas/postwoman#984]
Is it possible to save a response into the environmental variables?

I'm building an API where I have to authenticate via a JWT, so first I send the credentials to my `authenticate` endpoint, then after that I included the JWT as a Bearer Token in future requests.

Is there a way to automatically save the response body into a env variable? I know I can do a pre-request script where I do `pw.env.set` (which doesn't work in the tests), but my token has a short lifespan of 5 minutes so I'd need to manually override this constantly.

Does this feature exist as of yet?

**Comment by liyasthomas** [comment]
At the moment there's no such feature to automatically save response data to environment.
