### ISSUE TITLE
Content-Type revamping

### ISSUE THREAD

**Issue by nickpalenchar** [liyasthomas/postwoman#99]
I wanted to start a discussion around the future of Content-Type and what direction everyone thinks we should go in. @NBTX mentioned a great idea in #63 which I'll requote:

> I think we should make content-type a text field with 'command line completion' (autocomplete) for commonly used content types, rather than restricting to these two content types.

I personally love this idea. In addition to the auto-complete, a user could chose their own custom type, so that new types would not have to be manually implemented (#88). 

But a related issue I see is that Content-Type is a **header** and nothing more. POST/PUT requests don't require a Content-Type header to succeed, odd as it would be to omit one. Within the context of postwoman UI you could technically have a Content-Type in the header section while the Content-Type dropdown was selected. It wouldn't be apparent to the user which one was actually set.

So I propose a few changes. First is to move the headers above the body, making the hierarchy `Request > Headers > Request Body > Authentication > Parameters > Response > History`. Second, remove the Content-Type dropdown and use it within the Headers section. Third, auto expand the Headers sections when requests types that expect Content-Type is selected--when this happens, Content-Type can pre-populate with `application/json`. The user is then free to modify that header or remove it entirely.

Open for discussion--when a conclusion is met I'll make a separate issue detailing the plan

**Comment by nickpalenchar** [comment]
Looks like no discussion needed so I'll be running with this!

**Comment by liyasthomas** [comment]
Revamping UI is under construction. Changes will reflect your suggestions ✌️

**Comment by NBTX** [comment]
@nickpalenchar Just letting you know I'm working on autocomplete at the moment already.

**Comment by nickpalenchar** [comment]
Very nice, thanks for letting me know 👍

**Comment by michalsisak** [comment]
Is this implemented? I can see some PR was merged, then reverted and merged again but I can't see any autosuggestions or completions in a header tab.

**Comment by liyasthomas** [comment]
Content-Type for `POST` requests have been revamped with autosuggestions. Not for Headers. Headers can be added manually.
