### ISSUE TITLE
Cannot "Get schema" on GraphQL page

### ISSUE THREAD

**Issue by liyasthomas** [liyasthomas/postwoman#994]
**Describe the bug**
"Get schema" on GraphQL page has been broken since today.

**To Reproduce**
1. Go to https://postwoman.io/graphql
2. Click on 'Get schema'
3. Scroll down to 'Schema'

**Expected behavior**
"Get schema" should produce actual value.

**Screenshots**
```
Error: Invalid or incomplete introspection result. Ensure that you are passing "data" property of introspection response and no "errors" was returned alongside: undefined.. Check console for details.
```

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser: Chrome
 - Version: latest

**Additional context**
@AndrewBastin I don't think it's because of the recent improvements with browser extension or proxy. This seems to be an updated syntax from the GraphQL client.

| Site | Extension OFF & Poxy OFF | Extension ON & Proxy OFF | Extension OFF & Proxy ON | Extension ON & Poxy ON |
| ----------- | ----------- | -----------  | -----------  | -----------  |
| [Live](https://postwoman.io/) | [x] working | [ ] failed `SyntaxError: Unexpected token  in JSON at position 27692. Check console for details.` | [ ] failed `SyntaxError: Unexpected end of JSON input. Check console for details.` | [ ] failed `SyntaxError: Unexpected end of JSON input. Check console for details.` |

**Comment by AndrewBastin** [comment]
Yeah, I don't think it's from the binary responses either. I will have a look.

**Comment by AndrewBastin** [comment]
Nevermind, it is the binary responses :sweat_smile: 

Mannn, we need a better test suite :sweat_smile:

**Comment by liyasthomas** [comment]
Updated description with issue's current state.

- [x] Extension OFF & Poxy OFF
- [ ] Extension ON & Proxy OFF
- [ ] Extension OFF & Proxy ON
- [ ] Extension ON & Poxy ON

**Comment by levrik** [comment]
@liyasthomas Just want to add that this issue is present for a few weeks already now.

**Comment by liyasthomas** [comment]
Try disabling extension and proxy from settings for a hotfix.

**Comment by AndrewBastin** [comment]
@NBTX the proxy is giving error on trying to send a binary request.

**Comment by AndrewBastin** [comment]
And about the extension stuff, extension without proxy works fine for me, I can't seem to reproduce any errors for v0.14. So @levrik , if the issue persists, can you pass more info (console logs for both the extension and postwoman) so I can figure it out.

Extension with proxy had some small code oversight regarding content types, But I have fixed it in AndrewBastin/postwoman@ef17471b4f2189b63c94366ee1f282e3b3e40fe9

**Comment by NBTX** [comment]
> @NBTX the proxy is giving errors on both binary and non-binary requests.
> 
> I tried debugging this with Postwoman (turn off proxy of course): https://postwoman.io/?method=POST&url=https://postwoman.apollosoftware.xyz&path=/&contentType=application/json&rawParams=%7B%0A%20%20%22method%22:%20%22GET%22,%0A%20%20%22url%22:%20%22https://reqres.in/api/users%22,%0A%20%20%22auth%22:%20null,%0A%20%20%22headers%22:%20%7B%7D,%0A%20%20%22data%22:%20null,%0A%20%20%22credentials%22:%20true,%0A%20%20%22wantsBinary%22:%20true%0A%7D
> 
> Disabling `wantsBinary` (or removing it) still returns a failed request.

The request succeeded for me with `wantsBinary` both enabled and disabled using the link you provided.

**Comment by AndrewBastin** [comment]
@NBTX at the time it failed, but then later it started working again

**Comment by AndrewBastin** [comment]
@liyasthomas can you check if the issue persists with the code in my fork [https://github.com/AndrewBastin/postwoman/tree/bug/994](https://github.com/AndrewBastin/postwoman/tree/bug/994)

**Comment by liyasthomas** [comment]
Issue persists.
```
Error: (Proxy Error) Request failed.. Check console for details.
```

**Comment by AndrewBastin** [comment]
@liyasthomas, that error is what I described earlier and is associated with the proxy not with the app code. Use the URL in the quote below and you can see it is the issue with the proxy.


> @NBTX the proxy is giving errors on both binary and non-binary requests.
> 
> I tried debugging this with Postwoman (turn off proxy of course): https://postwoman.io/?method=POST&url=https://postwoman.apollosoftware.xyz&path=/&contentType=application/json&rawParams=%7B%0A%20%20%22method%22:%20%22GET%22,%0A%20%20%22url%22:%20%22https://reqres.in/api/users%22,%0A%20%20%22auth%22:%20null,%0A%20%20%22headers%22:%20%7B%7D,%0A%20%20%22data%22:%20null,%0A%20%20%22credentials%22:%20true,%0A%20%20%22wantsBinary%22:%20true%0A%7D
> 
> Disabling `wantsBinary` (or removing it) still returns a failed request.


@NBTX

**Comment by liyasthomas** [comment]
@NBTX proxy is down

**Comment by AndrewBastin** [comment]
Does this issue still need to stay open ?

**Comment by liyasthomas** [comment]
I'm still having issues when Proxy is turned on. Is it just me?

**Comment by AndrewBastin** [comment]
Well, it is not you, the proxy is down. But I think #1027 is a more suitable issue to be open right now ? As the extension based issues are fixed.

**Comment by liyasthomas** [comment]
Track this issue further on #1027

**Comment by Jawmo** [comment]
Came here with same error but different problem.

Django users, make sure you have this in your settings middleware:

`"corsheaders.middleware.CorsMiddleware"`
